import type { ExecutionRequest, ExecutionResult, Executor, WorkerDescriptor, WorkerRegistry } from "../application/execution.js";
import { signRequest, type HmacCredentials } from "./hmac-auth.js";
import type{VerificationExecutor}from"../application/verification.js";
import type{VerificationRequest,VerificationResult}from"../domain/verification.js";

export interface RemoteWorkerConfig { workerId:string; baseUrl:string; credentials:HmacCredentials }
export class RemoteTransportError extends Error {}
async function request(config:RemoteWorkerConfig,method:string,path:string,body="",fetcher:typeof fetch=fetch):Promise<Response>{const headers=signRequest(config.credentials,method,path,body);const init:RequestInit={method,headers:{...headers,...(body?{"content-type":"application/json"}:{})},signal:AbortSignal.timeout(30_000)};if(body)init.body=body;return fetcher(new URL(path,config.baseUrl),init);}
export class RemoteWorkerRegistry implements WorkerRegistry { constructor(private readonly configs:readonly RemoteWorkerConfig[],private readonly fetcher:typeof fetch=fetch){}async get(workerId:string):Promise<WorkerDescriptor|null>{const config=this.configs.find(item=>item.workerId===workerId);if(!config)return null;try{const response=await request(config,"GET","/v1/descriptor","",this.fetcher);if(!response.ok)return null;const value=await response.json() as WorkerDescriptor;if(value.workerId!==workerId||!Array.isArray(value.capabilities)||!Array.isArray(value.workspaceIds)||!Array.isArray(value.executorKinds))return null;return structuredClone(value);}catch{return null;}} }
export interface RemoteExecutionStatus { status:string;startedAt:string|null;finishedAt:string|null;summary:string;evidence:string[];baseHead?:string;candidateBranch?:string;candidateHead?:string }
export class RemoteCodexExecutor implements Executor { constructor(private readonly configs:readonly RemoteWorkerConfig[],private readonly workerIdForRepository:(repository:string)=>string|null,private readonly fetcher:typeof fetch=fetch){}async execute(value:ExecutionRequest):Promise<ExecutionResult>{const config=this.config(value.repository);const submit=await request(config,"POST","/v1/executions",JSON.stringify(value),this.fetcher);if(!submit.ok)throw new RemoteTransportError(`worker rejected execution (${submit.status})`);for(let attempts=0;attempts<360;attempts++){const record=await this.status(value.repository,value.executionId);if(!record)throw new RemoteTransportError("worker execution not found");if(!["QUEUED","RUNNING"].includes(record.status))return toResult(value.executionId,record);await new Promise(resolve=>setTimeout(resolve,1000));}return{executionId:value.executionId,status:"TIMED_OUT",startedAt:new Date().toISOString(),finishedAt:new Date().toISOString(),summary:"Remote execution status timeout",evidence:[],retryable:true};}async status(repository:string,executionId:string):Promise<RemoteExecutionStatus|null>{const response=await request(this.config(repository),"GET",`/v1/executions/${encodeURIComponent(executionId)}`,"",this.fetcher);if(response.status===404)return null;if(!response.ok)throw new RemoteTransportError(`worker execution unavailable (${response.status})`);return response.json() as Promise<RemoteExecutionStatus>;}async cancel(repository:string,executionId:string):Promise<RemoteExecutionStatus|null>{const response=await request(this.config(repository),"POST",`/v1/executions/${encodeURIComponent(executionId)}/cancel`,"",this.fetcher);if(response.status===404)return null;if(!response.ok)throw new RemoteTransportError(`worker cancel failed (${response.status})`);return response.json() as Promise<RemoteExecutionStatus>;}private config(repository:string):RemoteWorkerConfig{const config=this.configs.find(item=>item.workerId===this.workerIdForRepository(repository));if(!config)throw new RemoteTransportError("remote worker is not configured");return config;}}
export function toResult(executionId:string,record:RemoteExecutionStatus):ExecutionResult{return{executionId,status:mapStatus(record.status),startedAt:record.startedAt??new Date().toISOString(),finishedAt:record.finishedAt??new Date().toISOString(),summary:record.summary,evidence:record.evidence,retryable:["FAILED","TIMED_OUT","LOST"].includes(record.status),...(record.baseHead?{baseHead:record.baseHead}:{}),...(record.candidateBranch?{candidateBranch:record.candidateBranch}:{}),...(record.candidateHead?{candidateHead:record.candidateHead}:{})};}
function mapStatus(status:string):ExecutionResult["status"]{if(status==="SUCCEEDED")return"SUCCEEDED";if(status==="CANCELLED")return"CANCELLED";if(status==="TIMED_OUT")return"TIMED_OUT";if(status==="LOST")return"WORKER_LOST";return"FAILED";}
export class RemoteVerificationExecutor implements VerificationExecutor{constructor(private configs:readonly RemoteWorkerConfig[],private workerIdForRepository:(repository:string)=>string|null,private fetcher:typeof fetch=fetch){}async execute(value:VerificationRequest):Promise<VerificationResult>{const config=this.config(value.repository),submitted=await request(config,"POST","/v1/verifications",JSON.stringify(value),this.fetcher);if(!submitted.ok)throw new RemoteTransportError(`worker rejected verification (${submitted.status})`);for(let attempts=0;attempts<360;attempts++){const result=await this.status(value.repository,value.verificationId);if(!result)throw new RemoteTransportError("worker verification not found");if(!["QUEUED","RUNNING"].includes(String(result.status)))return normalizeVerification(value.verificationId,result);await new Promise(resolve=>setTimeout(resolve,1000));}const now=new Date().toISOString();return{verificationId:value.verificationId,status:"ERROR",startedAt:now,finishedAt:now,checks:[],summary:"Remote verification status timeout",evidence:[]};}async status(repository:string,id:string):Promise<(VerificationResult&{status:VerificationResult["status"]|"QUEUED"|"RUNNING"})|null>{const response=await request(this.config(repository),"GET",`/v1/verifications/${encodeURIComponent(id)}`,"",this.fetcher);if(response.status===404)return null;if(!response.ok)throw new RemoteTransportError(`worker verification unavailable (${response.status})`);return response.json() as Promise<VerificationResult&{status:VerificationResult["status"]|"QUEUED"|"RUNNING"}>;}async cancel(repository:string,id:string){const response=await request(this.config(repository),"POST",`/v1/verifications/${encodeURIComponent(id)}/cancel`,"",this.fetcher);if(response.status===404)return null;if(!response.ok)throw new RemoteTransportError(`worker verification cancel failed (${response.status})`);return response.json();}private config(repository:string){const config=this.configs.find(value=>value.workerId===this.workerIdForRepository(repository));if(!config)throw new RemoteTransportError("remote verification worker is not configured");return config;}}
function normalizeVerification(id:string,value:any):VerificationResult{return{verificationId:id,status:value.status==="PASSED"?"PASSED":value.status==="FAILED"?"FAILED":value.status==="CANCELLED"?"CANCELLED":"ERROR",startedAt:value.startedAt??new Date().toISOString(),finishedAt:value.finishedAt??new Date().toISOString(),...(value.verifiedHead?{verifiedHead:String(value.verifiedHead)}:{}),checks:Array.isArray(value.checks)?value.checks:[],summary:String(value.summary??"Verification result unavailable").slice(0,500),evidence:Array.isArray(value.evidence)?value.evidence.slice(0,10).map((v:unknown)=>String(v).slice(0,500)):[]};}
