import test from "node:test";
import assert from "node:assert/strict";
import { decideVerification,extractAcceptanceCriteria,parseAcceptanceCriteria,verificationPlan,type VerificationCheckResult } from "../src/domain/verification.js";

test("V02 extracts only Acceptance Criteria checkbox lines within heading boundary",()=>{const body=`## Other\n- [ ] AC-99 [AUTO:test] wrong\n## Acceptance Criteria\ntext\n- [ ] AC-01 [AUTO:test] tests pass\n- [x] AC-02 [HUMAN] device\n## Notes\n- [ ] AC-03 [AUTO:build] wrong`;assert.deepEqual(extractAcceptanceCriteria(body),["AC-01 [AUTO:test] tests pass","AC-02 [HUMAN] device"]);});
test("V03/V04 checkbox state is discarded and AUTO/HUMAN parse deterministically",()=>{const parsed=parseAcceptanceCriteria(["AC-01 [AUTO:test,typecheck] gate","AC-02 [HUMAN] device"]);assert.equal(parsed.valid,true);if(parsed.valid){assert.deepEqual(parsed.criteria,[{id:"AC-01",kind:"AUTO",summary:"gate",automatedCheckIds:["test","typecheck"]},{id:"AC-02",kind:"HUMAN",summary:"device",automatedCheckIds:[]}]);}});
test("V05 missing empty malformed and duplicate Acceptance fail closed",()=>{for(const lines of [[],["bad"],["AC-01 [AUTO:test] one","AC-01 [HUMAN] duplicate"]])assert.equal(parseAcceptanceCriteria(lines).valid,false);});
test("V07 plan deduplicates checks and rejects unknown IDs",()=>{const parsed=parseAcceptanceCriteria(["AC-01 [AUTO:test,build] gate","AC-02 [AUTO:test] again"]);assert.deepEqual(verificationPlan(parsed,["test","build"]),{valid:true,criteria:parsed.valid?parsed.criteria:[],checkIds:["test","build"]});assert.equal(verificationPlan(parsed,["test"]).valid,false);});
const check=(checkId:string,status:VerificationCheckResult["status"]):VerificationCheckResult=>({checkId,status,exitCode:status==="PASSED"?0:1,startedAt:"a",finishedAt:"b",summary:status,evidence:["bounded"]});
test("V18-V21 decision requires check evidence independent of checkbox/prose/exit zero",()=>{const parsed=parseAcceptanceCriteria(["AC-01 [AUTO:test] gate"]);assert.equal(parsed.valid,true);if(!parsed.valid)return;assert.equal(decideVerification(parsed.criteria,[]).status,"FAILED");assert.equal(decideVerification(parsed.criteria,[check("test","FAILED")]).status,"FAILED");assert.equal(decideVerification(parsed.criteria,[check("test","PASSED")]).status,"PASSED");});
test("V20 AUTO pass plus HUMAN remains HUMAN_REQUIRED",()=>{const parsed=parseAcceptanceCriteria(["AC-01 [AUTO:test] gate","AC-02 [HUMAN] device"]);assert.equal(parsed.valid,true);if(parsed.valid)assert.equal(decideVerification(parsed.criteria,[check("test","PASSED")]).status,"HUMAN_REQUIRED");});
