import test from "node:test"; import assert from "node:assert/strict"; import type { IncomingMessage, ServerResponse } from "node:http";
import { mkdtemp, rm } from "node:fs/promises"; import { join } from "node:path"; import { tmpdir } from "node:os";
import { atomicWrite, DurableWorkItemRepository, type AtomicFileWriter } from "../src/infrastructure/durable-work-item-repository.js"; import { IssueSyncService } from "../src/application/issue-sync-service.js"; import { WorkTransitionService } from "../src/application/work-transition-service.js";
import { ExecutionService, evaluateExecutionGate, type ExecutionResult, type RepositoryExecutionTarget, type WorkerDescriptor } from "../src/application/execution.js"; import { FakeExecutor, FakeWorkerRegistry } from "../src/infrastructure/fake-execution.js";
import { createRequestHandler } from "../src/http-app.js"; import { parseProductsManifest, ProductService, type GitHubMetadataProvider } from "../src/products.js";
const repo="knys/repo", id=`github:${repo}:10`; const target:RepositoryExecutionTarget={repository:repo,workerId:"gtx",workspaceId:"safe-workspace",requiredCapabilities:["CODE_EDIT","GIT"],concurrency:"EXCLUSIVE_REPOSITORY"}; const worker:WorkerDescriptor={workerId:"gtx",status:"ONLINE",capabilities:["CODE_EDIT","GIT"],workspaceIds:["safe-workspace"],executorKinds:["CODEX"]};
const result=(status:ExecutionResult["status"]="SUCCEEDED",retryable=false):ExecutionResult=>({executionId:"exec-1",status,startedAt:"2026-09-03T00:00:00Z",finishedAt:"2026-09-03T00:01:00Z",summary:`${status} summary`,evidence:["bounded"],retryable});
async function setup(writer?:AtomicFileWriter){const directory=await mkdtemp(join(tmpdir(),"lcc-005-"));const path=join(directory,"state.json");let repository=await DurableWorkItemRepository.open(path);await new IssueSyncService({fetchOpenIssues:async()=>[{externalId:"10",title:"Gate",state:"open",labels:[],assignees:[],updatedAt:"2026-09-03T00:00:00Z",url:`https://github.com/${repo}/issues/10`}]},repository).sync(repo);await new WorkTransitionService(repository).transition(id,{type:"DEFINITION_COMPLETED",executor:"CODEX"});if(writer)repository=await DurableWorkItemRepository.open(path,writer);return{directory,path,repository,cleanup:()=>rm(directory,{recursive:true,force:true})};}
const service=(repository:DurableWorkItemRepository,executor:FakeExecutor,idFactory=()=>"exec-1")=>new ExecutionService(repository,[target],new FakeWorkerRegistry([worker]),executor,()=>Date.parse("2026-09-03T00:00:00Z"),idFactory);
test("T09 atomic lease; T07/T08 duplicate prevention",async t=>{const f=await setup();t.after(f.cleanup);let release!:()=>void;const gate=new Promise<void>(r=>release=r);const fake=new FakeExecutor(async req=>{await gate;return{...result(),executionId:req.executionId}});const first=service(f.repository,fake).execute(id);while((await f.repository.executionState()).leases.length===0)await Promise.resolve();const second=await service(f.repository,new FakeExecutor(),()=>"exec-2").execute(id);assert.equal(second.status,"ALREADY_RUNNING");release();await first;assert.equal(fake.requests.length,1);});
test("T10 lease failure and T12 no executor call",async t=>{const f=await setup(async()=>{throw new Error("disk full")});t.after(f.cleanup);const fake=new FakeExecutor();await assert.rejects(service(f.repository,fake).execute(id),/disk full/);assert.equal(fake.requests.length,0);assert.equal((await (await DurableWorkItemRepository.open(f.path)).findWorkItem(id))?.workState,"READY");});
test("T11 state-machine start and T13 structured request",async t=>{const f=await setup();t.after(f.cleanup);let during="";const fake=new FakeExecutor(async req=>{during=(await f.repository.findWorkItem(id))!.workState;assert.equal(req.workspaceId,"safe-workspace");assert.equal(req.actionKind,"EXECUTE");assert.ok(!("path" in req)||!(req as Record<string,unknown>).path);return result();});await service(f.repository,fake).execute(id);assert.equal(during,"RUNNING");});
for(const [name,status,retryable,expected] of [["T14 success","SUCCEEDED",false,"VERIFYING"],["T15 retryable","FAILED",true,"FAILED"],["T16 terminal","FAILED",false,"FAILED"],["T17 timeout","TIMED_OUT",true,"FAILED"],["T17 worker lost","WORKER_LOST",true,"WAITING_WORKER"]] as const)test(name,async t=>{const f=await setup();t.after(f.cleanup);await service(f.repository,new FakeExecutor(async req=>({...result(status,retryable),executionId:req.executionId}))).execute(id);assert.equal((await f.repository.findWorkItem(id))?.workState,expected);assert.notEqual((await f.repository.findWorkItem(id))?.workState,"DONE");});
test("T18 history; T19/T20 orphan lease restore",async t=>{const f=await setup();t.after(f.cleanup);let release!:()=>void;const gate=new Promise<void>(r=>release=r);const fake=new FakeExecutor(async req=>{await gate;return{...result(),executionId:req.executionId}});const running=service(f.repository,fake).execute(id);while((await f.repository.executionState()).leases.length===0)await Promise.resolve();const restored=await DurableWorkItemRepository.open(f.path);const snapshot=await restored.executionState();assert.equal(snapshot.leases[0]?.status,"ACTIVE");assert.equal(snapshot.records[0]?.resultStatus,"ACTIVE");assert.notEqual(evaluateExecutionGate((await restored.findWorkItem(id))!,target,worker,snapshot,false).status,"ELIGIBLE");assert.equal(fake.requests.length,1);release();await running;});
test("T21 completion persistence failure atomic",async t=>{const f=await setup();t.after(f.cleanup);let writes=0;const reopened=await DurableWorkItemRepository.open(f.path,async(path,data)=>{writes++;if(writes===2)throw new Error("record failed");await atomicWrite(path,data);});await assert.rejects(service(reopened,new FakeExecutor(async req=>({...result(),executionId:req.executionId}))).execute(id),/record failed/);const restored=await DurableWorkItemRepository.open(f.path);assert.equal((await restored.executionState()).leases[0]?.status,"ACTIVE");assert.equal((await restored.findWorkItem(id))?.workState,"RUNNING");});
test("T22 polling and execution do not lose state",async t=>{const f=await setup();t.after(f.cleanup);let release!:()=>void;const gate=new Promise<void>(r=>release=r);const running=service(f.repository,new FakeExecutor(async req=>{await gate;return{...result(),executionId:req.executionId}})).execute(id);while((await f.repository.executionState()).leases.length===0)await Promise.resolve();await new IssueSyncService({fetchOpenIssues:async()=>[{externalId:"10",title:"Source changed while executing",state:"open",labels:["updated"],assignees:[],updatedAt:"2026-09-03T00:02:00Z",url:`https://github.com/${repo}/issues/10`}]},f.repository).sync(repo);assert.equal((await f.repository.findWorkItem(id))?.workState,"RUNNING");assert.equal((await f.repository.findWorkItem(id))?.title,"Source changed while executing");assert.equal((await f.repository.executionState()).leases[0]?.status,"ACTIVE");release();await running;assert.equal((await f.repository.findWorkItem(id))?.workState,"VERIFYING");});
test("T23 execution API read-only and secret-free",async t=>{const f=await setup();t.after(f.cleanup);const manifest=parseProductsManifest({version:1,products:[{id:"x",name:"X",repository:repo,summary:"X",status:"READY",ball:"CODEX",nextAction:"X"}]});const provider:GitHubMetadataProvider={fetch:async()=>new Map()};const handler=createRequestHandler(new ProductService(manifest,provider),[],undefined,undefined,undefined,()=>f.repository.executionState());let body="";await new Promise<void>(resolve=>handler({method:"GET",url:"/api/executions"}as IncomingMessage,{writeHead:()=>undefined,end:(v:string)=>{body=v;resolve();}}as unknown as ServerResponse));assert.deepEqual(JSON.parse(body),{leases:[],records:[]});assert.doesNotMatch(body,/token|environment|stdout|stderr/i);});
test("T24 shutdown blocks and T25 settles inflight",async t=>{const f=await setup();t.after(f.cleanup);let release!:()=>void;let entered!:()=>void;const gate=new Promise<void>(r=>release=r);const started=new Promise<void>(r=>entered=r);const fake=new FakeExecutor(async req=>{entered();await gate;return{...result(),executionId:req.executionId}});const execution=service(f.repository,fake);const running=execution.execute(id);await started;let stopped=false;const stopping=execution.stop().then(()=>stopped=true);await Promise.resolve();assert.equal(stopped,false);assert.equal((await execution.execute(id)).status,"REJECTED");release();await running;await stopping;assert.equal(stopped,true);});
