import test from "node:test";
import assert from "node:assert/strict";
import { mkdtemp,rm } from "node:fs/promises";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { CommissionInbox } from "../src/application/commission-inbox.js";
import { DurableCommissionRunRegistrar,verifyCandidate,type FixedRunner } from "../src/application/commission-runs.js";
import { commissionLabel,GitHubCommissionScanner,type GitHubCommissionIssue } from "../src/application/github-commission.js";
import { DurableSelfCommissioningStore,SelfCommissioningOrchestrator,failureRevision,type CodexJob } from "../src/application/self-commissioning.js";

const issue:GitHubCommissionIssue={repository:"knys/luckountry-control-center",number:50,nodeId:"I_50",title:"Human Bridge Zero",body:"## Human Gate\nProduction visual approval",url:"https://github.com/knys/luckountry-control-center/issues/50",state:"open",updatedAt:"2026-09-04T00:00:00Z",author:"knys",labels:[commissionLabel]};
async function fixture(){const directory=await mkdtemp(join(tmpdir(),"human-bridge-zero-")),runs=join(directory,"runs.json"),inbox=new CommissionInbox(join(directory,"inbox.json"),new DurableCommissionRunRegistrar(runs));return{directory,runs,inbox,cleanup:()=>rm(directory,{recursive:true,force:true})}}

test("AC-01/02 GitHub label creates exactly one durable Commission Run with verified revision",async t=>{const f=await fixture();t.after(f.cleanup);const scanner=new GitHubCommissionScanner(f.inbox,{list:async()=>[issue]},[issue.repository]);assert.equal((await scanner.scan()).length,1);assert.equal((await scanner.scan()).length,0);const items=await f.inbox.list();assert.equal(items.length,1);assert.equal(items[0]?.commissionState,"COMMISSIONED");assert.equal(items[0]?.commissionLabel,commissionLabel);assert.match(items[0]?.sourceRevision??"",/^[0-9a-f]{32}$/);const run=await(await DurableSelfCommissioningStore.open(f.runs)).stored(items[0]!.runId!);assert.equal(run?.run.status,"QUEUED");assert.equal((run?.steps[0] as {job:CodexJob}).job.policy.allowMerge,true);assert.match(items[0]?.humanGate??"",/Production visual approval/)});

test("GitHub Commission fails closed on identity, label, state and repository mismatch",async t=>{const f=await fixture();t.after(f.cleanup);for(const broken of [{...issue,labels:[]},{...issue,state:"closed" as const},{...issue,repository:"knys/other"},{...issue,url:"https://example.test/issues/50"}]){const scanner=new GitHubCommissionScanner(f.inbox,{list:async()=>[broken]},[issue.repository]);await assert.rejects(scanner.scan(),/invalid|allowlisted/)}});

test("AC-08/09 BLOCKED recovery is revision-bound, durable, bounded and never resets retries",async t=>{const f=await fixture();t.after(f.cleanup);const store=await DurableSelfCommissioningStore.open(f.runs),runner=new SelfCommissioningOrchestrator(store,{tx:async()=>({status:"BLOCKED",summary:"legacy CLI",evidence:[]}),gtx:async()=>({status:"BLOCKED",summary:"no",evidence:[]}),codex:async()=>({status:"BLOCKED",summary:"legacy CLI",evidence:[],blocker:"legacy CLI"})}),job:CodexJob={objective:"Issue 47",repository:"knys/luckountry-control-center",workspaceId:"lcc",policy:{allowCommit:true,allowPush:false,allowMerge:false,allowDeploy:false}};await runner.create({runId:"recover-47",objective:"Issue 47",steps:[{stepId:"codex",kind:"CODEX_JOB",job}],retryLimit:1});await runner.tick("recover-47");const blocked=(await store.get("recover-47"))!,revision=failureRevision(blocked);await assert.rejects(store.recover("recover-47",{actor:"knys",reason:"wrong",expectedFailure:"bad"}),/revision/);const recovered=await store.recover("recover-47",{actor:"knys",reason:"CLI compatibility fixed",expectedFailure:revision});assert.equal(recovered.status,"QUEUED");assert.equal(recovered.retryBudget.consumed,0);assert.equal(recovered.recoveryBudget.consumed,1);const restored=await DurableSelfCommissioningStore.open(f.runs);assert.equal((await restored.get("recover-47"))?.recoveryBudget.consumed,1)});

test("AC-10/11 future Human text does not block dispatch and NG durably queues repair",async t=>{const f=await fixture();t.after(f.cleanup);const store=await DurableSelfCommissioningStore.open(f.runs),job:CodexJob={objective:"visual",repository:"knys/TOBIE",workspaceId:"tobie",humanGate:"cute and well paced",policy:{allowCommit:true,allowPush:false,allowMerge:false,allowDeploy:false}},runner=new SelfCommissioningOrchestrator(store,{tx:async()=>({status:"BLOCKED",summary:"no",evidence:[]}),gtx:async()=>({status:"BLOCKED",summary:"no",evidence:[]}),codex:async()=>({status:"WAITING_HUMAN",summary:"automation complete",evidence:[],humanGate:job.humanGate!})});await runner.create({runId:"human",objective:"visual",steps:[{stepId:"codex",kind:"CODEX_JOB",job}],retryLimit:1});assert.equal((await runner.tick("human")).status,"WAITING_HUMAN");const repaired=await store.humanDecision("human",{actor:"knys",decision:"NG",reason:"tempo too slow"});assert.equal(repaired.status,"QUEUED");assert.equal(repaired.queuedActor,"CODEX");assert.match(JSON.stringify(repaired.history),/tempo too slow/)});

test("AC-03/04/15 candidate verifier rejects dirty or secret-bearing output and passes fixed evidence",async()=>{const job:CodexJob={objective:"Issue",repository:"knys/luckountry-control-center",workspaceId:"lcc",issueNumber:50,sourceRevision:"revision",policy:{allowCommit:true,allowPush:true,allowMerge:true,allowDeploy:true}};let dirty=true,secret=false;const run:FixedRunner=async(_file,args)=>{const key=args.join(" ");if(key==="status --porcelain")return{code:0,stdout:dirty?" M src/x.ts":"",stderr:""};if(key==="rev-parse HEAD")return{code:0,stdout:"bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb\n",stderr:""};if(key.startsWith("merge-base"))return{code:0,stdout:"",stderr:""};if(key.startsWith("diff --name-only"))return{code:0,stdout:"src/x.ts\n",stderr:""};if(key.startsWith("diff --no-ext-diff"))return{code:0,stdout:secret?"token=abcdefghijklmnop":"safe",stderr:""};return{code:0,stdout:"",stderr:""}};const checks:[[string,string[]]]=[["/usr/bin/npm",["test"]]];assert.equal((await verifyCandidate(job,".","aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",/^src\//,checks,run)).status,"BLOCKED");dirty=false;secret=true;assert.equal((await verifyCandidate(job,".","aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",/^src\//,checks,run)).status,"BLOCKED");secret=false;const passed=await verifyCandidate(job,".","aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",/^src\//,checks,run);assert.equal(passed.status,"SUCCEEDED");assert.match(passed.evidence.join(" "),/candidate=.*npm test: PASS/)});
