import test from"node:test";import assert from"node:assert/strict";import{mkdtemp,rm}from"node:fs/promises";import{join}from"node:path";import{tmpdir}from"node:os";import{PersistentCodexDispatcher}from"../src/application/persistent-codex-dispatcher.js";import{DurableSelfCommissioningStore,SelfCommissioningOrchestrator,type CodexJob,type CommissioningExecutors,type SelfCommissioningStep}from"../src/application/self-commissioning.js";
const policy={allowCommit:true as const,allowPush:false as const,allowMerge:false as const,allowDeploy:false as const},job:CodexJob={objective:"Complete one bounded job",repository:"knys/luckountry-control-center",workspaceId:"lcc",policy};
const steps:SelfCommissioningStep[]=[{stepId:"codex",kind:"CODEX_JOB",job},{stepId:"supervisor-1",kind:"SUPERVISOR_OPERATION",job:{...job,operation:"INSPECT_CURRENT_STATE"}},{stepId:"supervisor-2",kind:"SUPERVISOR_OPERATION",job:{...job,operation:"POST_ACCEPTANCE_OBSERVATION"}}];
async function setup(executors:CommissioningExecutors){const dir=await mkdtemp(join(tmpdir(),"lcc-dispatcher-")),path=join(dir,"runs.json"),store=await DurableSelfCommissioningStore.open(path),orchestrator=new SelfCommissioningOrchestrator(store,executors),reports:string[]=[];return{dir,path,store,orchestrator,reports,dispatcher:new PersistentCodexDispatcher(store,orchestrator,{report:async run=>{reports.push(run.status+":"+run.currentStep)}}),cleanup:()=>rm(dir,{recursive:true,force:true})}}
const unused=async()=>({status:"BLOCKED"as const,summary:"unexpected",evidence:[],blocker:"unexpected"});

test("L010 AC-02/03/07/10 one start advances CODEX_JOB and two Supervisor steps without duplicate or Human transport",async t=>{const calls:{id:string;operation:string|undefined}[]=[],f=await setup({tx:unused,gtx:unused,codex:async(value,id)=>{calls.push({id,operation:value.operation});return{status:"SUCCEEDED",summary:`ok token=secret ${"x".repeat(1000)}`,evidence:["/home/operator/private token=secret"]}}});t.after(f.cleanup);await f.orchestrator.create({runId:"three",objective:"three consecutive steps",steps,retryLimit:1});f.dispatcher.start("three");f.dispatcher.start("three");await f.dispatcher.drain();const run=await f.store.get("three");assert.equal(run?.status,"SUCCEEDED");assert.deepEqual(run?.completedSteps,["codex","supervisor-1","supervisor-2"]);assert.equal(calls.length,3);assert.equal(new Set(calls.map(value=>value.id)).size,3);assert.equal(f.reports.length,3);assert.doesNotMatch(JSON.stringify(run),/secret|\/home\/operator/)});

test("L010 AC-01/04 restart resumes durable retry without repeating completed step or restoring budget",async t=>{const gate=new Promise<void>(()=>undefined),calls:string[]=[],f=await setup({tx:unused,gtx:unused,codex:async(value)=>{calls.push(value.operation??"CODEX_JOB");if(value.operation==="INSPECT_CURRENT_STATE")await gate;return{status:"SUCCEEDED",summary:"ok",evidence:[]}}});t.after(f.cleanup);await f.orchestrator.create({runId:"restart",objective:"restart",steps,retryLimit:1});f.dispatcher.start("restart");while((await f.store.get("restart"))?.currentStep!=="supervisor-1"||!(await f.store.get("restart"))?.activeActor)await new Promise(resolve=>setImmediate(resolve));const reopened=await DurableSelfCommissioningStore.open(f.path),restored=await reopened.get("restart");assert.equal(restored?.status,"QUEUED");assert.deepEqual(restored?.completedSteps,["codex"]);assert.equal(restored?.retryBudget.consumed,0);const resumedCalls:string[]=[],resumedOrchestrator=new SelfCommissioningOrchestrator(reopened,{tx:unused,gtx:unused,codex:async value=>{resumedCalls.push(value.operation??"CODEX_JOB");return{status:"SUCCEEDED",summary:"resumed",evidence:[]}}}),resumed=new PersistentCodexDispatcher(reopened,resumedOrchestrator,{report:async()=>undefined});await resumed.resume();await resumed.drain();assert.equal((await reopened.get("restart"))?.status,"SUCCEEDED");assert.deepEqual(resumedCalls,["INSPECT_CURRENT_STATE","POST_ACCEPTANCE_OBSERVATION"]);assert.equal(calls.filter(value=>value==="CODEX_JOB").length,1)});

test("L010 AC-04/05/06 bounded retry, kill switch, BLOCKED and WAITING_HUMAN stop exactly",async t=>{let attempt=0;const f=await setup({tx:unused,gtx:unused,codex:async()=>++attempt===1?{status:"FAILED",summary:"temporary",evidence:[],retryable:true}:{status:"WAITING_HUMAN",summary:"promotion",evidence:[],humanGate:"promotion approval only"}});t.after(f.cleanup);await f.orchestrator.create({runId:"bounded",objective:"bounded",steps:[steps[0]!],retryLimit:1});f.dispatcher.start("bounded");await f.dispatcher.drain();const waiting=await f.store.get("bounded");assert.equal(attempt,2);assert.equal(waiting?.retryBudget.consumed,1);assert.equal(waiting?.status,"WAITING_HUMAN");assert.equal(waiting?.humanGate,"promotion approval only");await f.orchestrator.create({runId:"killed",objective:"killed",steps:[steps[0]!],retryLimit:1});await f.orchestrator.setKillSwitch(false);f.dispatcher.start("killed");await f.dispatcher.drain();const killed=await f.store.get("killed");assert.equal(killed?.status,"BLOCKED");assert.match(killed?.blocker??"",/kill switch/);assert.equal(attempt,2)});

test("L010 AC-08 arbitrary command cwd environment and policy escalation are rejected",async t=>{const f=await setup({tx:unused,gtx:unused,codex:unused});t.after(f.cleanup);for(const extra of[{command:"bash"},{cwd:"/tmp"},{environment:{SECRET:"x"}}])await assert.rejects(f.orchestrator.create({runId:"unsafe"+Object.keys(extra)[0],objective:"unsafe",steps:[{stepId:"unsafe",kind:"CODEX_JOB",job:{...job,...extra} as CodexJob}],retryLimit:0}),/unsafe step/);await assert.rejects(f.orchestrator.create({runId:"push",objective:"unsafe",steps:[{stepId:"unsafe",kind:"CODEX_JOB",job:{...job,policy:{...policy,allowPush:true}} as unknown as CodexJob}],retryLimit:0}),/unsafe step/)});
