import test from "node:test";
import assert from "node:assert/strict";
import { definitionReady, deterministicCandidateBranch, matchesPilotScope, parsePilotControl,type PilotScope } from "../src/domain/pilot.js";
import { PilotReadinessService,pilotExecutionCandidates, pilotVerificationCandidates, readinessReason } from "../src/application/pilot-control.js";
import type { WorkItem } from "../src/domain/work-item.js";

const scope:PilotScope={version:1,cycleId:"pilot-1",repository:"knys/repo",externalId:"16",workerId:"gtx1060",workspaceId:"product",verificationProfileId:"node",baseBranch:"main",requiredLabels:["lcc:pilot","lcc:ready"],expiresAt:"2026-09-04T03:00:00.000Z",maxExecutionAttempts:1,maxVerificationRuns:1};

test("AC-01 automation defaults disabled",()=>assert.equal(parsePilotControl({}).enabled,false));
test("AC-02 valid pilot requires exact scope and both flags",()=>{
  const control=parsePilotControl({WORK_AUTOMATION_MODE:"pilot",WORK_EXECUTION_ENABLED:"true",WORK_VERIFICATION_ENABLED:"true",WORK_PILOT_SCOPE_JSON:JSON.stringify(scope)},Date.parse("2026-09-03T00:00:00.000Z"));
  assert.equal(control.enabled,true);
  assert.deepEqual(control.scope,scope);
});
const item:WorkItem={id:"w16",source:{provider:"github",repository:"knys/repo",externalId:"16"},title:"pilot",sourceState:"open",labels:["lcc:pilot","lcc:ready"],assignees:[],sourceUrl:"https://github.com/knys/repo/issues/16",workState:"DEFINED",ballHolder:"HUMAN",nextAction:{kind:"DEFINE",summary:"define",ballHolder:"HUMAN",aiExecutable:false,requiredCapabilities:[]},blocker:null,acceptanceCriteria:["AC-01 [AUTO:test] passes"],definitionReady:true,evidence:[],sourceUpdatedAt:"2026-09-03T00:00:00Z",lastSyncedAt:"2026-09-03T00:00:00Z",transitionReason:"new"};
const enabled=parsePilotControl({WORK_AUTOMATION_MODE:"pilot",WORK_EXECUTION_ENABLED:"true",WORK_VERIFICATION_ENABLED:"true",WORK_PILOT_SCOPE_JSON:JSON.stringify(scope)},Date.parse("2026-09-03T00:00:00Z"));
test("AC-03 malformed multiple expired and reserved production fail closed",()=>{for(const value of["[]","{}",JSON.stringify({...scope,expiresAt:"2026-09-02T00:00:00Z"})])assert.equal(parsePilotControl({WORK_AUTOMATION_MODE:"pilot",WORK_EXECUTION_ENABLED:"true",WORK_VERIFICATION_ENABLED:"true",WORK_PILOT_SCOPE_JSON:value},Date.parse("2026-09-03T00:00:00Z")).enabled,false);assert.equal(parsePilotControl({WORK_AUTOMATION_MODE:"production",WORK_EXECUTION_ENABLED:"true",WORK_VERIFICATION_ENABLED:"true",WORK_PILOT_SCOPE_JSON:JSON.stringify(scope)}).enabled,false);});
test("AC-04 exact repository and external ID match",()=>{assert.equal(matchesPilotScope(item,scope),true);assert.equal(matchesPilotScope({...item,source:{...item.source,externalId:"17"}},scope),false);});
test("AC-05/06/07 readiness is deterministic and fail closed",()=>{assert.equal(readinessReason(item,scope,{workerReady:true,workspaceReady:true,profileReady:true},Date.parse("2026-09-03T00:00:00Z")),null);assert.match(readinessReason({...item,labels:["lcc:pilot"]},scope,{workerReady:true,workspaceReady:true,profileReady:true})??"",/labels/);assert.match(readinessReason({...item,definitionReady:false},scope,{workerReady:true,workspaceReady:true,profileReady:true})??"",/Definition/);assert.match(readinessReason({...item,acceptanceCriteria:["invalid"]},scope,{workerReady:true,workspaceReady:true,profileReady:true})??"",/Acceptance/);});
test("AC-06 exact Definition markers and Coding Ready YES",()=>{const body="## Problem\np\n## Outcome\no\n## Scope\ns\n## Failure Behavior\nf\n## Verification\nv\n## Execution Environment\ne\nCoding Ready: YES";assert.equal(definitionReady(body),true);assert.equal(definitionReady(body.replace("## Scope","## Maybe")),false);assert.equal(definitionReady(body.replace("YES","NO")),false);});
test("AC-09/10 shared scope leaves unrelated READY and VERIFYING untouched",()=>{const cycle={cycleId:"pilot-1",scopeFingerprint:"abc",workItemId:item.id,status:"ARMED" as const,baseHead:null,candidateBranch:null,candidateHead:null,executionAttempts:0,verificationRuns:0,startedAt:"x",updatedAt:"x",reason:"armed"},ready={...item,workState:"READY" as const,ballHolder:"CODEX" as const},other={...ready,id:"other",source:{...ready.source,externalId:"99"}};assert.deepEqual(pilotExecutionCandidates([other,ready],enabled,cycle),[item.id]);assert.deepEqual(pilotVerificationCandidates([{...other,workState:"VERIFYING"},{...ready,workState:"VERIFYING"}],enabled,{...cycle,status:"VERIFYING"}),[item.id]);});
test("AC-11/12 budgets and kill switches prevent dispatch",()=>{const cycle={cycleId:"pilot-1",scopeFingerprint:"abc",workItemId:item.id,status:"ARMED" as const,baseHead:null,candidateBranch:null,candidateHead:null,executionAttempts:1,verificationRuns:0,startedAt:"x",updatedAt:"x",reason:"armed"};assert.deepEqual(pilotExecutionCandidates([{...item,workState:"READY"}],enabled,cycle),[]);assert.deepEqual(pilotExecutionCandidates([{...item,workState:"READY"}],parsePilotControl({}),{...cycle,executionAttempts:0}),[]);});
test("AC-15 deterministic candidate branch is bounded and non-base",()=>{assert.equal(deterministicCandidateBranch("16","abcdef123456"),"lcc/pilot/16-abcdef12");assert.throws(()=>deterministicCandidateBranch("../16","abcdef"),/unsafe/);});
test("AC-08 valid scoped definition becomes READY/CODEX without LLM judgment",async()=>{let current=structuredClone(item);const cycles:any[]=[];const service=new PilotReadinessService({list:async()=>[current],findWorkItem:async()=>current,transitionExecutionState:async(_id,update)=>current=update(current)},{pilotCycles:async()=>structuredClone(cycles),savePilotCycle:async cycle=>{cycles.push(structuredClone(cycle));}},enabled,{workerReady:true,workspaceReady:true,profileReady:true},()=>Date.parse("2026-09-03T00:00:00Z"));const result=await service.evaluate();assert.equal(result.ready,true);assert.equal(current.workState,"READY");assert.equal(current.ballHolder,"CODEX");assert.equal(current.nextAction.aiExecutable,true);assert.equal(cycles[0]?.workItemId,item.id);});
