import test from "node:test";
import assert from "node:assert/strict";
import { buildPrompt, executeCodex } from "../src/worker/codex-cli.js";
import { CONTROLLER_EXECUTION_TIMEOUT_MS, RemoteCodexExecutor, type RemotePollingPolicy } from "../src/infrastructure/remote-execution.js";
import { WORKER_EXECUTION_TIMEOUT_MS,WorkerExecutionAgent } from "../src/worker/execution-agent.js";
import { PilotBranchPostconditionError,preparePilotBranch,validatePilotBranch } from "../src/worker/pilot-branch.js";
import type { ExecutionRequest } from "../src/application/execution.js";
import { parseWorkspaceManifest,type CommandRunner } from "../src/worker/workspace.js";
import { WorkerExecutionStore } from "../src/worker/execution-store.js";
import { mkdtemp,rm } from "node:fs/promises";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { parsePilotControl,scopeFingerprint,type PilotCycle,type PilotScope } from "../src/domain/pilot.js";
import { assessPilotRemediation,pilotExecutionCandidates } from "../src/application/pilot-control.js";
import type { WorkItem } from "../src/domain/work-item.js";
import { DurablePilotCycleRepository } from "../src/infrastructure/durable-pilot-cycle-repository.js";

const sha="a".repeat(40),candidate="b".repeat(40);
const request:ExecutionRequest={executionId:"attempt-2",workItemId:"github:knys/TOBIE:215",repository:"knys/TOBIE",workspaceId:"tobie-pilot",actionKind:"EXECUTE",summary:"Implement private Issue 215",acceptanceCriteria:["AC-01 [AUTO:test] behavior"],requiredCapabilities:["CODE_EDIT"],sourceUrl:"https://github.com/knys/TOBIE/issues/215",pilot:{cycleId:"pilot-1",externalId:"215",baseBranch:"main",candidateBranch:"lcc/pilot/215-attempt-"}};
const workspace={workspaceId:"tobie-pilot",repository:"knys/TOBIE",path:"/configured",capabilities:[],pilotBaseBranch:"main",promotionDisabled:true};
function git(head=sha,status=""):CommandRunner{return async(_executable,args)=>({code:args[0]==="merge-base"?0:0,stdout:args[0]==="branch"?`${request.pilot!.candidateBranch}\n`:args.join(" ")==="rev-parse HEAD"?`${head}\n`:args[0]==="status"?status:`${sha}\n`,stderr:""});}

test("A201-A205 Pilot success requires a clean candidate commit and preserves diagnostics",async()=>{const prepared={baseHead:sha,candidateBranch:request.pilot!.candidateBranch};try{await validatePilotBranch({...request.pilot!,executionId:request.executionId},prepared,workspace,git());assert.fail("expected unchanged HEAD rejection");}catch(error){assert.ok(error instanceof PilotBranchPostconditionError);assert.match(error.message,/did not advance/);assert.match(error.evidence.join("\n"),new RegExp(`pilot\\.observedCandidateHead=${sha}`));assert.match(error.evidence.join("\n"),/pilot\.gitStatus=clean/);}await assert.rejects(validatePilotBranch({...request.pilot!,executionId:request.executionId},prepared,workspace,git(candidate," M file.ts\n")),/not clean/);assert.deepEqual(await validatePilotBranch({...request.pilot!,executionId:request.executionId},prepared,workspace,git(candidate)),{...prepared,candidateHead:candidate});});

test("A206-A209 prompt carries Issue contract and final JSONL message separately",async()=>{const prompt=buildPrompt(request);for(const phrase of["authenticated GitHub","Implement the Issue","run its required verification","commit the completed implementation","Do not push","Do not create a PR","Do not merge","AUTO:test"])assert.match(prompt,new RegExp(phrase,"i"));const stdout=[JSON.stringify({type:"item.completed",item:{type:"agent_message",text:"old"}}),JSON.stringify({type:"item.completed",item:{type:"agent_message",text:"final outcome"}})].join("\n"),result=await executeCodex(request,workspace,{version:"1",codexReady:true,reason:null,args:["exec","--json","--color","never","--approve-for-me","-"],command:{executable:"/tmp/codex",prefixArgs:[]}},async()=>({code:0,stdout,stderr:""}));assert.equal(result.status,"SUCCEEDED");assert.equal(result.finalAgentMessage,"final outcome");});

test("A202/A203 Worker state retains final message and git diagnostics after postcondition failure",async t=>{const directory=await mkdtemp(join(tmpdir(),"lcc-attempt2-"));t.after(()=>rm(directory,{recursive:true,force:true}));const store=await WorkerExecutionStore.open(join(directory,"executions.json")),manifest=parseWorkspaceManifest({version:1,workspaces:[{workspaceId:"tobie-pilot",repository:"knys/TOBIE",path:directory,capabilities:["CODE_EDIT"],pilotBaseBranch:"main",promotionDisabled:true}]});let created=false;const run:CommandRunner=async(executable,args)=>{if(executable!=="git")return{code:0,stdout:JSON.stringify({type:"item.completed",item:{type:"agent_message",text:"No changes were necessary token=hidden"}}),stderr:""};const command=args.join(" ");if(command==="rev-parse --show-toplevel")return{code:0,stdout:directory,stderr:""};if(command==="remote get-url origin")return{code:0,stdout:"https://github.com/knys/TOBIE.git",stderr:""};if(command==="remote get-url --push origin")return{code:0,stdout:"DISABLED",stderr:""};if(command.startsWith("show-ref"))return{code:1,stdout:"",stderr:""};if(command.startsWith("switch")){created=true;return{code:0,stdout:"",stderr:""};}if(command==="branch --show-current")return{code:0,stdout:created?request.pilot!.candidateBranch:"main",stderr:""};if(command==="status --porcelain")return{code:0,stdout:"",stderr:""};return{code:0,stdout:sha,stderr:""};};const descriptor={workerId:"gtx",status:"ONLINE" as const,capabilities:["CODE_EDIT"],workspaceIds:["tobie-pilot"],executorKinds:["CODEX"]},agent=new WorkerExecutionAgent(descriptor,manifest,store,{version:"1",codexReady:true,reason:null,args:["exec","--json","--color","never","--approve-for-me","-"],command:{executable:"/tmp/codex",prefixArgs:[]}},run);await agent.submit(request);let record=await store.get(request.executionId);for(let index=0;index<20&&record?.status==="RUNNING";index++){await new Promise(resolve=>setImmediate(resolve));record=await store.get(request.executionId);}assert.equal(record?.status,"FAILED");assert.equal(record?.codexStatus,"SUCCEEDED");assert.match(record?.finalAgentMessage??"",/No changes were necessary/);assert.doesNotMatch(record?.finalAgentMessage??"",/hidden/);assert.match(record?.evidence.join("\n")??"",/candidate HEAD did not advance|observedCandidateHead/);});

test("A215-A218 remediation binds exact latest failure and grants one bounded third dispatch",()=>{const scope:PilotScope={version:1,cycleId:"pilot-1",repository:"knys/TOBIE",externalId:"215",workerId:"gtx",workspaceId:"tobie-pilot",verificationProfileId:"node",baseBranch:"main",requiredLabels:["lcc:pilot","lcc:ready"],expiresAt:"2026-09-04T00:00:00Z",maxExecutionAttempts:1,maxVerificationRuns:1},control=parsePilotControl({WORK_AUTOMATION_MODE:"pilot",WORK_EXECUTION_ENABLED:"true",WORK_VERIFICATION_ENABLED:"true",WORK_PILOT_SCOPE_JSON:JSON.stringify(scope),WORK_PILOT_REMEDIATION_ID:"pilot-1:attempt-2"},Date.parse("2026-09-03T00:00:00Z")),item:WorkItem={id:"github:knys/TOBIE:215",source:{provider:"github",repository:"knys/TOBIE",externalId:"215"},title:"issue",sourceState:"open",labels:["lcc:pilot","lcc:ready"],assignees:[],sourceUrl:"https://github.com/knys/TOBIE/issues/215",workState:"FAILED",ballHolder:"LCC",nextAction:{kind:"INVESTIGATE",summary:"failed",ballHolder:"LCC",aiExecutable:true,requiredCapabilities:["DIAGNOSTICS"]},blocker:null,acceptanceCriteria:["AC-01 [AUTO:test] pass"],definitionReady:true,evidence:["attempt1","attempt2"],sourceUpdatedAt:"x",lastSyncedAt:"x",transitionReason:"RETRYABLE_FAILURE accepted from RUNNING"},cycle:PilotCycle={cycleId:scope.cycleId,scopeFingerprint:scopeFingerprint(scope),workItemId:item.id,status:"FAILED",baseHead:null,candidateBranch:null,candidateHead:null,executionAttempts:2,verificationRuns:0,startedAt:"x",updatedAt:"x",reason:"failed",recoveryRequestId:"pilot-1",recoveryConsumedAt:"x",recoveryCount:1,previousFailureReason:"attempt1",remediationCount:0},execution={leases:[],records:[{executionId:"attempt-1",workItemId:item.id,attempt:1,workerId:"gtx",requestedAt:"x",startedAt:"x",finishedAt:"x",resultStatus:"FAILED" as const,summary:"preflight",evidence:[]},{executionId:"attempt-2",workItemId:item.id,attempt:2,workerId:"gtx",requestedAt:"x",startedAt:"x",finishedAt:"x",resultStatus:"TIMED_OUT" as const,summary:"old false timeout",evidence:[]}]},context={workerReady:true,workspaceReady:true,profileReady:true};assert.equal(assessPilotRemediation(control,scope,item,cycle,execution,context,Date.parse("2026-09-03T00:00:00Z")).eligible,true);assert.equal(assessPilotRemediation({...control,remediationId:"pilot-1:attempt-1"},scope,item,cycle,execution,context,Date.parse("2026-09-03T00:00:00Z")).eligible,false);const retrying={...item,workState:"RETRYING" as const,ballHolder:"LCC" as const,nextAction:{kind:"RETRY" as const,summary:"retry",ballHolder:"LCC" as const,aiExecutable:true,requiredCapabilities:["CODE_EDIT"]}};assert.deepEqual(pilotExecutionCandidates([retrying],control,{...cycle,status:"ARMED",remediationCount:1}),[item.id]);assert.deepEqual(pilotExecutionCandidates([retrying],control,{...cycle,status:"ARMED",remediationCount:1,executionAttempts:3}),[]);assert.deepEqual(item.evidence,["attempt1","attempt2"]);});

test("A215/A217 v2 migration preserves Recovery and makes remediation restart-idempotent",async t=>{const directory=await mkdtemp(join(tmpdir(),"lcc-remediation-"));t.after(()=>rm(directory,{recursive:true,force:true}));const path=join(directory,"cycles.json"),old:PilotCycle={cycleId:"pilot-1",scopeFingerprint:"fingerprint",workItemId:"work",status:"FAILED",baseHead:null,candidateBranch:null,candidateHead:null,executionAttempts:2,verificationRuns:0,startedAt:"x",updatedAt:"x",reason:"attempt2",recoveryRequestId:"pilot-1",recoveryConsumedAt:"x",recoveryCount:1,previousFailureReason:"attempt1"};await (await import("node:fs/promises")).writeFile(path,JSON.stringify({version:2,cycles:[old]}));const repository=await DurablePilotCycleRepository.open(path),[migrated]=await repository.pilotCycles();assert.equal(migrated?.recoveryCount,1);assert.equal(migrated?.remediationCount,0);const consumed={...migrated!,status:"ARMED" as const,remediationRequestId:"pilot-1:attempt-2",remediationConsumedAt:"y",remediationCount:1,previousRemediationFailureReason:"attempt2"};await repository.savePilotCycle(consumed);const [restored]=await(await DurablePilotCycleRepository.open(path)).pilotCycles();assert.equal(restored?.remediationCount,1);assert.equal(restored?.recoveryCount,1);await assert.rejects(repository.savePilotCycle({...restored!,remediationCount:0}),/history mutation/);});

test("A210 clean unchanged prior candidate is preserved and base is restored before remediation",async()=>{const calls:string[]=[],prior=`lcc/pilot/215-1b9ccd92`,run:CommandRunner=async(_executable,args)=>{const command=args.join(" ");calls.push(command);if(command==="branch --show-current")return{code:0,stdout:prior,stderr:""};if(command.startsWith("rev-parse"))return{code:0,stdout:sha,stderr:""};if(command==="remote get-url --push origin")return{code:0,stdout:"DISABLED",stderr:""};if(command.startsWith("show-ref"))return{code:1,stdout:"",stderr:""};return{code:0,stdout:"",stderr:""};};await preparePilotBranch({...request.pilot!,executionId:request.executionId},workspace,run);assert.ok(calls.includes("switch main"));assert.ok(calls.includes(`switch -c ${request.pilot!.candidateBranch} ${sha}`));assert.equal(calls.some(value=>/branch -D|reset|clean/.test(value)),false);});

const credentials={keyId:"lcc",secret:"test-secret"};
function policy():{value:RemotePollingPolicy;time:()=>number}{let now=0;return{time:()=>now,value:{pollIntervalMs:1,controllerTimeoutMs:2,terminalGraceMs:1,now:()=>now,sleep:async milliseconds=>{now+=milliseconds;}}};}
test("A211 terminal status at Controller boundary wins over local timeout",async()=>{const clock=policy();let gets=0,cancels=0;const fetcher:typeof fetch=async(_input,init)=>{if(init?.method==="POST"){if(String(_input).endsWith("/cancel"))cancels++;return new Response("{}",{status:202});}gets++;return new Response(JSON.stringify({status:gets>=3?"FAILED":"RUNNING",startedAt:"a",finishedAt:gets>=3?"b":null,summary:gets>=3?"worker terminal":"running",evidence:["diagnostic"]}),{status:200});};const result=await new RemoteCodexExecutor([{workerId:"gtx",baseUrl:"http://worker/",credentials}],()=>"gtx",fetcher,clock.value).execute(request);assert.equal(result.status,"FAILED");assert.equal(result.summary,"worker terminal");assert.equal(cancels,0);});

test("A212-A214 Controller timeout is bounded, execution-scoped, and race-safe",async()=>{assert.ok(CONTROLLER_EXECUTION_TIMEOUT_MS>WORKER_EXECUTION_TIMEOUT_MS);assert.ok(CONTROLLER_EXECUTION_TIMEOUT_MS<=32*60_000);for(const terminalOnCancel of[false,true]){const clock=policy();let cancelPath="";const fetcher:typeof fetch=async(input,init)=>{const path=new URL(String(input)).pathname;if(init?.method==="POST"&&path.endsWith("/cancel")){cancelPath=path;return new Response(JSON.stringify({status:terminalOnCancel?"FAILED":"RUNNING",startedAt:"a",finishedAt:terminalOnCancel?"b":null,summary:terminalOnCancel?"terminal won race":"running",evidence:[]}),{status:200});}if(init?.method==="POST")return new Response("{}",{status:202});return new Response(JSON.stringify({status:"RUNNING",startedAt:"a",finishedAt:null,summary:"running",evidence:[]}),{status:200});};const result=await new RemoteCodexExecutor([{workerId:"gtx",baseUrl:"http://worker/",credentials}],()=>"gtx",fetcher,clock.value).execute(request);assert.equal(cancelPath,"/v1/executions/attempt-2/cancel");assert.equal(result.status,terminalOnCancel?"FAILED":"TIMED_OUT");assert.ok(clock.time()<=4);}});
