import test from"node:test";
import assert from"node:assert/strict";
import{mkdtemp,rm}from"node:fs/promises";
import{join}from"node:path";
import{tmpdir}from"node:os";
import type{CommissionCandidate,CommissionRunRegistrar}from"../src/application/commission-inbox.js";
import{PortfolioSupervisor,classifyPortfolioFailure,portfolioFailureTypes,portfolioPolicy}from"../src/application/portfolio-supervisor.js";
import{DurableSelfCommissioningStore,SelfCommissioningOrchestrator,type CodexJob}from"../src/application/self-commissioning.js";

const job:CodexJob={objective:"bounded",repository:"knys/luckountry-control-center",workspaceId:"lcc",issueNumber:69,sourceRevision:"a".repeat(32),policy:{allowCommit:true,allowPush:false,allowMerge:false,allowDeploy:false}};
const step={stepId:"codex-job",kind:"CODEX_JOB"as const,job};
function item(n:number,state:CommissionCandidate["commissionState"]="COMMISSIONED"):CommissionCandidate{return{id:`item-${n}`,title:`Issue ${n}`,product:"LCC",source:"GITHUB",sourceRef:`https://github.com/knys/luckountry-control-center/issues/${n}`,repository:"knys/luckountry-control-center",issueNumber:n,issueUrl:`https://github.com/knys/luckountry-control-center/issues/${n}`,commissionState:state,suggestedNextActionJa:"実行",whyNotCommissioned:null,humanGate:null,humanActionJa:null,detectedAt:`2026-09-05T00:00:0${n}.000Z`,updatedAt:"2026-09-05T00:00:00.000Z",runId:`run-${n}`,priority:50,dependsOn:[],sourceRevision:"a".repeat(32),commissionLabel:"lcc:commission"}}
async function setup(){const dir=await mkdtemp(join(tmpdir(),"lcc-portfolio-")),path=join(dir,"runs.json"),store=await DurableSelfCommissioningStore.open(path),orchestrator=new SelfCommissioningOrchestrator(store,{tx:async()=>({status:"BLOCKED",summary:"no",evidence:[]}),gtx:async()=>({status:"BLOCKED",summary:"no",evidence:[]}),codex:async()=>({status:"SUCCEEDED",summary:"ok",evidence:[]})});const registrar:CommissionRunRegistrar={register:async(_candidate,id)=>{if(!await store.get(id))await orchestrator.create({runId:id,objective:id,steps:[step],retryLimit:3})}};return{dir,store,orchestrator,registrar,cleanup:()=>rm(dir,{recursive:true,force:true})}}

test("AC-01/02/07/10 reconcile repairs missing Run and resumes stale checkpoint durably",async t=>{const f=await setup();t.after(f.cleanup);await f.orchestrator.create({runId:"run-2",objective:"stale",steps:[step],retryLimit:3});const stored=await f.store.stored("run-2");assert.ok(stored);stored.run={...stored.run,status:"RUNNING",activeActor:"CODEX",activeExecutionId:"lost",queuedActor:null,queuedStep:null,updatedAt:"2026-09-04T00:00:00.000Z"};await f.store.replace(stored);const first=await new PortfolioSupervisor(f.store,f.registrar,()=>Date.parse("2026-09-05T00:00:00.000Z")).reconcile([item(1),item(2)]);assert.deepEqual(first.repairedMissing,["run-1"]);const reopened=await DurableSelfCommissioningStore.open(join(f.dir,"runs.json"));await new PortfolioSupervisor(reopened,f.registrar,()=>Date.parse("2026-09-05T00:00:00.000Z")).reconcile([item(1),item(2)]);assert.equal((await reopened.get("run-2"))?.status,"QUEUED");assert.match(JSON.stringify((await reopened.get("run-2"))?.history),/RESTART_RESUME/);assert.ok(portfolioPolicy.reconcileIntervalMs<=300_000);const durable=await DurableSelfCommissioningStore.open(join(f.dir,"runs.json"));assert.equal((await durable.get("run-2"))?.queuedStep,"codex-job")});

test("AC-02 live stale actor is recovered without restarting the portfolio",async t=>{const f=await setup();t.after(f.cleanup);await f.orchestrator.create({runId:"run-1",objective:"stale",steps:[step],retryLimit:3});const stored=await f.store.stored("run-1");assert.ok(stored);stored.run={...stored.run,status:"RUNNING",activeActor:"CODEX",activeExecutionId:"lost",queuedActor:null,queuedStep:null,updatedAt:"2026-09-04T00:00:00.000Z"};await f.store.replace(stored);const result=await new PortfolioSupervisor(f.store,f.registrar,()=>Date.parse("2026-09-05T00:00:00.000Z")).reconcile([item(1)]);assert.deepEqual(result.recovered,["run-1"]);assert.equal((await f.store.get("run-1"))?.recoveryBudget.consumed,1)});

test("AC-03/06 taxonomy is complete and unsafe authentication is isolated",async t=>{const f=await setup();t.after(f.cleanup);assert.equal(portfolioFailureTypes.length,16);for(const [text,type]of[["temporary network timeout","TRANSIENT_EXTERNAL"],["Codex exited 1","CODEX_FAILURE"],["Independent check failed: npm test","TEST_FAILURE"],["required CI checks failed","CI_FAILURE"],["merge conflict","MERGE_CONFLICT"],["deploy health canary failed","DEPLOY_FAILURE"],["credential 401","AUTH_EXPIRED"]]as const){await f.orchestrator.create({runId:`x-${type}`,objective:"x",steps:[step],retryLimit:0});await f.orchestrator.block(`x-${type}`,text);assert.equal(classifyPortfolioFailure((await f.store.get(`x-${type}`))!),type)}});

test("AC-04/05/14 one isolated and one Human-gated Issue do not stop unrelated queue",async t=>{const f=await setup();t.after(f.cleanup);for(const n of[1,2,3])await f.orchestrator.create({runId:`run-${n}`,objective:`run-${n}`,steps:[step],retryLimit:3});await f.orchestrator.block("run-1","credential expired 401");let waiting=await f.store.stored("run-2");assert.ok(waiting);waiting.run={...waiting.run,status:"WAITING_HUMAN",queuedActor:null,queuedStep:null,humanGate:"visual acceptance"};await f.store.replace(waiting);const result=await new PortfolioSupervisor(f.store,f.registrar).reconcile([item(1),item(2),item(3)]);assert.deepEqual(result.isolated.sort(),["run-1","run-2"]);assert.deepEqual(result.runnable,["run-3"]);assert.equal((await f.store.get("run-3"))?.status,"QUEUED")});

test("AC-11 repeated reconcile is idempotent and does not duplicate Run",async t=>{const f=await setup();t.after(f.cleanup);const supervisor=new PortfolioSupervisor(f.store,f.registrar);await supervisor.reconcile([item(1)]);await supervisor.reconcile([item(1)]);assert.equal((await f.store.list()).filter(v=>v.runId==="run-1").length,1)});
