import test from "node:test";
import assert from "node:assert/strict";
import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { DurableWatchdogStore, SelfCommissioningWatchdog, classifyWatchdog, watchdogPolicy, type WatchdogObservation, type WatchdogPorts } from "../src/application/self-commissioning-watchdog.js";
import type { SelfCommissioningRun } from "../src/domain/self-commissioning-run.js";

const at="2026-09-05T00:30:00.000Z",now=Date.parse(at);
function run(status:SelfCommissioningRun["status"],updatedAt=at):SelfCommissioningRun{return{runId:"commission-65",objective:"Issue 65",status,currentStep:status==="RUNNING"||status==="QUEUED"||status==="WAITING_HUMAN"||status==="BLOCKED"?"codex-job":null,activeActor:status==="RUNNING"?"CODEX":null,activeExecutionId:status==="RUNNING"?"execution":null,queuedActor:status==="QUEUED"?"CODEX":null,queuedStep:status==="QUEUED"?"codex-job":null,startedAt:updatedAt,updatedAt,completedSteps:[],failedStep:status==="BLOCKED"?"codex-job":null,blocker:status==="BLOCKED"?"Codex dispatch failure":null,humanGate:status==="WAITING_HUMAN"?"visual acceptance":null,retryBudget:{limit:3,consumed:3},recoveryBudget:{limit:3,consumed:0},history:[]}}
function observation(overrides:Partial<WatchdogObservation>={}):WatchdogObservation{return{observedAt:at,lccServiceActive:true,watcherServiceActive:true,healthReady:true,watcherState:"WATCHING",productionRevision:"a".repeat(40),expectedRevision:"a".repeat(40),stateReadable:true,runs:[],...overrides}}
async function fixture(observations:WatchdogObservation[]){const directory=await mkdtemp(join(tmpdir(),"lcc-watchdog-")),calls:{restart:string[];recover:unknown[];codex:unknown[];report:unknown[]}={restart:[],recover:[],codex:[],report:[]};let index=0;const ports:WatchdogPorts={inspect:async()=>observations[Math.min(index++,observations.length-1)]!,restart:async(service,key)=>{calls.restart.push(service+":"+key);return{ok:false,summary:"still down"}},recover:async input=>{calls.recover.push(input);return{ok:true,summary:"queued"}},codex:async input=>{calls.codex.push(input);return{ok:true,summary:"candidate committed"}},report:async input=>{calls.report.push(input);return{commentId:"123"}}};return{directory,path:join(directory,"state.json"),calls,ports,cleanup:()=>rm(directory,{recursive:true,force:true})}}

test("AC-02 normal states never trigger recovery",async()=>{for(const [expected,value] of [["WATCHING",observation()],["IDLE",observation({watcherState:null})],["RUNNING_WITH_ACTOR",observation({runs:[run("RUNNING")]})],["WAITING_HUMAN",observation({runs:[run("WAITING_HUMAN")]})]] as const){const f=await fixture([value]);try{const result=await new SelfCommissioningWatchdog(await DurableWatchdogStore.open(f.path),f.ports,()=>now).runOnce();assert.equal(result.classification,expected);assert.deepEqual(f.calls,{restart:[],recover:[],codex:[],report:[]})}finally{await f.cleanup()}}});

test("AC-03 classifies bounded failure taxonomy",()=>{assert.equal(classifyWatchdog(observation({lccServiceActive:false}),now),"HEALTH_OR_SERVICE_DOWN");assert.equal(classifyWatchdog(observation({watcherServiceActive:false}),now),"WATCHER_DOWN");assert.equal(classifyWatchdog(observation({stateReadable:false}),now),"STATE_CORRUPTION");assert.equal(classifyWatchdog(observation({productionRevision:"b".repeat(40)}),now),"REVISION_MISMATCH");assert.equal(classifyWatchdog(observation({runs:[run("RUNNING",new Date(now-watchdogPolicy.staleMs).toISOString())]}),now),"RUN_STALE");assert.equal(classifyWatchdog(observation({runs:[{...run("RUNNING"),activeActor:null}]}),now),"ACTOR_LOST");assert.equal(classifyWatchdog(observation({runs:[run("BLOCKED",new Date(now-watchdogPolicy.staleMs).toISOString())]}),now),"CODEX_FAILURE")});

test("AC-04/05 integrity inspection precedes and bounds allowlisted restart at three",async t=>{const down=observation({lccServiceActive:false,healthReady:false}),f=await fixture([down]);t.after(f.cleanup);for(let i=0;i<3;i++)await new SelfCommissioningWatchdog(await DurableWatchdogStore.open(f.path),f.ports,()=>now+i).runOnce();assert.equal(f.calls.restart.length,3);assert.ok(f.calls.restart.every(v=>v.startsWith("luckountry-control-center.service:")));const fourth=await new SelfCommissioningWatchdog(await DurableWatchdogStore.open(f.path),f.ports,()=>now+4).runOnce();assert.equal(fourth.action,"BLOCKED_WITH_EVIDENCE");assert.equal(f.calls.restart.length,3);assert.equal(f.calls.report.length,1)});

test("AC-06 formal recovery is failure-revision and idempotency bound",async t=>{const stale=observation({runs:[run("BLOCKED",new Date(now-watchdogPolicy.staleMs).toISOString())]}),f=await fixture([stale]);t.after(f.cleanup);const result=await new SelfCommissioningWatchdog(await DurableWatchdogStore.open(f.path),f.ports,()=>now).runOnce();assert.equal(result.action,"FORMAL_RECOVERY");assert.equal(f.calls.recover.length,1);assert.match(JSON.stringify(f.calls.recover[0]),/expectedFailure/);assert.match(JSON.stringify(f.calls.recover[0]),/formal-recovery/)});

test("AC-07/08/09 Codex is dedicated, timeout-bound, once per fingerprint and state survives restart",async t=>{const unknown=observation({codeFixRequired:true}),f=await fixture([unknown]);t.after(f.cleanup);let watchdog=new SelfCommissioningWatchdog(await DurableWatchdogStore.open(f.path),f.ports,()=>now);assert.equal((await watchdog.runOnce()).action,"CODEX_RECOVERY");watchdog=new SelfCommissioningWatchdog(await DurableWatchdogStore.open(f.path),f.ports,()=>now+1);assert.equal((await watchdog.runOnce()).action,"BLOCKED_WITH_EVIDENCE");assert.equal(f.calls.codex.length,1);assert.equal(f.calls.report.length,1);assert.match(JSON.stringify(f.calls.codex[0]),/lcc-watchdog-recovery/);assert.match(JSON.stringify(f.calls.codex[0]),/900000/);await watchdog.runOnce();assert.equal(f.calls.report.length,1);const persisted=JSON.parse(await readFile(f.path,"utf8"));assert.equal(persisted.incidents[0].codexAttempted,true);assert.equal(persisted.deliveries[0].commentId,"123")});

test("AC-07 enforces cross-fingerprint cooldown and 24-hour Codex budget",async t=>{const values=["a","b","c","d","e"].map(value=>observation({unknownFailure:true,productionRevision:value,expectedRevision:null})),f=await fixture(values);t.after(f.cleanup);let clock=now,watchdog=new SelfCommissioningWatchdog(await DurableWatchdogStore.open(f.path),f.ports,()=>clock);assert.equal((await watchdog.runOnce()).action,"CODEX_RECOVERY");assert.equal((await watchdog.runOnce()).action,"CODEX_COOLDOWN");clock+=watchdogPolicy.cooldownMs;assert.equal((await watchdog.runOnce()).action,"CODEX_RECOVERY");clock+=watchdogPolicy.cooldownMs;assert.equal((await watchdog.runOnce()).action,"CODEX_RECOVERY");clock+=watchdogPolicy.cooldownMs;assert.equal((await watchdog.runOnce()).action,"BLOCKED_WITH_EVIDENCE");assert.equal(f.calls.codex.length,3)});

test("AC-09 corrupt durable watchdog state fails closed",async t=>{const directory=await mkdtemp(join(tmpdir(),"lcc-watchdog-corrupt-")),path=join(directory,"state.json");t.after(()=>rm(directory,{recursive:true,force:true}));await writeFile(path,"not-json");await assert.rejects(DurableWatchdogStore.open(path),/Unexpected token|JSON/)});

test("AC-01/07/12 systemd timer, single-flight lock and recovery wrapper expose only fixed operations",async()=>{const timer=await readFile("ops/luckountry-self-commissioning-watchdog.timer","utf8"),service=await readFile("ops/luckountry-self-commissioning-watchdog.service","utf8"),wrapper=await readFile("ops/lcc-watchdog-recovery","utf8");assert.match(timer,/OnUnitActiveSec=5min/);assert.match(timer,/Persistent=true/);assert.doesNotMatch(service,/After=.*luckountry-control-center/);assert.match(service,/Type=oneshot/);assert.match(service,/flock -n .*single-flight\.lock/);assert.match(wrapper,/luckountry-control-center\.service/);assert.match(wrapper,/luckountry-commission-watcher\.service/);assert.doesNotMatch(wrapper,/eval|sh -c|bash -c|\$\{4/)});
