import assert from "node:assert/strict";
import test from "node:test";
import {mkdtemp,readFile,rm} from "node:fs/promises";
import {tmpdir} from "node:os";
import {join} from "node:path";
import {TxMaintenanceService,reconcilePilotCycle,reconcilePilotStore,type TxCommand,type TxMaintenanceContext} from "../src/application/tx-maintenance.js";
import type {PilotCycle} from "../src/domain/pilot.js";

async function fixture(){const dir=await mkdtemp(join(tmpdir(),"lcc-tx-maintenance-")),commands:TxCommand[]=[];const context:TxMaintenanceContext={repositoryPath:join(dir,"repository"),allowedRepository:"knys/luckountry-control-center",allowedRefs:["a".repeat(40)],storePath:join(dir,"maintenance.json"),runner:{run:async command=>{commands.push(command);return{code:0,stdout:"ok token=secret /home/private/file\n".repeat(200),stderr:""};}},status:async()=>["status ok"],migrate:async()=>["migrated"],reconcile:async()=>["reconciled"],now:(()=>{let n=0;return()=>Date.parse("2026-09-04T00:00:00Z")+n++;})()};return{dir,commands,context,cleanup:()=>rm(dir,{recursive:true,force:true})};}

test("L009-04 arbitrary shell, unknown operation, extra cwd/env and non-exact ref are rejected",async t=>{const f=await fixture();t.after(f.cleanup);const service=new TxMaintenanceService(f.context);for(const request of[{operation:"SHELL",idempotencyKey:"x",command:"rm -rf /"},{operation:"TX_LCC_STATUS",idempotencyKey:"x",cwd:"/tmp"},{operation:"TX_LCC_STATUS",idempotencyKey:"x",environment:{SECRET:"x"}},{operation:"TX_LCC_UPDATE_EXACT_REF",idempotencyKey:"x",exactRef:"main"}])await assert.rejects(service.execute(request),/reject|allow|exact|unknown/i);assert.equal(f.commands.length,0);});

test("L009-TX fixed argv, bounded timeout/output, disabled-first deploy, and durable idempotency",async t=>{const f=await fixture();t.after(f.cleanup);const service=new TxMaintenanceService(f.context),sha="a".repeat(40);for(const request of[{operation:"TX_LCC_UPDATE_EXACT_REF",idempotencyKey:"update-1",exactRef:sha},{operation:"TX_LCC_BUILD_TEST",idempotencyKey:"build-1"},{operation:"TX_LCC_DEPLOY_DISABLED",idempotencyKey:"deploy-1"},{operation:"TX_LCC_RESTART",idempotencyKey:"restart-1"}] as const){const result=await service.execute(request);assert.equal(result.status,"SUCCEEDED");assert.ok(result.evidence.every(value=>value.length<=500));assert.doesNotMatch(JSON.stringify(result),/secret|\/home\/private/i);}assert.ok(f.commands.every(value=>value.cwd===f.context.repositoryPath&&value.timeoutMs>0&&value.timeoutMs<=20*60_000));assert.ok(f.commands.some(value=>value.executable==="/usr/bin/git"&&value.args.includes(sha)));const deploy=f.commands.findIndex(value=>value.args.includes("TX_LCC_DEPLOY_DISABLED")),disable=f.commands.findIndex(value=>value.args.includes("WORK_AUTOMATION_MODE=disabled"));assert.ok(disable>=0&&disable<deploy);const before=f.commands.length,duplicate=await service.execute({operation:"TX_LCC_BUILD_TEST",idempotencyKey:"build-1"});assert.equal(duplicate.status,"SUCCEEDED");assert.equal(f.commands.length,before);const restored=new TxMaintenanceService(f.context),again=await restored.execute({operation:"TX_LCC_BUILD_TEST",idempotencyKey:"build-1"});assert.equal(again.status,"SUCCEEDED");assert.equal(f.commands.length,before);assert.match(await readFile(f.context.storePath,"utf8"),/build-1/);});

test("L009-TX migration is idempotent and interrupted idempotency resumes once",async t=>{const f=await fixture();t.after(f.cleanup);let migrations=0;f.context.migrate=async()=>{migrations++;return["v3"]};const first=new TxMaintenanceService(f.context);await first.execute({operation:"TX_LCC_MIGRATE_PILOT_STORE",idempotencyKey:"migration-v3"});await first.execute({operation:"TX_LCC_MIGRATE_PILOT_STORE",idempotencyKey:"migration-v3"});assert.equal(migrations,1);});

test("L009-TX restart resumes an interrupted record and concurrent duplicate dispatches once",async t=>{const f=await fixture();t.after(f.cleanup);await (await import("node:fs/promises")).mkdir(join(f.dir),{recursive:true});await (await import("node:fs/promises")).writeFile(f.context.storePath,JSON.stringify({version:1,results:[{idempotencyKey:"status-resume",operation:"TX_LCC_STATUS",status:"RUNNING",startedAt:"2026-09-04T00:00:00Z",finishedAt:null,summary:"interrupted",evidence:[]}]}));let calls=0,release!:()=>void;const gate=new Promise<void>(resolve=>release=resolve);f.context.status=async()=>{calls++;await gate;return["resumed"]};const service=new TxMaintenanceService(f.context),one=service.execute({operation:"TX_LCC_STATUS",idempotencyKey:"status-resume"}),two=service.execute({operation:"TX_LCC_STATUS",idempotencyKey:"status-resume"});while(calls===0)await new Promise(resolve=>setImmediate(resolve));assert.equal(calls,1);release();assert.deepEqual(await one,await two);assert.equal((await new TxMaintenanceService(f.context).execute({operation:"TX_LCC_STATUS",idempotencyKey:"status-resume"})).status,"SUCCEEDED");assert.equal(calls,1);});

test("L009-TX timeout is terminal, bounded, and durably observable",async t=>{const f=await fixture();t.after(f.cleanup);f.context.runner.run=async()=>{throw new Error("bounded operation timeout")};const result=await new TxMaintenanceService(f.context).execute({operation:"TX_LCC_BUILD_TEST",idempotencyKey:"timeout-1"});assert.equal(result.status,"TIMED_OUT");assert.ok(result.finishedAt);assert.match(await readFile(f.context.storePath,"utf8"),/TIMED_OUT/);});

test("L009-TX reconcile rebuilds stale cycle counters without deleting history or grants",()=>{const cycle:PilotCycle={cycleId:"pilot-1",scopeFingerprint:"fingerprint",workItemId:"work-1",status:"ARMED",baseHead:null,candidateBranch:null,candidateHead:null,executionAttempts:1,verificationRuns:0,startedAt:"a",updatedAt:"a",reason:"stale",recoveryRequestId:"pilot-1",recoveryConsumedAt:"b",recoveryCount:1,previousFailureReason:"attempt1",remediationRequestId:null,remediationConsumedAt:null,remediationCount:0,previousRemediationFailureReason:null},execution={leases:[],records:[{executionId:"e1",workItemId:"work-1",attempt:1,workerId:"gtx",requestedAt:"a",startedAt:"a",finishedAt:"b",resultStatus:"FAILED" as const,summary:"one",evidence:["one"]},{executionId:"e2",workItemId:"work-1",attempt:2,workerId:"gtx",requestedAt:"c",startedAt:"c",finishedAt:"d",resultStatus:"FAILED" as const,summary:"two",evidence:["two"],retryable:true}]},verification={leases:[],records:[]},beforeExecution=structuredClone(execution),beforeVerification=structuredClone(verification),next=reconcilePilotCycle(cycle,execution,verification,"FAILED","2026-09-04T00:00:00Z");assert.equal(next.status,"FAILED");assert.equal(next.executionAttempts,2);assert.equal(next.verificationRuns,0);assert.equal(next.recoveryCount,1);assert.equal(next.remediationCount,0);assert.equal(next.recoveryConsumedAt,"b");assert.deepEqual(execution,beforeExecution);assert.deepEqual(verification,beforeVerification);});

test("L009-TX fixed reconcile operation persists rebuilt cycle through repository API",async()=>{const cycle:PilotCycle={cycleId:"pilot-1",scopeFingerprint:"fingerprint",workItemId:"work-1",status:"ARMED",baseHead:null,candidateBranch:null,candidateHead:null,executionAttempts:1,verificationRuns:0,startedAt:"a",updatedAt:"a",reason:"stale",recoveryCount:1,remediationCount:0},execution={leases:[],records:[{executionId:"e1",workItemId:"work-1",attempt:1,workerId:"gtx",requestedAt:"a",startedAt:"a",finishedAt:"b",resultStatus:"FAILED" as const,summary:"one",evidence:[]},{executionId:"e2",workItemId:"work-1",attempt:2,workerId:"gtx",requestedAt:"c",startedAt:"c",finishedAt:"d",resultStatus:"FAILED" as const,summary:"two",evidence:[]}]},verification={leases:[],records:[]},saved:PilotCycle[]=[];const evidence=await reconcilePilotStore({pilotCycles:async()=>[structuredClone(cycle)],savePilotCycle:async value=>{saved.push(structuredClone(value))}},execution,verification,async()=>"FAILED","2026-09-04T00:00:00Z");assert.equal(saved[0]?.executionAttempts,2);assert.equal(saved[0]?.status,"FAILED");assert.match(evidence.join("\n"),/executionAttempts=2/);assert.equal(execution.records.length,2);});
