import test from "node:test";
import assert from "node:assert/strict";
import type { IncomingMessage, ServerResponse } from "node:http";
import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { DurableWorkItemRepository, type AtomicFileWriter } from "../src/infrastructure/durable-work-item-repository.js";
import { IssueSyncService, type IssueSource, type WorkItemRepository } from "../src/application/issue-sync-service.js";
import { WorkTransitionService } from "../src/application/work-transition-service.js";
import { ProductService, parseProductsManifest, type GitHubMetadataProvider } from "../src/products.js";
import { createRequestHandler } from "../src/http-app.js";

const repo = "knys/repo"; const id = `github:${repo}:8`;
const source: IssueSource = { fetchOpenIssues: async () => [{ externalId: "8", title: "Original", state: "open", labels: [], assignees: [], updatedAt: "2026-09-03T00:00:00Z", url: `https://github.com/${repo}/issues/8` }] };
async function fixture() { const directory = await mkdtemp(join(tmpdir(), "lcc-004-")); return { path: join(directory, "state.json"), cleanup: () => rm(directory, { recursive: true, force: true }) }; }

test("T13 new_issue_is_not_auto_ready", async () => { const memory = new (await import("../src/infrastructure/in-memory-work-item-repository.js")).InMemoryWorkItemRepository(); await new IssueSyncService(source, memory).sync(repo); const item = (await memory.list(repo))[0]!; assert.equal(item.workState, "DEFINED"); assert.equal(item.ballHolder, "HUMAN"); assert.equal(item.nextAction.kind, "DEFINE"); assert.equal(item.nextAction.aiExecutable, false); });

test("T15 transition_persists_atomically", async (context) => { const file = await fixture(); context.after(file.cleanup); const repository = await DurableWorkItemRepository.open(file.path); await new IssueSyncService(source, repository).sync(repo); const result = await new WorkTransitionService(repository).transition(id, { type: "DEFINITION_COMPLETED", executor: "CODEX" }); assert.equal(result.workItem.workState, "READY"); assert.equal((await repository.list(repo))[0]?.transitionReason, result.decision.reason); });
test("T16 transition_restores_after_restart", async (context) => { const file = await fixture(); context.after(file.cleanup); const repository = await DurableWorkItemRepository.open(file.path); await new IssueSyncService(source, repository).sync(repo); await new WorkTransitionService(repository).transition(id, { type: "DEFINITION_COMPLETED", executor: "CODEX" }); const restored = (await (await DurableWorkItemRepository.open(file.path)).list(repo))[0]!; assert.equal(restored.workState, "READY"); assert.equal(restored.ballHolder, "CODEX"); assert.equal(restored.nextAction.kind, "EXECUTE"); assert.match(restored.transitionReason, /DEFINITION_COMPLETED/); });
test("T17 source_sync_preserves_execution_state", async (context) => { const file = await fixture(); context.after(file.cleanup); const repository = await DurableWorkItemRepository.open(file.path); await new IssueSyncService(source, repository).sync(repo); await new WorkTransitionService(repository).transition(id, { type: "DEFINITION_COMPLETED", executor: "CODEX" }); await new IssueSyncService({ fetchOpenIssues: async () => [{ ...(await source.fetchOpenIssues(repo))[0]!, title: "Changed" }] }, repository).sync(repo); const item = (await repository.list(repo))[0]!; assert.equal(item.title, "Changed"); assert.equal(item.workState, "READY"); });

test("T18 concurrent_sync_and_transition_no_lost_update", async (context) => { const file = await fixture(); context.after(file.cleanup); const durable = await DurableWorkItemRepository.open(file.path); await new IssueSyncService(source, durable).sync(repo); let release!: () => void; let entered!: () => void; const gate = new Promise<void>((resolve) => { release = resolve; }); const atCommit = new Promise<void>((resolve) => { entered = resolve; }); const wrapper: WorkItemRepository = { list: (r) => durable.list(r), metadata: (r) => durable.metadata(r), recordFailure: (r,m) => durable.recordFailure(r,m), transitionExecutionState: (i,u) => durable.transitionExecutionState(i,u), commitSync: async (r,w,m) => { entered(); await gate; return durable.commitSync(r,w,m); } }; const syncing = new IssueSyncService({ fetchOpenIssues: async () => [{ ...(await source.fetchOpenIssues(repo))[0]!, title: "Concurrent source" }] }, wrapper).sync(repo); await atCommit; await new WorkTransitionService(durable).transition(id, { type: "DEFINITION_COMPLETED", executor: "CODEX" }); release(); await syncing; const item = (await durable.list(repo))[0]!; assert.equal(item.title, "Concurrent source"); assert.equal(item.workState, "READY"); });

test("T19 failed_transition_does_not_partially_write", async (context) => { const file = await fixture(); context.after(file.cleanup); const first = await DurableWorkItemRepository.open(file.path); await new IssueSyncService(source, first).sync(repo); const failing: AtomicFileWriter = async () => { throw new Error("disk full"); }; const reopened = await DurableWorkItemRepository.open(file.path, failing); await assert.rejects(new WorkTransitionService(reopened).transition(id, { type: "DEFINITION_COMPLETED", executor: "CODEX" }), /disk full/); assert.equal((await (await DurableWorkItemRepository.open(file.path)).list(repo))[0]?.workState, "DEFINED"); });

test("T20 schema_v1_to_v2_migration", async (context) => { const file = await fixture(); context.after(file.cleanup); const item = { id, source: { provider: "github", repository: repo, externalId: "8" }, title: "Legacy", sourceState: "open", labels: [], assignees: [], sourceUrl: `https://github.com/${repo}/issues/8`, workState: "READY", ballHolder: "CODEX", nextAction: "Implement", blocker: null, acceptanceCriteria: [], evidence: [], sourceUpdatedAt: "2026-09-01T00:00:00Z", lastSyncedAt: "2026-09-01T00:00:00Z" }; const metadata = { status: "SUCCEEDED", lastAttemptedSyncAt: item.lastSyncedAt, lastSuccessfulSyncAt: item.lastSyncedAt, failureReason: null, failureType: null, resetAt: null, retryAfter: null }; await writeFile(file.path, JSON.stringify({ schemaVersion: 1, repositories: { [repo]: { workItems: [item], metadata } } })); const migrated = (await (await DurableWorkItemRepository.open(file.path)).list(repo))[0]!; assert.equal(migrated.workState, "DEFINED"); assert.equal(migrated.ballHolder, "HUMAN"); assert.equal(migrated.nextAction.aiExecutable, false); assert.equal(JSON.parse(await readFile(file.path, "utf8")).schemaVersion, 3); });
test("T21 migration_failure_preserves_original_storage", async (context) => { const file = await fixture(); context.after(file.cleanup); const original = JSON.stringify({ schemaVersion: 1, repositories: { [repo]: { workItems: [{ broken: true }], metadata: {} } } }); await writeFile(file.path, original); await assert.rejects(DurableWorkItemRepository.open(file.path), /migration.*failed/i); assert.equal(await readFile(file.path, "utf8"), original); });
test("T22 execution_state_read_only_observability", async (context) => { const file = await fixture(); context.after(file.cleanup); const repository = await DurableWorkItemRepository.open(file.path); await new IssueSyncService(source, repository).sync(repo); const manifest = parseProductsManifest({ version: 1, products: [{ id: "x", name: "X", repository: repo, summary: "X", status: "READY", ball: "CODEX", nextAction: "X" }] }); const provider: GitHubMetadataProvider = { fetch: async () => new Map() }; const handler = createRequestHandler(new ProductService(manifest, provider), [], undefined, undefined, async () => repository.list(repo)); let body=""; await new Promise<void>((resolve) => handler({method:"GET",url:"/api/work-items"} as IncomingMessage,{writeHead:()=>undefined,end:(value:string)=>{body=value;resolve();}} as unknown as ServerResponse)); const response=JSON.parse(body); assert.equal(response.workItems[0].workState,"DEFINED"); response.workItems[0].workState="DONE"; assert.equal((await repository.list(repo))[0]?.workState,"DEFINED"); });
