import test from "node:test";
import assert from "node:assert/strict";
import { actionKinds, allowedTransitions, ballHolders, InvalidWorkTransitionError, transitionWorkItem, workStates, type CanonicalBallHolder, type CanonicalWorkState, type NextAction, type WorkEvent } from "../src/domain/work-state-machine.js";
import type { WorkItem } from "../src/domain/work-item.js";

const base = (state: CanonicalWorkState = "DEFINED", changes: Record<string, unknown> = {}): WorkItem => ({ id: "github:knys/repo:8", source: { provider: "github", repository: "knys/repo", externalId: "8" }, title: "State machine", sourceState: "open", labels: [], assignees: [], sourceUrl: "https://github.com/knys/repo/issues/8", workState: state, ballHolder: "HUMAN", nextAction: { kind: "DEFINE", summary: "Define work", ballHolder: "HUMAN", aiExecutable: false, requiredCapabilities: [] }, blocker: null, acceptanceCriteria: [], evidence: [], sourceUpdatedAt: "2026-09-03T00:00:00Z", lastSyncedAt: "2026-09-03T00:00:00Z", transitionReason: "Created safely", ...changes } as unknown as WorkItem);
const events = new Map<string, WorkEvent>([
  ["IDEA>DEFINED", { type: "DEFINITION_STARTED" }], ["DEFINED>READY", { type: "DEFINITION_COMPLETED", executor: "CODEX" }], ["DEFINED>BLOCKED", { type: "BLOCKER_SET", owner: "HUMAN", summary: "Need input" }],
  ["READY>RUNNING", { type: "EXECUTION_STARTED" }], ["READY>WAITING_HUMAN", { type: "HUMAN_REQUIRED", summary: "Approve" }], ["READY>WAITING_WORKER", { type: "WORKER_UNAVAILABLE", monitor: "LCC" }], ["READY>BLOCKED", { type: "BLOCKER_SET", owner: "EXTERNAL", summary: "Vendor" }],
  ["RUNNING>VERIFYING", { type: "EXECUTION_COMPLETED", verification: "AUTOMATED" }], ["RUNNING>FAILED", { type: "TERMINAL_FAILURE" }], ["RUNNING>WAITING_HUMAN", { type: "HUMAN_REQUIRED", summary: "Inspect" }], ["RUNNING>WAITING_WORKER", { type: "WORKER_UNAVAILABLE", monitor: "LCC" }], ["RUNNING>BLOCKED", { type: "BLOCKER_SET", owner: "HUMAN", summary: "Blocked" }],
  ["VERIFYING>DONE", { type: "VERIFICATION_PASSED" }], ["VERIFYING>RUNNING", { type: "VERIFICATION_FAILED" }], ["VERIFYING>WAITING_HUMAN", { type: "HUMAN_REQUIRED", summary: "Accept" }], ["VERIFYING>FAILED", { type: "TERMINAL_FAILURE" }], ["VERIFYING>BLOCKED", { type: "BLOCKER_SET", owner: "HUMAN", summary: "Blocked" }],
  ["FAILED>RETRYING", { type: "RETRY_STARTED" }], ["FAILED>WAITING_HUMAN", { type: "HUMAN_REQUIRED", summary: "Decide" }], ["FAILED>BLOCKED", { type: "BLOCKER_SET", owner: "HUMAN", summary: "Blocked" }],
  ["RETRYING>RUNNING", { type: "EXECUTION_STARTED" }], ["RETRYING>FAILED", { type: "TERMINAL_FAILURE" }], ["RETRYING>BLOCKED", { type: "BLOCKER_SET", owner: "EXTERNAL", summary: "Blocked" }],
  ["WAITING_HUMAN>READY", { type: "HUMAN_COMPLETED", executor: "CODEX" }], ["WAITING_HUMAN>BLOCKED", { type: "BLOCKER_SET", owner: "HUMAN", summary: "Blocked" }], ["WAITING_WORKER>READY", { type: "WORKER_AVAILABLE", executor: "CODEX" }], ["WAITING_WORKER>BLOCKED", { type: "BLOCKER_SET", owner: "EXTERNAL", summary: "Blocked" }], ["BLOCKED>READY", { type: "BLOCKER_CLEARED", executor: "CODEX" }], ["DONE>READY", { type: "REOPENED", executor: "CODEX" }]
]);

test("T01 canonical_work_states", () => assert.deepEqual(workStates, ["IDEA", "DEFINED", "READY", "RUNNING", "VERIFYING", "WAITING_HUMAN", "WAITING_WORKER", "BLOCKED", "FAILED", "RETRYING", "DONE", "UNKNOWN"]));
test("T02 canonical_ball_holders_include_lcc", () => assert.deepEqual(ballHolders, ["LCC", "CHATGPT", "CODEX", "HUMAN", "EXTERNAL", "NONE", "UNKNOWN"]));
test("T03 structured_next_action", () => { const action: NextAction = { kind: "EXECUTE", summary: "Implement", ballHolder: "CODEX", aiExecutable: true, requiredCapabilities: ["CODE_EDIT"] }; assert.ok(actionKinds.includes(action.kind)); assert.equal(action.requiredCapabilities[0], "CODE_EDIT"); });
test("T04 allowed_transition_matrix", () => { for (const [from, targets] of Object.entries(allowedTransitions)) for (const to of targets) { const event = events.get(`${from}>${to}`); assert.ok(event, `missing event ${from}>${to}`); assert.equal(transitionWorkItem(base(from as CanonicalWorkState), event).decision.to, to); } });
test("T05 forbidden_transition_rejected", () => assert.throws(() => transitionWorkItem(base("DEFINED"), { type: "VERIFICATION_PASSED" }), InvalidWorkTransitionError));
test("T06 running_cannot_skip_verifying", () => assert.throws(() => transitionWorkItem(base("RUNNING"), { type: "VERIFICATION_PASSED" }), InvalidWorkTransitionError));
test("T07 transition_decision_is_deterministic", () => { const item = base(); const event = { type: "DEFINITION_COMPLETED", executor: "CODEX" } as const; assert.deepEqual(transitionWorkItem(item, event), transitionWorkItem(item, event)); });
test("T08 human_acceptance_assigns_human_ball", () => { const result = transitionWorkItem(base("RUNNING"), { type: "EXECUTION_COMPLETED", verification: "HUMAN" }); assert.equal(result.workItem.workState, "VERIFYING"); assert.equal(result.workItem.ballHolder, "HUMAN"); assert.equal((result.workItem.nextAction as unknown as NextAction).aiExecutable, false); });
test("T09 automated_verification_assigns_lcc_ball", () => { const result = transitionWorkItem(base("RUNNING"), { type: "EXECUTION_COMPLETED", verification: "AUTOMATED" }); assert.equal(result.workItem.ballHolder, "LCC"); assert.equal((result.workItem.nextAction as unknown as NextAction).kind, "VERIFY"); });
test("T10 waiting_worker_can_keep_lcc_ball", () => { const result = transitionWorkItem(base("RUNNING"), { type: "WORKER_UNAVAILABLE", monitor: "LCC" }); assert.equal(result.workItem.ballHolder, "LCC"); assert.equal((result.workItem.nextAction as unknown as NextAction).kind, "WAIT_WORKER"); });
test("T11 retrying_assigns_lcc_retry_action", () => { const result = transitionWorkItem(base("FAILED"), { type: "RETRY_STARTED" }); assert.equal(result.workItem.ballHolder, "LCC"); assert.equal((result.workItem.nextAction as unknown as NextAction).kind, "RETRY"); });
test("T12 done_clears_ball_and_action", () => { const result = transitionWorkItem(base("VERIFYING"), { type: "VERIFICATION_PASSED" }); assert.equal(result.workItem.ballHolder, "NONE"); assert.equal((result.workItem.nextAction as unknown as NextAction).kind, "NONE"); });
test("T14 ready_requires_explicit_event", () => { assert.throws(() => transitionWorkItem(base("DEFINED"), { type: "EXECUTION_STARTED" }), InvalidWorkTransitionError); assert.equal(transitionWorkItem(base("DEFINED"), { type: "DEFINITION_COMPLETED", executor: "CODEX" }).decision.to, "READY"); });
