export type VerificationCriterion={id:string;kind:"AUTO"|"HUMAN";summary:string;automatedCheckIds:string[]};
export type AcceptanceParseResult={valid:true;criteria:VerificationCriterion[]}|{valid:false;criteria:[];reason:string};
export type VerificationCheckStatus="PASSED"|"FAILED"|"TIMED_OUT"|"ERROR";
export interface VerificationCheckResult{checkId:string;status:VerificationCheckStatus;exitCode?:number;startedAt:string;finishedAt:string;summary:string;evidence:string[]}
export interface CriterionEvidence{criterionId:string;checkIds:string[];status:"PASSED"|"FAILED"|"HUMAN_REQUIRED"}
export interface VerificationRequest{verificationId:string;workItemId:string;sourceExecutionId:string;repository:string;workspaceId:string;profileId:string;checkIds:string[]}
export interface VerificationResult{verificationId:string;status:"PASSED"|"FAILED"|"ERROR"|"CANCELLED";startedAt:string;finishedAt:string;verifiedHead?:string;checks:VerificationCheckResult[];summary:string;evidence:string[]}
export interface VerificationRecord{verificationId:string;workItemId:string;sourceExecutionId:string;repository:string;workerId:string;workspaceId:string;profileId:string;requestedAt:string;startedAt:string;finishedAt:string|null;verifiedHead:string|null;status:"ACTIVE"|"PASSED"|"FAILED"|"HUMAN_REQUIRED"|"ERROR";criteria:VerificationCriterion[];criterionEvidence:CriterionEvidence[];checks:VerificationCheckResult[];summary:string;evidence:string[]}
export interface VerificationLease{verificationId:string;workItemId:string;repository:string;workerId:string;acquiredAt:string;status:"ACTIVE"|"COMPLETED"|"ABANDONED"}
export interface VerificationState{leases:VerificationLease[];records:VerificationRecord[]}

export function extractAcceptanceCriteria(body:string|null|undefined):string[]{if(!body)return[];const lines=body.split(/\r?\n/);let inside=false;const output:string[]=[];for(const line of lines){const heading=line.match(/^(#{1,6})\s+(.+?)\s*$/);if(heading){if(inside)break;inside=heading[1]==="##"&&heading[2]?.trim().toLowerCase()==="acceptance criteria";continue;}if(!inside)continue;const checkbox=line.match(/^\s*[-*+]\s+\[[ xX]\]\s+(.+?)\s*$/);if(checkbox)output.push(checkbox[1]!.slice(0,500));}return output;}
export function parseAcceptanceCriteria(lines:readonly string[]):AcceptanceParseResult{if(lines.length===0)return invalid("Acceptance Criteria section is missing or empty");const criteria:VerificationCriterion[]=[],seen=new Set<string>();for(const line of lines){const match=line.match(/^(AC-\d+)\s+\[(HUMAN|AUTO:([^\]]+))\]\s+(.+)$/);if(!match)return invalid(`Malformed Acceptance criterion: ${line.slice(0,100)}`);const id=match[1]!;if(seen.has(id))return invalid(`Duplicate Acceptance criterion: ${id}`);seen.add(id);const kind=match[2]==="HUMAN"?"HUMAN":"AUTO",checks=kind==="AUTO"?match[3]!.split(","):[];if(checks.some(check=>!check||!/^[A-Za-z0-9._-]+$/.test(check))||new Set(checks).size!==checks.length)return invalid(`Malformed check IDs for ${id}`);criteria.push({id,kind,summary:match[4]!.trim(),automatedCheckIds:checks});}return{valid:true,criteria};}
export function verificationPlan(parsed:AcceptanceParseResult,availableCheckIds:readonly string[]):{valid:true;criteria:VerificationCriterion[];checkIds:string[]}|{valid:false;reason:string}{if(!parsed.valid)return{valid:false,reason:parsed.reason};const available=new Set(availableCheckIds),checkIds=[...new Set(parsed.criteria.flatMap(item=>item.automatedCheckIds))];const unknown=checkIds.filter(id=>!available.has(id));return unknown.length?{valid:false,reason:`Unknown verification checks: ${unknown.join(", ")}`}:{valid:true,criteria:structuredClone(parsed.criteria),checkIds};}
export function decideVerification(criteria:readonly VerificationCriterion[],checks:readonly VerificationCheckResult[]):{status:"PASSED"|"FAILED"|"HUMAN_REQUIRED";criterionEvidence:CriterionEvidence[];reason:string}{const byId=new Map(checks.map(check=>[check.checkId,check])),mapping=criteria.map(criterion=>criterion.kind==="HUMAN"?{criterionId:criterion.id,checkIds:[],status:"HUMAN_REQUIRED" as const}:{criterionId:criterion.id,checkIds:[...criterion.automatedCheckIds],status:criterion.automatedCheckIds.every(id=>byId.get(id)?.status==="PASSED")?"PASSED" as const:"FAILED" as const});const failed=mapping.filter(item=>item.status==="FAILED").map(item=>item.criterionId);if(failed.length)return{status:"FAILED",criterionEvidence:mapping,reason:`Failed AUTO criteria: ${failed.join(", ")}`};const human=mapping.filter(item=>item.status==="HUMAN_REQUIRED").map(item=>item.criterionId);if(human.length)return{status:"HUMAN_REQUIRED",criterionEvidence:mapping,reason:`Human criteria remain: ${human.join(", ")}`};return{status:"PASSED",criterionEvidence:mapping,reason:"All AUTO criteria have PASSED evidence"};}
function invalid(reason:string):AcceptanceParseResult{return{valid:false,criteria:[],reason};}
