import type { ExecutionRequest } from "../application/execution.js";
import type { WorkerDescriptor } from "../application/execution.js";
import { executeCodex, probeCodex, type CodexProbe } from "./codex-cli.js";
import { preflightWorkspace, resolveWorkspace, type CommandRunner, type WorkspaceManifest } from "./workspace.js";
import { WorkerBusyError, WorkerConflictError, WorkerExecutionStore } from "./execution-store.js";

export const DEFAULT_WORKER_HOST = "127.0.0.1";
export const DEFAULT_WORKER_PORT = 9200;
export const MAX_REQUEST_BODY_BYTES = 64 * 1024;
export class WorkerExecutionAgent {
  private readonly controllers = new Map<string, AbortController>();
  constructor(readonly descriptor: WorkerDescriptor, private readonly manifest: WorkspaceManifest, private readonly store: WorkerExecutionStore, private readonly codex: CodexProbe, private readonly run?: CommandRunner) {}
  async submit(request: ExecutionRequest): Promise<{ statusCode: number; record: unknown }> { validateRequest(request);const workspace=resolveWorkspace(this.manifest,request.workspaceId,request.repository); const saved=await this.store.create(request); if (!saved.created) return {statusCode:200,record:saved.record}; try{await preflightWorkspace(workspace,this.run);}catch(error){await this.store.patch(request.executionId,item=>{item.status="FAILED";item.finishedAt=new Date().toISOString();item.summary=error instanceof Error?error.message:"Workspace preflight failed";});throw error;} const controller=new AbortController(); this.controllers.set(request.executionId,controller); await this.store.patch(request.executionId,item=>{item.status="RUNNING";item.startedAt=new Date().toISOString();item.summary="Running";}); void this.finish(request,workspace).catch(()=>undefined); return {statusCode:202,record:await this.store.get(request.executionId)}; }
  async status(id:string):Promise<unknown|null>{return this.store.get(id);}
  async cancel(id:string):Promise<unknown|null>{const controller=this.controllers.get(id);const current=await this.store.get(id);if(!current)return null;if(controller)controller.abort();if(["QUEUED","RUNNING"].includes(current.status))return this.store.patch(id,item=>{item.status="CANCELLED";item.finishedAt=new Date().toISOString();item.summary="Cancelled";});return current;}
  private async finish(request:ExecutionRequest,workspace:ReturnType<typeof resolveWorkspace>):Promise<void>{const controller=this.controllers.get(request.executionId)!;const timeout=setTimeout(()=>controller.abort(),30*60_000);try{const result=await executeCodex(request,workspace,this.codex,this.run,controller.signal);await this.store.patch(request.executionId,item=>{if(item.status==="CANCELLED")return;item.status=controller.signal.aborted?"TIMED_OUT":result.status;item.finishedAt=result.finishedAt;item.summary=result.summary;item.evidence=result.evidence;});}catch(error){await this.store.patch(request.executionId,item=>{if(item.status==="CANCELLED")return;item.status=controller.signal.aborted?"TIMED_OUT":"FAILED";item.finishedAt=new Date().toISOString();item.summary=error instanceof Error?error.message:"Worker failure";});}finally{clearTimeout(timeout);this.controllers.delete(request.executionId);}}
}
export async function createWorkerDescriptor(workerId:string,manifest:WorkspaceManifest,run?:CommandRunner):Promise<{descriptor:WorkerDescriptor;probe:CodexProbe}>{const probe=await probeCodex(run);return{probe,descriptor:{workerId,status:"ONLINE",capabilities:[...new Set(manifest.workspaces.flatMap(item=>item.capabilities))],workspaceIds:manifest.workspaces.map(item=>item.workspaceId),executorKinds:["CODEX"],agentVersion:"1",codexVersion:probe.version,codexReady:probe.codexReady,lastHealthAt:new Date().toISOString()}};}
export { WorkerBusyError, WorkerConflictError };
function validateRequest(request:ExecutionRequest):void{if(!request||!/^[-A-Za-z0-9._]+$/.test(request.executionId)||!request.workItemId||request.actionKind!=="EXECUTE"||!request.repository||!request.workspaceId||!request.summary||!Array.isArray(request.requiredCapabilities))throw new Error("invalid ExecutionRequest");let source:URL;try{source=new URL(request.sourceUrl);}catch{throw new Error("invalid sourceUrl");}if(source.protocol!=="https:"||source.hostname!=="github.com"||!source.pathname.toLowerCase().startsWith(`/${request.repository.toLowerCase()}/issues/`))throw new Error("sourceUrl does not match repository");}
