import { createServer, type IncomingMessage, type ServerResponse } from "node:http";
import { HmacVerifier, type HmacHeaders } from "../infrastructure/hmac-auth.js";
import { DEFAULT_WORKER_HOST, DEFAULT_WORKER_PORT, MAX_REQUEST_BODY_BYTES, WorkerBusyError, WorkerConflictError, type WorkerExecutionAgent } from "./execution-agent.js";
import type { ExecutionRequest } from "../application/execution.js";
import type { VerificationRequest } from "../domain/verification.js";
import { VerificationConflictError,type WorkerVerificationAgent } from "./verification-agent.js";

function json(response:ServerResponse,status:number,value:unknown):void{response.writeHead(status,{"content-type":"application/json; charset=utf-8","cache-control":"no-store"});response.end(JSON.stringify(value));}
export function createWorkerHandler(agent:WorkerExecutionAgent,verifier:HmacVerifier,verification?:WorkerVerificationAgent){return async(request:IncomingMessage,response:ServerResponse)=>{const path=new URL(request.url??"/","http://worker").pathname;if(request.method==="GET"&&path==="/v1/health")return json(response,200,{status:"ok"});let body="";for await(const chunk of request){body+=String(chunk);if(Buffer.byteLength(body)>MAX_REQUEST_BODY_BYTES)return json(response,413,{error:"body_too_large"});}const headers=Object.fromEntries(Object.entries(request.headers).map(([key,value])=>[key,Array.isArray(value)?value[0]:value])) as Partial<HmacHeaders>;if(!verifier.verify(request.method??"",path,body,headers))return json(response,401,{error:"unauthorized"});try{if(request.method==="GET"&&path==="/v1/descriptor")return json(response,200,sanitizeDescriptor(agent.descriptor));if(request.method==="POST"&&path==="/v1/executions")return void(await agent.submit(JSON.parse(body) as ExecutionRequest).then(result=>json(response,result.statusCode,result.record)));if(request.method==="POST"&&path==="/v1/verifications"&&verification)return void(await verification.submit(JSON.parse(body) as VerificationRequest).then(result=>json(response,result.statusCode,result.record)));const vm=path.match(/^\/v1\/verifications\/([A-Za-z0-9._-]+)(\/cancel)?$/);if(vm&&verification&&request.method==="GET"&&!vm[2]){const record=await verification.status(vm[1]!);return record?json(response,200,record):json(response,404,{error:"not_found"});}if(vm&&verification&&request.method==="POST"&&vm[2]){const record=await verification.cancel(vm[1]!);return record?json(response,200,record):json(response,404,{error:"not_found"});}const match=path.match(/^\/v1\/executions\/([A-Za-z0-9._-]+)(\/cancel)?$/);if(match&&request.method==="GET"&&!match[2]){const record=await agent.status(match[1]!);return record?json(response,200,record):json(response,404,{error:"not_found"});}if(match&&request.method==="POST"&&match[2]){const record=await agent.cancel(match[1]!);return record?json(response,200,record):json(response,404,{error:"not_found"});}return json(response,404,{error:"not_found"});}catch(error){if(error instanceof WorkerConflictError||error instanceof WorkerBusyError||error instanceof VerificationConflictError)return json(response,409,{error:error.message});return json(response,400,{error:"invalid_request"});}};}
export function startWorkerServer(agent:WorkerExecutionAgent,verifier:HmacVerifier,environment:NodeJS.ProcessEnv=process.env,verification?:WorkerVerificationAgent){const host=environment.WORKER_BIND_ADDRESS?.trim()||DEFAULT_WORKER_HOST;const port=positivePort(environment.WORKER_PORT)||DEFAULT_WORKER_PORT;const server=createServer(createWorkerHandler(agent,verifier,verification));server.listen(port,host);return server;}
function positivePort(value:string|undefined):number|null{const parsed=Number(value);return Number.isInteger(parsed)&&parsed>0&&parsed<=65535?parsed:null;}
function sanitizeDescriptor(value:WorkerExecutionAgent["descriptor"]){return{workerId:value.workerId,status:value.status,capabilities:[...value.capabilities],workspaceIds:[...value.workspaceIds],executorKinds:[...value.executorKinds],verificationProfiles:structuredClone(value.verificationProfiles??{}),agentVersion:value.agentVersion,codexVersion:value.codexVersion,codexReady:value.codexReady,lastHealthAt:value.lastHealthAt};}
