import { readFile } from "node:fs/promises";
import { HmacVerifier } from "../infrastructure/hmac-auth.js";
import { createWorkerDescriptor, WorkerExecutionAgent } from "./execution-agent.js";
import { WorkerExecutionStore } from "./execution-store.js";
import { startWorkerServer } from "./http-server.js";
import { parseWorkspaceManifest,preflightWorkspace,resolveWorkspace,runCommand } from "./workspace.js";
import { resolveVerificationProfiles } from "./verifier.js";
import { WorkerVerificationStore } from "./verification-store.js";
import { WorkerVerificationAgent } from "./verification-agent.js";
import { GtxWorkerMaintenanceService } from "./maintenance.js";

const configPath=required("WORKER_WORKSPACES_CONFIG"),secret=required("WORKER_HMAC_SECRET"),keyId=required("WORKER_HMAC_KEY_ID"),workerId=required("WORKER_ID"),statePath=required("WORKER_STATE_PATH");
const manifest=parseWorkspaceManifest(JSON.parse(await readFile(configPath,"utf8"))),profilePath=process.env.WORKER_VERIFICATION_PROFILES_CONFIG?.trim(),profiles=profilePath?await resolveVerificationProfiles(JSON.parse(await readFile(profilePath,"utf8"))):[],store=await WorkerExecutionStore.open(statePath),profileIndex=Object.fromEntries(profiles.map(profile=>[profile.profileId,Object.keys(profile.checks)]));const runtime=await createWorkerDescriptor(workerId,manifest,undefined,profileIndex);let verification:WorkerVerificationAgent|undefined;const agent=new WorkerExecutionAgent(runtime.descriptor,manifest,store,runtime.probe,undefined,workspaceId=>verification?.active(workspaceId)??Promise.resolve(false));let verificationState:string|undefined;if(profiles.length){verificationState=required("WORKER_VERIFICATION_STATE_PATH");const verificationStore=await WorkerVerificationStore.open(verificationState);verification=new WorkerVerificationAgent(manifest,profiles,verificationStore,undefined,workspaceId=>store.active(workspaceId));}const maintenance=composeMaintenance();const server=startWorkerServer(agent,new HmacVerifier({keyId,secret}),process.env,verification,maintenance);
function composeMaintenance():GtxWorkerMaintenanceService|undefined{const repository=process.env.WORKER_REPOSITORY_PATH?.trim(),maintenanceState=process.env.WORKER_MAINTENANCE_STATE_PATH?.trim(),git=process.env.WORKER_GIT_EXECUTABLE?.trim(),restart=process.env.WORKER_RESTART_HELPER?.trim(),refs=(process.env.WORKER_ALLOWED_UPDATE_REFS??"").split(",").map(v=>v.trim()).filter(v=>/^[0-9a-f]{40}$/i.test(v));if(!repository||!maintenanceState||!git||!restart||!refs.length)return undefined;return new GtxWorkerMaintenanceService({workerRepositoryPath:repository,allowedRefs:refs,allowedWorkspaceIds:manifest.workspaces.map(v=>v.workspaceId),storePath:maintenanceState,protectedPaths:[statePath,...(verificationState?[verificationState]:[]),...manifest.workspaces.map(v=>v.path)],gitExecutable:git,nodeExecutable:runtime.probe.command.executable,restartHelperExecutable:restart,run:command=>{const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),command.timeoutMs);return runCommand(command.executable,[...command.args],command.cwd,undefined,undefined,controller.signal).finally(()=>clearTimeout(timer));},status:async()=>[`workerId=${agent.descriptor.workerId}`,`status=${agent.descriptor.status}`],descriptor:async()=>structuredClone(agent.descriptor),preflight:async workspaceId=>{const workspace=manifest.workspaces.find(v=>v.workspaceId===workspaceId);if(!workspace)throw new Error("workspace is not allowlisted");return preflightWorkspace(resolveWorkspace(manifest,workspaceId,workspace.repository));}});}
function required(name:string):string{const value=process.env[name]?.trim();if(!value)throw new Error(`${name} is required`);return value;}
for(const signal of ["SIGINT","SIGTERM"] as const)process.on(signal,()=>server.close(()=>process.exit(0)));
