import{createHash}from"node:crypto";import{access,mkdir}from"node:fs/promises";import{join}from"node:path";import{spawn}from"node:child_process";import type{DiscoveredIssue,ExecutionResult,ExecutionUpdate,V2Ports}from"./supervisor.js";import type{V2Job}from"./state.js";
type Result={code:number;out:string;err:string};
export class GhV2Ports implements V2Ports{
  private child:ReturnType<typeof spawn>|null=null;
  constructor(private repositories:string[],private workspaceRoot:string,private label="lcc:autonomous",private codexPath="/usr/local/bin/codex",private run=command){}
  processAlive(pid:number){try{process.kill(pid,0);return true}catch{return false}}
  stop(){this.child?.kill("SIGTERM")}
  async discover(){const result:DiscoveredIssue[]=[];for(const repository of this.repositories){if(!/^knys\/[\w.-]+$/.test(repository))throw Error("repository not allowlisted");const r=await this.run("/usr/bin/gh",["issue","list","--repo",repository,"--state","open","--label",this.label,"--limit","100","--json","id,number,title,url,updatedAt,labels"],process.cwd());if(r.code)throw Error(`GitHub discovery failed: ${safe(r.err)}`);for(const x of JSON.parse(r.out)as any[]){const labels=(x.labels??[]).map((v:any)=>String(v.name));result.push({issueId:String(x.id),repository,number:Number(x.number),url:String(x.url),title:String(x.title),revision:createHash("sha256").update(`${x.id}\0${x.updatedAt}\0${labels.sort().join(",")}`).digest("hex"),closed:false,labels})}}return result}
  async execute(job:V2Job,update:(value:ExecutionUpdate)=>Promise<void>):Promise<ExecutionResult>{
    const cwd=join(this.workspaceRoot,job.jobId);await mkdir(this.workspaceRoot,{recursive:true});try{await access(join(cwd,".git"))}catch{const clone=await this.run("/usr/bin/git",["clone","--",`https://github.com/${job.repository}.git`,cwd],this.workspaceRoot);if(clone.code)return fail("clone failed",true)}
    const clean=await this.run("/usr/bin/git",["status","--porcelain"],cwd);if(clean.code||clean.out.trim())return fail("dedicated workspace is not clean",false);
    for(const args of [["fetch","origin","main"],["switch","--detach","origin/main"]]){const value=await this.run("/usr/bin/git",args,cwd);if(value.code)return fail("base synchronization failed",true)}
    const base=(await this.run("/usr/bin/git",["rev-parse","HEAD"],cwd)).out.trim(),branch=branchName(job);const switched=await this.run("/usr/bin/git",["switch","-c",branch],cwd);if(switched.code)return fail("branch creation failed",true);
    const prompt=`Implement GitHub Issue ${job.issueUrl} in repository ${job.repository}. Read the Issue as the SSOT. Work only within its bounded scope. Run relevant tests and commit all intended changes on the current branch. Do not push, merge, deploy, close Issues, expose credentials, modify unrelated work, or ask a human to run commands. Finish only with a clean committed worktree.`;
    const codex=spawn(this.codexPath,["exec","--approve-for-me",prompt],{cwd,stdio:"ignore",shell:false,env:{...process.env,HOME:process.env.HOME??"/home/user"}});this.child=codex;if(!codex.pid){this.child=null;return fail("Codex process did not start",true)}const pid=codex.pid;await update({state:"ACTIVE",pid,action:"Codex implementing Issue",nextAction:"Independent verification",heartbeatAt:new Date().toISOString(),branch});const timer=setInterval(()=>void update({state:"ACTIVE",pid,action:"Codex implementing Issue",nextAction:"Independent verification",heartbeatAt:new Date().toISOString(),branch}).catch(()=>undefined),20_000);const exit=await new Promise<number>(resolve=>{codex.once("exit",c=>resolve(c??1));codex.once("error",()=>resolve(1))});clearInterval(timer);this.child=null;if(exit)return fail(`Codex exited ${exit}`,true,{branch});
    const status=await this.run("/usr/bin/git",["status","--porcelain"],cwd),head=(await this.run("/usr/bin/git",["rev-parse","HEAD"],cwd)).out.trim();if(status.code||status.out.trim()||!head||head===base)return fail("Codex did not leave a clean non-empty commit",true,{branch});await update({state:"VERIFYING",action:"Running independent fixed checks",nextAction:"Create PR and wait for CI",branch,commitSha:head});
    const files=await this.run("/usr/bin/git",["diff","--name-only",`${base}..${head}`],cwd);if(files.code||!files.out.trim())return fail("candidate diff unavailable",false,{branch,commitSha:head});for(const [file,args]of [["/usr/bin/npm",["test"]],["/usr/bin/npm",["run","typecheck"]],["/usr/bin/npm",["run","build"]],["/usr/bin/git",["diff","--check",`${base}..${head}`]]]as [string,string[]][]){const check=await this.run(file,args,cwd);if(check.code)return fail(`verification failed: ${file} ${args.join(" ")}`,true,{branch,commitSha:head})}
    const push=await this.run("/usr/bin/git",["push","-u","origin",branch],cwd);if(push.code)return fail("push failed",true,{branch,commitSha:head});const created=await this.run("/usr/bin/gh",["pr","create","--repo",job.repository,"--base","main","--head",branch,"--title",`Issue #${job.issueNumber}: autonomous implementation`,`--body`,`Closes #${job.issueNumber}\n\nExecuted by LCC v2 job ${job.jobId}.`],cwd);if(created.code)return fail("PR creation failed",true,{branch,commitSha:head});const prUrl=created.out.trim().split(/\s/).find(v=>v.startsWith("https://"))??created.out.trim(),prNumber=Number(prUrl.split("/").at(-1));await update({state:"MERGING",action:"Waiting for CI and merging",nextAction:"Confirm main and close Issue",branch,commitSha:head,prNumber,prUrl,ciStatus:"PENDING"});
    let checks:Result|null=null;for(let i=0;i<12;i++){checks=await this.run("/usr/bin/gh",["pr","checks",String(prNumber),"--repo",job.repository,"--watch","--interval","10"],cwd);if(!/no checks reported/i.test(checks.err+checks.out))break;await new Promise(resolve=>setTimeout(resolve,5_000))}if(!checks||checks.code||/no checks reported/i.test(checks.err+checks.out))return fail("CI checks absent or failed",true,{branch,commitSha:head,prNumber,prUrl,ciStatus:"FAIL"});const merge=await this.run("/usr/bin/gh",["pr","merge",String(prNumber),"--repo",job.repository,"--merge","--delete-branch"],cwd);if(merge.code)return fail("main merge failed",true,{branch,commitSha:head,prNumber,prUrl,ciStatus:"PASS"});const view=await this.run("/usr/bin/gh",["pr","view",String(prNumber),"--repo",job.repository,"--json","mergeCommit,state"],cwd);if(view.code)return fail("merged PR confirmation failed",true,{branch,commitSha:head,prNumber,prUrl,ciStatus:"PASS"});const data=JSON.parse(view.out),mainSha=String(data.mergeCommit?.oid??"");if(data.state!=="MERGED"||!mainSha)return fail("PR is not merged",true,{branch,commitSha:head,prNumber,prUrl,ciStatus:"PASS"});return{ok:true,retryable:false,branch,commitSha:head,prNumber,prUrl,ciStatus:"PASS",mainSha}
  }
  async closeIssue(job:V2Job){await this.run("/usr/bin/gh",["issue","comment",String(job.issueNumber),"--repo",job.repository,"--body",`LCC v2 completed ${job.jobId}; PR ${job.prUrl}; CI PASS; main ${job.mainSha}.`],process.cwd());await this.run("/usr/bin/gh",["issue","close",String(job.issueNumber),"--repo",job.repository,"--reason","completed"],process.cwd())}
}
export function branchName(job:Pick<V2Job,"issueNumber"|"jobId"|"retryCount">){return`lcc/v2/${job.issueNumber}-${job.jobId.slice(-8)}-r${job.retryCount}`}
function fail(failure:string,retryable:boolean,extra:Partial<ExecutionResult>={}):ExecutionResult{return{ok:false,retryable,failure,...extra}}
function safe(value:string){return value.replace(/gh[opsu]_[A-Za-z0-9_]+/g,"<redacted>").slice(-500)}
function command(file:string,args:string[],cwd:string):Promise<Result>{return new Promise(resolve=>{const child=spawn(file,args,{cwd,stdio:["ignore","pipe","pipe"],shell:false});let out="",err="";child.stdout.on("data",v=>{out+=String(v);if(out.length>2_000_000)child.kill()});child.stderr.on("data",v=>{err+=String(v);if(err.length>100_000)err=err.slice(-100_000)});child.once("error",e=>resolve({code:1,out,err:e.message}));child.once("exit",c=>resolve({code:c??1,out,err}))})}
