import{randomUUID}from"node:crypto";import{newJob,transition,type JobState,type V2Job}from"./state.js";import{V2Store}from"./store.js";
export interface DiscoveredIssue{issueId:string;repository:string;product?:string;number:number;url:string;title:string;body?:string;revision:string;closed:boolean;labels:string[];hasOpenPullRequest?:boolean;workerAvailable?:boolean;worker?:string}
export interface ExecutionUpdate{state:"ACTIVE"|"VERIFYING"|"MERGING";pid?:number;action:string;nextAction:string|null;heartbeatAt?:string;branch?:string;commitSha?:string;prNumber?:number;prUrl?:string;ciStatus?:V2Job["ciStatus"]}
export interface ExecutionResult{ok:boolean;retryable:boolean;failure?:string;branch?:string;commitSha?:string;prNumber?:number;prUrl?:string;ciStatus?:V2Job["ciStatus"];mainSha?:string}
export interface V2Ports{discover():Promise<DiscoveredIssue[]>;execute(job:V2Job,update:(value:ExecutionUpdate)=>Promise<void>):Promise<ExecutionResult>;closeIssue(job:V2Job):Promise<void>;processAlive(pid:number):boolean;stop?():void}
export class V2Supervisor{
  private running=false;private inflight:Promise<void>|null=null;
  constructor(readonly store:V2Store,private ports:V2Ports,private now:()=>number=Date.now,private leaseMs=120_000){}
  async tick(){if(this.running)return;this.running=true;try{await this.heartbeat();await this.reconcile();await this.discover();await this.promoteDiscovered();const snapshot=await this.store.read();if(!snapshot.automationEnabled)return;const busy=new Set(snapshot.jobs.filter(j=>["LEASED","ACTIVE","VERIFYING","MERGING"].includes(j.state)).map(j=>j.repository));const queued=snapshot.jobs.filter(j=>j.state==="QUEUED"&&!busy.has(j.repository)).sort((a,b)=>a.discoveredAt.localeCompare(b.discoveredAt))[0];if(queued)this.inflight=this.dispatch(queued).finally(()=>{this.inflight=null})}finally{this.running=false}}
  async drain(){await this.inflight}
  private async heartbeat(){await this.store.update(s=>{s.heartbeatAt=new Date(this.now()).toISOString()})}
  private async discover(){const issues=await this.ports.discover();await this.store.update(s=>{for(const issue of issues){const existing=s.jobs.find(j=>j.issueId===issue.issueId);if(issue.closed){if(existing&&existing.state!=="COMPLETED")existing.failure="Issue closed externally";continue}if(!existing){let job=newJob({issueId:issue.issueId,repository:issue.repository,product:issue.product,issueNumber:issue.number,issueUrl:issue.url,title:issue.title,sourceRevision:issue.revision},new Date(this.now()).toISOString());const reason=eligibilityFailure(issue);if(reason)job=transition(job,"BLOCKED",reason,{failure:reason,currentAction:reason,nextAction:issue.workerAvailable?null:`Wait for ${issue.worker}`},new Date(this.now()).toISOString());s.jobs.push(job)}}})}
  private async promoteDiscovered(){await this.store.update(s=>{for(let i=0;i<s.jobs.length;i++){let j=s.jobs[i]!;if(j.state==="DISCOVERED")j=transition(j,"ELIGIBLE","Issue is complete, safe, unclaimed, and worker-ready",{currentAction:"Eligibility confirmed",nextAction:"Enter durable queue"},new Date(this.now()).toISOString());if(j.state==="ELIGIBLE")j=transition(j,"QUEUED","Execution slot requested",{currentAction:"Waiting for execution slot",nextAction:"Acquire repository lease"},new Date(this.now()).toISOString());s.jobs[i]=j}})}
  private async reconcile(){await this.store.update(s=>{for(let i=0;i<s.jobs.length;i++){const j=s.jobs[i]!;if(!["LEASED","ACTIVE","VERIFYING","MERGING"].includes(j.state))continue;const expired=!j.leaseExpiresAt||Date.parse(j.leaseExpiresAt)<=this.now(),missing=j.state==="ACTIVE"&&(!j.pid||!this.ports.processAlive(j.pid));if(!expired&&!missing)continue;const failure=missing?"Codex process disappeared":"Lease/heartbeat expired";s.jobs[i]=j.retryCount<j.retryLimit?transition(j,"FAILED_RETRYABLE",failure,{pid:null,heartbeatAt:null,leaseId:null,leaseExpiresAt:null,failure,currentAction:failure,nextAction:"Retry with bounded budget"},new Date(this.now()).toISOString()):transition(j,"FAILED_FINAL","Retry budget exhausted",{pid:null,heartbeatAt:null,leaseId:null,leaseExpiresAt:null,failure,currentAction:"Failed permanently",nextAction:null},new Date(this.now()).toISOString())}for(let i=0;i<s.jobs.length;i++){const j=s.jobs[i]!;if(j.state==="FAILED_RETRYABLE")s.jobs[i]=transition(j,"QUEUED","Bounded retry queued",{retryCount:j.retryCount+1,failure:j.failure,currentAction:"Waiting to retry",nextAction:"Acquire lease"},new Date(this.now()).toISOString())}})}
  private async dispatch(original:V2Job){const leaseId=`lease-${randomUUID()}`,at=new Date(this.now()).toISOString(),expires=new Date(this.now()+this.leaseMs).toISOString();let job=await this.store.update(s=>{const i=s.jobs.findIndex(j=>j.jobId===original.jobId);if(i<0||s.jobs[i]!.state!=="QUEUED")throw Error("job no longer queued");s.jobs[i]=transition(s.jobs[i]!,"LEASED","Exclusive Issue lease acquired",{leaseId,leaseExpiresAt:expires,currentAction:"Lease acquired",nextAction:"Start Codex"},at);return s.jobs[i]!});
    const update=async(u:ExecutionUpdate)=>{job=await this.store.update(s=>{const i=s.jobs.findIndex(j=>j.jobId===job.jobId),current=s.jobs[i]!;const patch={pid:u.pid??current.pid,heartbeatAt:u.heartbeatAt??new Date(this.now()).toISOString(),leaseExpiresAt:new Date(this.now()+this.leaseMs).toISOString(),currentAction:u.action,nextAction:u.nextAction,branch:u.branch??current.branch,commitSha:u.commitSha??current.commitSha,prNumber:u.prNumber??current.prNumber,prUrl:u.prUrl??current.prUrl,ciStatus:u.ciStatus??current.ciStatus};s.jobs[i]=current.state===u.state?{...current,...patch,updatedAt:new Date(this.now()).toISOString()}:transition(current,u.state,u.action,patch,new Date(this.now()).toISOString());return s.jobs[i]!})};
    try{const result=await this.ports.execute(job,update);job=await this.store.update(s=>{const i=s.jobs.findIndex(j=>j.jobId===job.jobId),current=s.jobs[i]!,patch={pid:null,heartbeatAt:null,leaseId:null,leaseExpiresAt:null,branch:result.branch??current.branch,commitSha:result.commitSha??current.commitSha,prNumber:result.prNumber??current.prNumber,prUrl:result.prUrl??current.prUrl,ciStatus:result.ciStatus??current.ciStatus,mainSha:result.mainSha??current.mainSha};if(result.ok){if(current.state!=="MERGING")throw Error("successful worker must reach MERGING");s.jobs[i]=transition(current,"COMPLETED","PR merged to main and Issue completed",{...patch,currentAction:"Completed",nextAction:null,failure:null},new Date(this.now()).toISOString())}else{const retryable=result.retryable&&current.retryCount<current.retryLimit;s.jobs[i]=transition(current,retryable?"FAILED_RETRYABLE":"FAILED_FINAL",result.failure??"Execution failed",{...patch,currentAction:"Execution failed",nextAction:retryable?"Retry":null,failure:result.failure??"Execution failed"},new Date(this.now()).toISOString())}return s.jobs[i]!});if(result.ok)await this.ports.closeIssue(job)}catch(e){await this.store.update(s=>{const i=s.jobs.findIndex(j=>j.jobId===job.jobId),current=s.jobs[i]!;if(["COMPLETED","FAILED_FINAL"].includes(current.state))return;const retryable=current.retryCount<current.retryLimit;s.jobs[i]=transition(current,retryable?"FAILED_RETRYABLE":"FAILED_FINAL","Supervisor caught executor failure",{pid:null,heartbeatAt:null,leaseId:null,leaseExpiresAt:null,failure:String(e).slice(0,500),currentAction:"Executor failure",nextAction:retryable?"Retry":null},new Date(this.now()).toISOString())})}}
}
function eligibilityFailure(issue:DiscoveredIssue){if(issue.hasOpenPullRequest)return"An open pull request already addresses this Issue";if(issue.workerAvailable===false)return`Required worker ${issue.worker} is offline`;const text=`${issue.title}\n${issue.body??"Acceptance: test fixture"}`;if(!/(acceptance|完了条件|受入条件|expected|期待)/i.test(text))return"Issue lacks readable Acceptance criteria";if(/(password|credential|secret|秘密情報|不可逆|delete production)/i.test(text))return"Issue requires secrets or an irreversible operation";return null}
