type Capacity={usedBytes:number|null;totalBytes:number|null;usedPercent:number|null};
type Device={id:string;name:string;hostname:string|null;status:"ONLINE"|"WARNING"|"OFFLINE";os:string|null;cpuUsagePercent:number|null;cpuTemperatureC:number|null;memory:Capacity;filesystem:Capacity;ipv4:string|null;uptimeSeconds:number|null;lastSeen:string|null};
type ProductState="RUNNING"|"QUEUED"|"READY"|"WAITING"|"BLOCKED"|"ACCEPTANCE"|"DONE"|"UNKNOWN";
type Product={id:string;name:string;summary:string;status:ProductState;ball:string;nextAction:string;nextActionJa:string;issueNumber:number|null;issueTitle:string|null;issueUrl:string|null;relatedIssues:{number:number;url:string;title:string;state:string}[];relatedPullRequests:{number:number;url:string}[];humanActionJa:string|null;humanSource:{repository:string;issueNumber:number;revision:string}|null;repository:string|null;repositoryUrl:string|null;defaultBranch:string|null;headSha:string|null;openIssues:number|null;openPullRequests:number|null;updatedAt:string|null;source:string;stale:boolean;syncWarning:string|null;activeActor:string|null;queuedActor:string|null;currentRun:string|null;executionId:string|null;baseSha:string|null;candidateSha:string|null;deployedSha:string|null;blocker:string|null;humanGate:string|null;failureSummary:string|null;latestVerificationSummary:string|null;latestGitHubEvidence:string|null};
type CommissionCandidate={id:string;title:string;product:string;source:string;sourceRef:string;repository:string;issueNumber:number|null;issueUrl:string|null;commissionState:string;suggestedNextActionJa:string;whyNotCommissioned:string|null;humanActionJa:string|null;runId:string|null};
const el=(id:string)=>document.getElementById(id)!;
const set=(id:string,value:string)=>{el(id).textContent=value};
const gb=(bytes:number|null)=>bytes===null?"--":`${(bytes/1073741824).toFixed(1)}G`;
const percent=(value:number|null)=>value===null?"--%":`${value.toFixed(1)}%`;
const temp=(value:number|null)=>value===null?"--°C":`${value.toFixed(1)}°C`;
const duration=(seconds:number|null)=>{if(seconds===null)return "--";const d=Math.floor(seconds/86400),h=Math.floor(seconds%86400/3600),m=Math.floor(seconds%3600/60);return `${d}d ${h}h ${m}m`};
const age=(timestamp:string|null)=>{if(!timestamp)return "NEVER";const seconds=Math.max(0,Math.floor((Date.now()-Date.parse(timestamp))/1000));return seconds<5?"NOW":seconds<60?`${seconds}s AGO`:`${Math.floor(seconds/60)}m AGO`};
const safe=(value:string|null)=>value??"UNAVAILABLE";
const html=(value:string|null)=>safe(value).replace(/[&<>"']/g,(character)=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[character]!));
const capacity=(value:Capacity)=>`<b>${percent(value.usedPercent)}</b><small>${gb(value.usedBytes)} / ${gb(value.totalBytes)}</small>`;
const deviceOrder=["gtx1060","tobie-box","tx66kwh"];
const deviceRow=(device:Device,smart:string|null)=>{const smartClass=smart===null?"unknown":smart==="PASSED"?"online":"error";return `<article class="device-row ${device.status.toLowerCase()}"><span class="device-identity"><b>${html(device.name)}</b><small>${html(device.os)}</small></span><strong class="device-status">${device.status}</strong><span>${html(device.ipv4)}</span><span>${percent(device.cpuUsagePercent)}</span><span>${temp(device.cpuTemperatureC)}</span><span class="capacity">${capacity(device.memory)}</span><span class="capacity">${capacity(device.filesystem)}${device.id==="tx66kwh"?`<small class="smart ${smartClass}">SMART ${html(smart)}</small>`:""}</span><span>${duration(device.uptimeSeconds)}</span><span>${age(device.lastSeen)}</span></article>`};
const productRow=(product:Product)=>{const repo=product.repositoryUrl?`<a href="${html(product.repositoryUrl)}" target="_blank" rel="noreferrer">${html(product.repository)}</a>`:`<span>${html(product.repository)}</span>`;const meta=product.repository?`${repo}<small>${product.headSha?.slice(0,7)??"NO DATA"} · I${product.openIssues??"-"} P${product.openPullRequests??"-"} · ${age(product.updatedAt)}${product.stale?" · STALE":""}</small>`:`<span>UNCONFIRMED</span><small>REPOSITORY EVIDENCE MISSING</small>`;const actor=product.activeActor??product.queuedActor??"NONE",run=product.currentRun?.slice(0,16)??(product.queuedActor?"QUEUED":"--"),gate=product.syncWarning??product.blocker??product.humanGate??"--",issue=product.issueNumber?(product.issueUrl?`<a href="${html(product.issueUrl)}" target="_blank" rel="noreferrer">#${product.issueNumber}</a>`:`#${product.issueNumber}`):"--",more=product.relatedIssues.length?` +${product.relatedIssues.length}`:"",issueTitle=[product.issueTitle,...product.relatedIssues.map(value=>`#${value.number} ${value.state}: ${value.title}`)].filter(Boolean).join("\n");return `<article class="product-row" data-product-id="${html(product.id)}" tabindex="0" role="button" aria-label="Open ${html(product.name)} details"><b class="product-name">${html(product.name)}</b><strong class="product-status ${product.status.toLowerCase()}">${product.status}</strong><span class="issue" title="${html(issueTitle)}">${issue}${html(more)}</span><strong class="ball ball-${product.ball.toLowerCase()}">${html(product.ball)}</strong><span class="actor"><b>${html(actor)}</b><small>${html(run)}</small></span><span class="next" title="${html(product.nextActionJa)}">${html(product.nextActionJa)}</span><span class="human-action" title="${html(product.humanActionJa??"--")}">${html(product.humanActionJa??"--")}</span><span class="gate" title="${html(gate)}">${html(gate)}</span><span class="repo">${meta}</span></article>`};

let productsById=new Map<string,Product>(),activeProductId:string|null=null,returnFocus:HTMLElement|null=null;
const field=(label:string,value:string|null,kind="")=>`<section class="detail-field ${kind}"><h3>${html(label)}</h3><p>${html(value??"--")}</p></section>`;
const linkField=(label:string,text:string|null,url:string|null)=>`<section class="detail-field"><h3>${html(label)}</h3><p>${url?`<a href="${html(url)}" target="_blank" rel="noreferrer">${html(text)}</a>`:html(text??"--")}</p></section>`;
function detailMarkup(product:Product){const issue=product.issueNumber?`#${product.issueNumber}${product.issueTitle?` — ${product.issueTitle}`:""}`:null,issues=product.relatedIssues.map(value=>`<li><a href="${html(value.url)}" target="_blank" rel="noreferrer">#${value.number} — ${html(value.title)}</a> <small>${html(value.state)}</small></li>`),pulls=product.relatedPullRequests.map(value=>`<li><a href="${html(value.url)}" target="_blank" rel="noreferrer">PR #${value.number}</a></li>`),related=[...issues,...pulls].join("")||"<li>--</li>";return `<div class="detail-badges"><strong class="product-status ${product.status.toLowerCase()}">${html(product.status)}</strong><strong class="ball ball-${product.ball.toLowerCase()}">BALL ${html(product.ball)}</strong></div><div class="detail-grid">${linkField("REPOSITORY",product.repository,product.repositoryUrl)}${linkField("CURRENT ISSUE",issue,product.issueUrl)}${field("GITHUB UPDATED",product.updatedAt)}${field("ACTIVE ACTOR",product.activeActor,product.status==="RUNNING"?"emphasis-running":"")}${field("QUEUED ACTOR",product.queuedActor)}${field("CURRENT RUN",product.currentRun)}${field("EXECUTION ID",product.executionId)}${field("DEFAULT BRANCH / LATEST SHA",`${product.defaultBranch??"--"} / ${product.headSha??"--"}`)}${field("BASE SHA",product.baseSha)}${field("CANDIDATE SHA",product.candidateSha)}${field("DEPLOYED SHA",product.deployedSha)}</div>${field("NEXT ACTION",product.nextActionJa,"detail-wide")}${product.humanActionJa?field("HUMAN ACTION",product.humanActionJa,"detail-wide emphasis-human"):""}${product.humanGate?field("HUMAN GATE / WHY HUMAN?",product.humanGate,"detail-wide emphasis-human"):""}${product.syncWarning?field("SYNC WARNING",product.syncWarning,"detail-wide emphasis-blocked"):""}${product.blocker?field("EXACT BLOCKER",product.blocker,"detail-wide emphasis-blocked"):""}${product.failureSummary?field("FAILURE / RETRY SUMMARY",product.failureSummary,"detail-wide emphasis-blocked"):""}${product.latestVerificationSummary?field("LATEST VERIFICATION / EVIDENCE",product.latestVerificationSummary,"detail-wide"):""}<section class="detail-field detail-wide"><h3>RELATED WORK</h3><ul>${related}</ul></section>`}
function renderOpenProduct(){if(!activeProductId)return;const product=productsById.get(activeProductId);if(!product){closeProductModal();return}el("product-detail-title").textContent=product.name;el("product-detail-body").innerHTML=detailMarkup(product)}
function openProductModal(id:string,trigger:HTMLElement){if(!productsById.has(id))return;activeProductId=id;returnFocus=trigger;renderOpenProduct();const modal=el("product-modal");modal.hidden=false;document.body.classList.add("modal-open");el("product-modal-close").focus()}
function closeProductModal(){if(!activeProductId)return;activeProductId=null;el("product-modal").hidden=true;document.body.classList.remove("modal-open");returnFocus?.focus();returnFocus=null}
el("products").addEventListener("click",event=>{const target=event.target as HTMLElement;if(target.closest("a"))return;const row=target.closest<HTMLElement>("[data-product-id]");if(row)openProductModal(row.dataset.productId!,row)});
el("products").addEventListener("keydown",event=>{if(event.key!=="Enter"&&event.key!==" ")return;const row=(event.target as HTMLElement).closest<HTMLElement>("[data-product-id]");if(row){event.preventDefault();openProductModal(row.dataset.productId!,row)}});
el("product-modal-close").addEventListener("click",closeProductModal);el("product-modal").addEventListener("click",event=>{if((event.target as HTMLElement).hasAttribute("data-modal-close"))closeProductModal()});
document.addEventListener("keydown",event=>{if(!activeProductId)return;if(event.key==="Escape"){event.preventDefault();closeProductModal();return}if(event.key!=="Tab")return;const modal=el("product-modal"),focusable=[...modal.querySelectorAll<HTMLElement>('a[href],button:not([disabled]),[tabindex]:not([tabindex="-1"])')].filter(value=>!value.hidden);if(!focusable.length)return;const first=focusable[0]!,last=focusable.at(-1)!;if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()}});
async function refreshDevices(){try{const [response,system]=await Promise.all([fetch("/api/devices",{cache:"no-store"}),fetch("/api/system-status",{cache:"no-store"}).then(async result=>result.ok?await result.json() as {smart:{health:string}}:null).catch(()=>null)]);if(!response.ok)throw new Error();const data=await response.json() as {timestamp:string;devices:Device[]};const rank=(device:Device)=>{const index=deviceOrder.indexOf(device.id);return index<0?deviceOrder.length:index};const devices=[...data.devices].sort((a,b)=>rank(a)-rank(b));el("devices").innerHTML=devices.map(device=>deviceRow(device,system?.smart.health??null)).join("");const states=devices.map((item)=>item.status);const state=states.includes("OFFLINE")?"DEGRADED":states.includes("WARNING")?"WARNING":"ONLINE";const health=el("device-health");health.className=state==="ONLINE"?"online":"warning";health.textContent=state;set("devices-updated",`TELEMETRY ${new Date(data.timestamp).toLocaleTimeString()}`);set("updated",`DEVICE TELEMETRY ${new Date(data.timestamp).toLocaleTimeString()}`)}catch{const health=el("device-health");health.className="error";health.textContent="ERROR";set("devices-updated","TELEMETRY LOST");set("updated","DEVICE TELEMETRY LOST")}}
async function refreshProducts(){try{const response=await fetch("/api/products",{cache:"no-store"});if(!response.ok)throw new Error();const data=await response.json() as {timestamp:string;cacheUpdatedAt:string|null;stale:boolean;warning:string|null;products:Product[]};productsById=new Map(data.products.map(product=>[product.id,product]));el("products").innerHTML=data.products.map(productRow).join("");renderOpenProduct();const states=data.products.map((item)=>item.status);const workflow=el("workflow-health");const attention=states.some((state)=>["BLOCKED","WAITING","ACCEPTANCE","UNKNOWN"].includes(state));workflow.className=attention?"warning":"online";workflow.textContent=attention?"ATTENTION":"CLEAR";set("products-updated",data.stale?"GITHUB STALE // CACHE FALLBACK":`GITHUB ${data.cacheUpdatedAt?new Date(data.cacheUpdatedAt).toLocaleTimeString():"NO REPOSITORIES"}`)}catch{const workflow=el("workflow-health");workflow.className="error";workflow.textContent="UNKNOWN";set("products-updated","PRODUCT DATA LOST")}}
const commissionRow=(candidate:CommissionCandidate)=>{const issue=candidate.issueNumber?(candidate.issueUrl?`<a href="${html(candidate.issueUrl)}" target="_blank" rel="noreferrer">${html(candidate.repository)} #${candidate.issueNumber}</a>`:`${html(candidate.repository)} #${candidate.issueNumber}`):html(candidate.repository);const reason=[candidate.whyNotCommissioned,candidate.humanActionJa].filter(Boolean).join(" // ")||"--";return `<article class="commission-row"><span><b>${html(candidate.title)}</b><small>${html(candidate.product)}</small></span><span>${issue}<small>${html(candidate.source)}</small></span><strong class="commission-state state-${html(candidate.commissionState.toLowerCase())}">${html(candidate.commissionState)}</strong><span title="${html(candidate.suggestedNextActionJa)}">${html(candidate.suggestedNextActionJa)}</span><span title="${html(reason)}">${html(reason)}</span></article>`};
async function refreshCommission(){try{const [watcher,inbox]=await Promise.all([fetch("/api/commission-watcher",{cache:"no-store"}).then(r=>r.json()),fetch("/api/commissions",{cache:"no-store"}).then(r=>r.json())]) as [{state:string;queuedCount?:number;activeCount?:number},{candidates:CommissionCandidate[]}];set("watcher-state",`WATCHER ${watcher.state} Q${watcher.queuedCount??0} A${watcher.activeCount??0}`);set("commission-count",`INBOX ${inbox.candidates.length}`);el("commissions").innerHTML=inbox.candidates.map(commissionRow).join("")}catch{set("watcher-state","WATCHER DEGRADED");set("commission-count","INBOX UNAVAILABLE")}}
setInterval(()=>set("clock",`${new Date().toLocaleTimeString("en-GB",{timeZone:"Asia/Tokyo"})} JST`),1000);refreshDevices();refreshProducts();refreshCommission();setInterval(()=>{refreshDevices();refreshProducts();refreshCommission()},5000);
