type Capacity={usedBytes:number|null;totalBytes:number|null;usedPercent:number|null};
type Device={id:string;name:string;hostname:string|null;status:"ONLINE"|"WARNING"|"OFFLINE";os:string|null;cpuUsagePercent:number|null;cpuTemperatureC:number|null;memory:Capacity;filesystem:Capacity;ipv4:string|null;uptimeSeconds:number|null;lastSeen:string|null};
type ProductState="RUNNING"|"READY"|"WAITING"|"BLOCKED"|"ACCEPTANCE"|"DONE"|"UNKNOWN";
type Product={id:string;name:string;summary:string;status:ProductState;ball:string;nextAction:string;repository:string|null;repositoryUrl:string|null;defaultBranch:string|null;headSha:string|null;openIssues:number|null;openPullRequests:number|null;updatedAt:string|null;source:string;stale:boolean};
const el=(id:string)=>document.getElementById(id)!;
const set=(id:string,value:string)=>{el(id).textContent=value};
const gb=(bytes:number|null)=>bytes===null?"--":`${(bytes/1073741824).toFixed(1)}G`;
const percent=(value:number|null)=>value===null?"--%":`${value.toFixed(1)}%`;
const temp=(value:number|null)=>value===null?"--°C":`${value.toFixed(1)}°C`;
const duration=(seconds:number|null)=>{if(seconds===null)return "--";const d=Math.floor(seconds/86400),h=Math.floor(seconds%86400/3600),m=Math.floor(seconds%3600/60);return `${d}d ${h}h ${m}m`};
const age=(timestamp:string|null)=>{if(!timestamp)return "NEVER";const seconds=Math.max(0,Math.floor((Date.now()-Date.parse(timestamp))/1000));return seconds<5?"NOW":seconds<60?`${seconds}s AGO`:`${Math.floor(seconds/60)}m AGO`};
const safe=(value:string|null)=>value??"UNAVAILABLE";
const html=(value:string|null)=>safe(value).replace(/[&<>"']/g,(character)=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[character]!));
const capacity=(value:Capacity)=>`<b>${percent(value.usedPercent)}</b><small>${gb(value.usedBytes)} / ${gb(value.totalBytes)}</small>`;
const deviceOrder=["gtx1060","tobie-box","tx66kwh"];
const deviceRow=(device:Device,smart:string|null)=>{const smartClass=smart===null?"unknown":smart==="PASSED"?"online":"error";return `<article class="device-row ${device.status.toLowerCase()}"><span class="device-identity"><b>${html(device.name)}</b><small>${html(device.os)}</small></span><strong class="device-status">${device.status}</strong><span>${html(device.ipv4)}</span><span>${percent(device.cpuUsagePercent)}</span><span>${temp(device.cpuTemperatureC)}</span><span class="capacity">${capacity(device.memory)}</span><span class="capacity">${capacity(device.filesystem)}${device.id==="tx66kwh"?`<small class="smart ${smartClass}">SMART ${html(smart)}</small>`:""}</span><span>${duration(device.uptimeSeconds)}</span><span>${age(device.lastSeen)}</span></article>`};
const productRow=(product:Product)=>{const repo=product.repositoryUrl?`<a href="${html(product.repositoryUrl)}" target="_blank" rel="noreferrer">${html(product.repository)}</a>`:`<span>${html(product.repository)}</span>`;const meta=product.repository?`${repo}<small>${product.headSha?.slice(0,7)??"NO DATA"} · I${product.openIssues??"-"} P${product.openPullRequests??"-"} · ${age(product.updatedAt)}${product.stale?" · STALE":""}</small>`:`<span>UNCONFIRMED</span><small>MANIFEST REVIEW REQUIRED</small>`;return `<article class="product-row"><b class="product-name">${html(product.name)}</b><strong class="product-status ${product.status.toLowerCase()}">${product.status}</strong><strong class="ball ball-${product.ball.toLowerCase()}">${html(product.ball)}</strong><span class="summary">${html(product.summary)}</span><span class="next">${html(product.nextAction)}</span><span class="repo">${meta}</span></article>`};
async function refreshDevices(){try{const [response,system]=await Promise.all([fetch("/api/devices",{cache:"no-store"}),fetch("/api/system-status",{cache:"no-store"}).then(async result=>result.ok?await result.json() as {smart:{health:string}}:null).catch(()=>null)]);if(!response.ok)throw new Error();const data=await response.json() as {timestamp:string;devices:Device[]};const rank=(device:Device)=>{const index=deviceOrder.indexOf(device.id);return index<0?deviceOrder.length:index};const devices=[...data.devices].sort((a,b)=>rank(a)-rank(b));el("devices").innerHTML=devices.map(device=>deviceRow(device,system?.smart.health??null)).join("");const states=devices.map((item)=>item.status);const state=states.includes("OFFLINE")?"DEGRADED":states.includes("WARNING")?"WARNING":"ONLINE";const health=el("device-health");health.className=state==="ONLINE"?"online":"warning";health.textContent=state;set("devices-updated",`TELEMETRY ${new Date(data.timestamp).toLocaleTimeString()}`);set("updated",`DEVICE TELEMETRY ${new Date(data.timestamp).toLocaleTimeString()}`)}catch{const health=el("device-health");health.className="error";health.textContent="ERROR";set("devices-updated","TELEMETRY LOST");set("updated","DEVICE TELEMETRY LOST")}}
async function refreshProducts(){try{const response=await fetch("/api/products",{cache:"no-store"});if(!response.ok)throw new Error();const data=await response.json() as {timestamp:string;cacheUpdatedAt:string|null;stale:boolean;warning:string|null;products:Product[]};el("products").innerHTML=data.products.map(productRow).join("");const states=data.products.map((item)=>item.status);const workflow=el("workflow-health");const attention=states.some((state)=>["BLOCKED","WAITING","ACCEPTANCE","UNKNOWN"].includes(state));workflow.className=attention?"warning":"online";workflow.textContent=attention?"ATTENTION":"CLEAR";set("products-updated",data.stale?"GITHUB STALE // CACHE FALLBACK":`GITHUB ${data.cacheUpdatedAt?new Date(data.cacheUpdatedAt).toLocaleTimeString():"NO REPOSITORIES"}`)}catch{const workflow=el("workflow-health");workflow.className="error";workflow.textContent="UNKNOWN";set("products-updated","PRODUCT DATA LOST")}}
setInterval(()=>set("clock",`${new Date().toLocaleTimeString("en-GB",{timeZone:"Asia/Tokyo"})} JST`),1000);refreshDevices();refreshProducts();setInterval(()=>{refreshDevices();refreshProducts()},5000);
