type Level = "online"|"warning"|"error"|"unknown";
const el=(id:string)=>document.getElementById(id)!;
const set=(id:string,value:string)=>{el(id).textContent=value};
const gb=(bytes:number)=>`${(bytes/1073741824).toFixed(1)} GiB`;
const level=(id:string,value:Level)=>{const node=el(id);node.className=value;node.textContent=value.toUpperCase()};
const bar=(id:string,value:number|null,status:Level)=>{const node=el(id) as HTMLElement;node.style.width=`${value??0}%`;node.style.background=status==="error"?"var(--red)":status==="warning"?"var(--amber)":"var(--cyan)"};
const duration=(seconds:number)=>{const d=Math.floor(seconds/86400),h=Math.floor(seconds%86400/3600),m=Math.floor(seconds%3600/60);return `${d}d ${h}h ${m}m`};
async function refresh(){try{const response=await fetch("/api/system-status",{cache:"no-store"});if(!response.ok)throw new Error();const s=await response.json();set("hostname",s.host.hostname);set("os",s.host.os);set("kernel",s.host.kernel);set("uptime",duration(s.host.uptimeSeconds));set("cpu-model",s.cpu.model);set("cpu-usage",s.cpu.usagePercent===null?"--%":`${s.cpu.usagePercent}%`);level("cpu-state",s.cpu.usageStatus);bar("cpu-bar",s.cpu.usagePercent,s.cpu.usageStatus);s.cpu.cores.forEach((c:any,i:number)=>set(`core${i}`,c.temperatureC===null?"--°C":`${c.temperatureC.toFixed(1)}°C`));set("memory-percent",`${s.memory.usedPercent}%`);set("memory-capacity",`${gb(s.memory.usedBytes)} USED / ${gb(s.memory.totalBytes)} TOTAL`);level("memory-state",s.memory.status);bar("memory-bar",s.memory.usedPercent,s.memory.status);set("disk-percent",`${s.filesystem.usedPercent}%`);set("disk-capacity",`${gb(s.filesystem.usedBytes)} USED / ${gb(s.filesystem.totalBytes)} TOTAL`);level("disk-state",s.filesystem.status);bar("disk-bar",s.filesystem.usedPercent,s.filesystem.status);set("interface",s.network.interface??"UNAVAILABLE");set("ipv4",s.network.ipv4??"UNAVAILABLE");set("ssh",s.services.ssh===null?"UNKNOWN":s.services.ssh?"ACTIVE":"INACTIVE");set("smart-health",s.smart.health);set("hdd-temp",s.smart.temperatureC===null?"--°C":`${s.smart.temperatureC}°C`);const smartLevel:Level=!s.smart.available?"unknown":s.smart.health==="PASSED"?"online":"error";level("smart-state",smartLevel);set("smart-note",s.smart.available?"Fixed privileged sensor link active":"Privileged sensor link unavailable");set("updated",`TELEMETRY ${new Date(s.timestamp).toLocaleTimeString()}`);el("master").className="master online"}catch{el("master").className="master error";el("master").querySelector("strong")!.textContent="ERROR";set("updated","TELEMETRY LINK LOST")}}
setInterval(()=>set("clock",`${new Date().toLocaleTimeString("en-GB",{timeZone:"Asia/Tokyo"})} JST`),1000);refresh();setInterval(refresh,5000);
