import { mkdir,readFile,rename,writeFile } from "node:fs/promises";
import { dirname,join } from "node:path";
import { CommissionInbox,type WatcherStatus } from "./commission-inbox.js";
import { BoundedLocalCodexExecutor,DurableCommissionRunRegistrar,commissionExecutors } from "./commission-runs.js";
import { DurableSelfCommissioningStore,SelfCommissioningOrchestrator } from "./self-commissioning.js";
import { PersistentCodexDispatcher } from "./persistent-codex-dispatcher.js";
import { InterruptibleWait } from "./interruptible-wait.js";
import { GhCommissionProvider,GitHubCommissionScanner } from "./github-commission.js";

const data=process.env.LCC_DATA_DIRECTORY??"/var/lib/luckountry-control-center",runsPath=process.env.COMMISSION_RUNS_PATH??join(data,"commission-runs.json"),inbox=new CommissionInbox(process.env.COMMISSION_INBOX_PATH??join(data,"commissions.json"),new DurableCommissionRunRegistrar(runsPath)),statusPath=process.env.COMMISSION_WATCHER_STATUS_PATH??join(data,"watcher.json"),pausePath=process.env.COMMISSION_WATCHER_PAUSE_PATH??join(data,"watcher.paused"),interval=Math.max(10_000,Number(process.env.COMMISSION_WATCHER_INTERVAL_MS??60_000)),executor=new BoundedLocalCodexExecutor(process.env.LCC_WORKSPACE_ROOT??"/home/user/.lcc-commission-watcher/workspaces"),scanner=new GitHubCommissionScanner(inbox,new GhCommissionProvider()),sleeper=new InterruptibleWait();
let stopping=false;const wait=(n:number)=>sleeper.wait(n);
async function save(x:Omit<WatcherStatus,"lastHeartbeat"|"heartbeatExpiresAt">){const now=Date.now(),status:WatcherStatus={...x,lastHeartbeat:new Date(now).toISOString(),heartbeatExpiresAt:new Date(now+Math.max(interval*2.5,30_000)).toISOString()};await mkdir(dirname(statusPath),{recursive:true});const tmp=`${statusPath}.${process.pid}.tmp`;await writeFile(tmp,JSON.stringify(status,null,2)+"\n");await rename(tmp,statusPath)}
async function paused(){try{await readFile(pausePath);return true}catch{return false}}
async function main(){let failures=0;while(!stopping){const now=new Date(),next=new Date(now.getTime()+interval).toISOString();try{
  await scanner.scan();
  const items=await inbox.list(),store=await DurableSelfCommissioningStore.open(runsPath),allRuns=await store.list();
  for(const item of items.filter(v=>v.commissionState==="COMMISSIONED"&&v.runId)){const run=allRuns.find(r=>r.runId===item.runId);if(run?.status==="SUCCEEDED")await inbox.patch(item.id,{commissionState:"COMPLETED",whyNotCommissioned:"完了済み（Persistent Dispatcher Run evidence retained）"})}
  const currentItems=await inbox.list(),waiting=allRuns.filter(v=>v.status==="WAITING_HUMAN").length,eligible=currentItems.filter(v=>v.commissionState==="COMMISSIONED"&&v.runId),queued=eligible.filter(v=>allRuns.some(r=>r.runId===v.runId&&r.status==="QUEUED")).filter(v=>v.dependsOn.every(id=>currentItems.some(dependency=>dependency.id===id&&dependency.commissionState==="COMPLETED")));
  if(await paused()||!(await store.enabled())){await save({state:"PAUSED",lastScan:now.toISOString(),nextScan:next,queuedCount:queued.length,activeCount:0,humanWaitingCount:waiting,currentWorkItem:null,currentActor:null,failure:null});failures=0;await wait(interval);continue}
  const item=queued.sort((a,b)=>b.priority-a.priority||a.detectedAt.localeCompare(b.detectedAt))[0];
  if(!item){await save({state:"WATCHING",lastScan:now.toISOString(),nextScan:next,queuedCount:0,activeCount:0,humanWaitingCount:waiting,currentWorkItem:null,currentActor:null,failure:null});failures=0;await wait(interval);continue}
  await save({state:"DISPATCHING",lastScan:now.toISOString(),nextScan:null,queuedCount:queued.length,activeCount:0,humanWaitingCount:waiting,currentWorkItem:item.id,currentActor:null,failure:null});
  const orchestrator=new SelfCommissioningOrchestrator(store,commissionExecutors(executor)),dispatcher=new PersistentCodexDispatcher(store,orchestrator,{report:async()=>undefined});dispatcher.start(item.runId!);for(let i=0;i<100;i++){const run=await store.get(item.runId!);if(run?.status==="RUNNING")break;await new Promise(r=>setImmediate(r))}
  const active=await store.get(item.runId!);await save({state:active?.status==="RUNNING"?"RUNNING":"DISPATCHING",lastScan:new Date().toISOString(),nextScan:null,queuedCount:Math.max(0,queued.length-1),activeCount:active?.status==="RUNNING"?1:0,humanWaitingCount:waiting,currentWorkItem:item.id,currentActor:active?.activeActor??null,failure:null});let drained=false;const draining=dispatcher.drain().finally(()=>{drained=true});while(!drained&&!stopping){await Promise.race([draining,new Promise(resolve=>setTimeout(resolve,Math.min(interval/2,30_000)))]);if(!drained&&!stopping){const running=await store.get(item.runId!);if(running?.status==="RUNNING")await save({state:"RUNNING",lastScan:new Date().toISOString(),nextScan:null,queuedCount:Math.max(0,queued.length-1),activeCount:1,humanWaitingCount:waiting,currentWorkItem:item.id,currentActor:running.activeActor??null,failure:null})}}await draining;failures=0;
}catch(e){failures++;const delay=Math.min(interval*2**failures,900_000);await save({state:"DEGRADED",lastScan:new Date().toISOString(),nextScan:new Date(Date.now()+delay).toISOString(),queuedCount:0,activeCount:0,humanWaitingCount:0,currentWorkItem:null,currentActor:null,failure:String(e).slice(0,500)});await wait(delay)}}}
function stop(){stopping=true;sleeper.cancel();executor.stop()}
process.on("SIGTERM",stop);process.on("SIGINT",stop);await main();
