import { spawn } from "node:child_process";
import { access, mkdir } from "node:fs/promises";
import { join } from "node:path";
import type { CommissionCandidate,CommissionRunRegistrar } from "./commission-inbox.js";
import { DurableSelfCommissioningStore,SelfCommissioningOrchestrator,type CodexJob,type CommissioningExecutors,type CommissioningResult } from "./self-commissioning.js";
export class DurableCommissionRunRegistrar implements CommissionRunRegistrar{constructor(private path:string){}async register(candidate:CommissionCandidate,runId:string){const store=await DurableSelfCommissioningStore.open(this.path);if(await store.get(runId))return;const unavailable=async():Promise<CommissioningResult>=>({status:"BLOCKED",summary:"Commission Run permits only bounded CODEX_JOB",evidence:[]}),orchestrator=new SelfCommissioningOrchestrator(store,{tx:unavailable,gtx:unavailable,codex:unavailable}),job:CodexJob={objective:`GitHub Issue #${candidate.issueNumber}「${candidate.title}」を実装・検証する`,repository:candidate.repository,workspaceId:workspaceId(candidate.repository),policy:{allowCommit:true,allowPush:false,allowMerge:false,allowDeploy:false}};await orchestrator.create({runId,objective:job.objective,steps:[{stepId:"codex-job",kind:"CODEX_JOB",job}],retryLimit:3})}async retainCompleted(candidate:CommissionCandidate,runId:string){await this.register(candidate,runId);const store=await DurableSelfCommissioningStore.open(this.path),value=await store.stored(runId);if(!value||value.run.status==="SUCCEEDED")return;const at=new Date().toISOString();await store.replace({...value,run:{...value.run,status:"SUCCEEDED",currentStep:null,activeActor:null,activeExecutionId:null,queuedActor:null,queuedStep:null,completedSteps:["codex-job"],updatedAt:at,history:[...value.run.history,{type:"MIGRATED_COMPLETION",at,summary:"Prior production completion retained in Dispatcher SSOT",evidence:[candidate.issueUrl??candidate.sourceRef]}]}})}}
export class BoundedLocalCodexExecutor{private child:ReturnType<typeof spawn>|null=null;constructor(private workspaceRoot:string,private codexPath="/usr/local/bin/codex"){}async execute(job:CodexJob):Promise<CommissioningResult>{const cwd=join(this.workspaceRoot,workspaceId(job.repository));await mkdir(this.workspaceRoot,{recursive:true});try{await access(join(cwd,".git"))}catch{if(await command("git",["clone","--",`https://github.com/${job.repository}.git`,cwd],this.workspaceRoot))return{status:"FAILED",summary:"Dedicated workspace clone failed",evidence:[],retryable:true}}const prompt=`Repository: ${job.repository}\n${job.objective}\nInspect actual durable state. Implement and test the bounded Issue. Commit is allowed. Push, merge, deploy, arbitrary privilege escalation, and work outside this repository are prohibited. Do not expose secrets or request Human command/log transport.`;return new Promise(resolve=>{const child=spawn(this.codexPath,["exec","--approve-for-me",prompt],{cwd,stdio:"inherit",shell:false});this.child=child;let settled=false;const done=(result:CommissioningResult)=>{if(settled)return;settled=true;this.child=null;resolve(result)};child.once("exit",code=>done(code===0?{status:"SUCCEEDED",summary:"Bounded CODEX_JOB completed",evidence:[]}:{status:"FAILED",summary:`Codex exited ${code??1}`,evidence:[],retryable:true}));child.once("error",error=>done({status:"FAILED",summary:error.message,evidence:[],retryable:true}))})}stop(){this.child?.kill("SIGTERM")}}
const command=(file:string,args:string[],cwd:string)=>new Promise<number>(resolve=>{const child=spawn(file,args,{cwd,stdio:"ignore",shell:false});child.once("exit",code=>resolve(code??1));child.once("error",()=>resolve(1))});
export const workspaceId=(repository:string)=>repository.replace(/[^A-Za-z0-9._-]/g,"-").slice(0,100);
export function commissionExecutors(codex:BoundedLocalCodexExecutor):CommissioningExecutors{const unavailable=async():Promise<CommissioningResult>=>({status:"BLOCKED",summary:"Unsupported Commission operation",evidence:[]});return{tx:unavailable,gtx:unavailable,codex:job=>codex.execute(job)}}
