import{mkdtemp,rm}from"node:fs/promises";import{join}from"node:path";import{tmpdir}from"node:os";import{PersistentCodexDispatcher}from"./persistent-codex-dispatcher.js";import{DurableSelfCommissioningStore,SelfCommissioningOrchestrator,type CodexJob,type CommissioningExecutors,type SelfCommissioningStep}from"./self-commissioning.js";
const job:CodexJob={objective:"Prove one-start persistent dispatch without Human transport",repository:"knys/luckountry-control-center",workspaceId:"lcc",policy:{allowCommit:true,allowPush:false,allowMerge:false,allowDeploy:false}};
const steps:SelfCommissioningStep[]=[{stepId:"whole-codex-job",kind:"CODEX_JOB",job},{stepId:"supervisor-checkpoint",kind:"SUPERVISOR_OPERATION",job:{...job,operation:"INSPECT_CURRENT_STATE"}},{stepId:"supervisor-evidence",kind:"SUPERVISOR_OPERATION",job:{...job,operation:"POST_ACCEPTANCE_OBSERVATION"}}];
const blocked=async()=>({status:"BLOCKED"as const,summary:"transport excluded from acceptance",evidence:[],blocker:"transport excluded from acceptance"});
export async function runPersistentDispatcherCanary(){const directory=await mkdtemp(join(tmpdir(),"lcc010-canary-"));try{
  const path=join(directory,"runs.json"),store=await DurableSelfCommissioningStore.open(path),calls:string[]=[],reports:string[]=[],executors:CommissioningExecutors={tx:blocked,gtx:blocked,codex:async(value,id)=>{calls.push(`${value.operation??"CODEX_JOB"}:${id}`);return{status:"SUCCEEDED",summary:"bounded step completed",evidence:["bounded"]}}},orchestrator=new SelfCommissioningOrchestrator(store,executors),dispatcher=new PersistentCodexDispatcher(store,orchestrator,{report:async run=>{reports.push(`${run.status}:${run.currentStep??"terminal"}`)}});
  await orchestrator.create({runId:"lcc010-three-step",objective:"Execute three consecutive allowlisted steps after one start",steps,retryLimit:1});dispatcher.start("lcc010-three-step");dispatcher.start("lcc010-three-step");await dispatcher.drain();const run=await store.get("lcc010-three-step");if(run?.status!=="SUCCEEDED"||run.completedSteps.length!==3||calls.length!==3||reports.length!==3)throw Error("three-step or duplicate-dispatch acceptance failed");
  let started=false;const restartPath=join(directory,"restart.json"),interruptedStore=await DurableSelfCommissioningStore.open(restartPath),interruptedOrchestrator=new SelfCommissioningOrchestrator(interruptedStore,{tx:blocked,gtx:blocked,codex:async()=>{started=true;await new Promise<void>(()=>undefined);return{status:"SUCCEEDED",summary:"unreachable",evidence:[]}}});await interruptedOrchestrator.create({runId:"restart",objective:"restart resume",steps:[steps[0]!],retryLimit:1});void interruptedOrchestrator.tick("restart");while(!started)await new Promise(resolve=>setImmediate(resolve));const reopened=await DurableSelfCommissioningStore.open(restartPath),resumedOrchestrator=new SelfCommissioningOrchestrator(reopened,{tx:blocked,gtx:blocked,codex:async()=>({status:"SUCCEEDED",summary:"resumed",evidence:[]})}),resumedDispatcher=new PersistentCodexDispatcher(reopened,resumedOrchestrator,{report:async()=>undefined});await resumedDispatcher.resume();await resumedDispatcher.drain();if((await reopened.get("restart"))?.status!=="SUCCEEDED")throw Error("restart resume acceptance failed");
  const killedStore=await DurableSelfCommissioningStore.open(join(directory,"kill.json"));let killedDispatches=0;const killedOrchestrator=new SelfCommissioningOrchestrator(killedStore,{tx:blocked,gtx:blocked,codex:async()=>{killedDispatches++;return{status:"SUCCEEDED",summary:"unsafe",evidence:[]}}}),killedDispatcher=new PersistentCodexDispatcher(killedStore,killedOrchestrator,{report:async()=>undefined});await killedOrchestrator.create({runId:"kill",objective:"kill switch",steps:[steps[0]!],retryLimit:1});await killedOrchestrator.setKillSwitch(false);killedDispatcher.start("kill");await killedDispatcher.drain();const killed=await killedStore.get("kill");if(killed?.status!=="BLOCKED"||killedDispatches!==0)throw Error("kill switch acceptance failed");
  return{status:"PASS"as const,runId:run.runId,completedSteps:run.completedSteps,dispatchCount:calls.length,humanCopyPasteCount:0,finalStatus:run.status,restartResult:"PASS"as const,duplicatePrevention:"PASS"as const,killSwitch:"PASS"as const}
}finally{await rm(directory,{recursive:true,force:true})}}
