import type{WorkItem}from"../domain/work-item.js";
import{parseAcceptanceCriteria}from"../domain/verification.js";
import{hasPilotLabels,matchesPilotScope,scopeFingerprint,type PilotControl,type PilotCycle,type PilotScope}from"../domain/pilot.js";
import{transitionWorkItem}from"../domain/work-state-machine.js";
import type{ExecutionState}from"./execution.js";
import type{VerificationState}from"../domain/verification.js";

export interface PilotWorkRepository{list(repository:string):Promise<WorkItem[]>;findWorkItem(id:string):Promise<WorkItem|null>;transitionExecutionState(id:string,update:(item:WorkItem)=>WorkItem):Promise<WorkItem>}
export interface PilotCycleRepository{pilotCycles():Promise<PilotCycle[]>;savePilotCycle(cycle:PilotCycle):Promise<void>}
export interface PilotReadinessContext{workerReady:boolean;workspaceReady:boolean;profileReady:boolean}

export async function scopedPilotItem(repository:PilotWorkRepository,scope:PilotScope):Promise<WorkItem|null>{const matches=(await repository.list(scope.repository)).filter(item=>matchesPilotScope(item,scope));return matches.length===1?matches[0]!:null;}
export function readinessReason(item:WorkItem|null,scope:PilotScope,context:PilotReadinessContext,now=Date.now()):string|null{if(!item||!matchesPilotScope(item,scope))return"exact scoped WorkItem not found";if(!hasPilotLabels(item,scope))return"required pilot labels are missing";if(!item.definitionReady)return"deterministic Definition gate is incomplete";if(!parseAcceptanceCriteria(item.acceptanceCriteria).valid)return"Acceptance Criteria are missing or malformed";if(Date.parse(scope.expiresAt)<=now)return"pilot scope is expired";if(!context.workerReady||!context.workspaceReady||!context.profileReady)return"worker, workspace, or verification profile is unavailable";return null;}
export class PilotReadinessService{constructor(private work:PilotWorkRepository,private cycles:PilotCycleRepository,private control:PilotControl,private context:PilotReadinessContext,private now:()=>number=Date.now){}async evaluate():Promise<{ready:boolean;reason:string;item:WorkItem|null;cycle:PilotCycle|null}>{const scope=this.control.scope;if(!this.control.enabled||!scope)return{ready:false,reason:this.control.reason,item:null,cycle:null};const item=await scopedPilotItem(this.work,scope),existing=(await this.cycles.pilotCycles()).find(cycle=>cycle.cycleId===scope.cycleId);if(existing){if(existing.scopeFingerprint!==scopeFingerprint(scope)||existing.workItemId!==item?.id)return{ready:false,reason:"active cycle scope cannot be retargeted",item,cycle:existing};return{ready:existing.status==="ARMED",reason:existing.reason,item,cycle:existing};}const blocker=readinessReason(item,scope,this.context,this.now());if(blocker||!item)return{ready:false,reason:blocker??"pilot readiness rejected",item,cycle:null};if(item.workState!=="DEFINED")return{ready:false,reason:"scoped WorkItem is not DEFINED",item,cycle:null};const updated=await this.work.transitionExecutionState(item.id,current=>transitionWorkItem(current,{type:"DEFINITION_COMPLETED",executor:"CODEX"}).workItem),timestamp=new Date(this.now()).toISOString(),cycle:PilotCycle={cycleId:scope.cycleId,scopeFingerprint:scopeFingerprint(scope),workItemId:updated.id,status:"ARMED",baseHead:null,candidateBranch:null,candidateHead:null,executionAttempts:0,verificationRuns:0,startedAt:timestamp,updatedAt:timestamp,reason:"Pilot readiness gate passed"};await this.cycles.savePilotCycle(cycle);return{ready:true,reason:cycle.reason,item:updated,cycle};}}
export function pilotExecutionCandidates(items:readonly WorkItem[],control:PilotControl,cycle:PilotCycle|null):string[]{const scope=control.scope;if(!control.enabled||!scope||!cycle||cycle.status!=="ARMED"||cycle.executionAttempts>=scope.maxExecutionAttempts)return[];return items.filter(item=>item.id===cycle.workItemId&&matchesPilotScope(item,scope)&&hasPilotLabels(item,scope)&&item.workState==="READY").map(item=>item.id).slice(0,1);}
export function pilotVerificationCandidates(items:readonly WorkItem[],control:PilotControl,cycle:PilotCycle|null):string[]{const scope=control.scope;if(!control.enabled||!scope||!cycle||cycle.status!=="VERIFYING"||cycle.verificationRuns>=scope.maxVerificationRuns)return[];return items.filter(item=>item.id===cycle.workItemId&&matchesPilotScope(item,scope)&&item.workState==="VERIFYING").map(item=>item.id).slice(0,1);}
export async function reconcilePilotCycle(repository:PilotCycleRepository,cycle:PilotCycle,item:WorkItem,execution:ExecutionState,verification:VerificationState,now=Date.now()):Promise<PilotCycle>{const records=execution.records.filter(value=>value.workItemId===cycle.workItemId),checks=verification.records.filter(value=>value.workItemId===cycle.workItemId),successful=[...records].reverse().find(value=>value.resultStatus==="SUCCEEDED"),status:PilotCycle["status"]=item.workState==="WAITING_HUMAN"?"WAITING_HUMAN":item.workState==="VERIFYING"?"VERIFYING":item.workState==="RUNNING"?"EXECUTING":item.workState==="FAILED"?"FAILED":cycle.status,next={...cycle,status,executionAttempts:records.length,verificationRuns:checks.length,baseHead:successful?.baseHead??cycle.baseHead,candidateBranch:successful?.candidateBranch??cycle.candidateBranch,candidateHead:successful?.candidateHead??cycle.candidateHead,updatedAt:new Date(now).toISOString(),reason:item.transitionReason.slice(0,500)};await repository.savePilotCycle(next);return next;}
