import type{WorkItem}from"../domain/work-item.js";
import{parseAcceptanceCriteria}from"../domain/verification.js";
import{hasPilotLabels,matchesPilotScope,scopeFingerprint,type PilotControl,type PilotCycle,type PilotScope}from"../domain/pilot.js";
import{transitionWorkItem}from"../domain/work-state-machine.js";
import type{ExecutionState}from"./execution.js";
import type{VerificationState}from"../domain/verification.js";

export interface PilotWorkRepository{list(repository:string):Promise<WorkItem[]>;findWorkItem(id:string):Promise<WorkItem|null>;transitionExecutionState(id:string,update:(item:WorkItem)=>WorkItem):Promise<WorkItem>}
export interface PilotCycleRepository{pilotCycles():Promise<PilotCycle[]>;savePilotCycle(cycle:PilotCycle):Promise<void>}
export interface PilotReadinessContext{workerReady:boolean;workspaceReady:boolean;profileReady:boolean}
export interface PilotRecoveryStatus{eligible:boolean;requested:boolean;consumed:boolean;reason:string;cycleId:string|null;previousFailureReason:string|null;attemptCount:number;remainingBudget:number;workState:WorkItem["workState"]|null;cycleStatus:PilotCycle["status"]|null}

export async function scopedPilotItem(repository:PilotWorkRepository,scope:PilotScope):Promise<WorkItem|null>{const matches=(await repository.list(scope.repository)).filter(item=>matchesPilotScope(item,scope));return matches.length===1?matches[0]!:null;}
export function readinessReason(item:WorkItem|null,scope:PilotScope,context:PilotReadinessContext,now=Date.now()):string|null{if(!item||!matchesPilotScope(item,scope))return"exact scoped WorkItem not found";if(!hasPilotLabels(item,scope))return"required pilot labels are missing";if(!item.definitionReady)return"deterministic Definition gate is incomplete";if(!parseAcceptanceCriteria(item.acceptanceCriteria).valid)return"Acceptance Criteria are missing or malformed";if(Date.parse(scope.expiresAt)<=now)return"pilot scope is expired";if(!context.workerReady||!context.workspaceReady||!context.profileReady)return"worker, workspace, or verification profile is unavailable";return null;}
export class PilotReadinessService{
  constructor(private work:PilotWorkRepository,private cycles:PilotCycleRepository,private control:PilotControl,private context:PilotReadinessContext,private now:()=>number=Date.now,private executionState:()=>Promise<ExecutionState>=async()=>({leases:[],records:[]})){}
  async evaluate():Promise<{ready:boolean;reason:string;item:WorkItem|null;cycle:PilotCycle|null}>{
    const scope=this.control.scope;if(!this.control.enabled||!scope)return{ready:false,reason:this.control.reason,item:null,cycle:null};
    let item=await scopedPilotItem(this.work,scope),existing=(await this.cycles.pilotCycles()).find(cycle=>cycle.cycleId===scope.cycleId);
    if(existing){
      if(existing.scopeFingerprint!==scopeFingerprint(scope)||existing.workItemId!==item?.id)return{ready:false,reason:"active cycle scope cannot be retargeted",item,cycle:existing};
      if(this.control.recoveryId===scope.cycleId&&item){const recovered=await this.recover(item,existing);item=recovered.item;existing=recovered.cycle;}
      return{ready:existing.status==="ARMED"&&(item?.workState==="READY"||item?.workState==="RETRYING"),reason:existing.reason,item,cycle:existing};
    }
    const blocker=readinessReason(item,scope,this.context,this.now());if(blocker||!item)return{ready:false,reason:blocker??"pilot readiness rejected",item,cycle:null};if(item.workState!=="DEFINED")return{ready:false,reason:"scoped WorkItem is not DEFINED",item,cycle:null};const updated=await this.work.transitionExecutionState(item.id,current=>transitionWorkItem(current,{type:"DEFINITION_COMPLETED",executor:"CODEX"}).workItem),timestamp=new Date(this.now()).toISOString(),cycle:PilotCycle={cycleId:scope.cycleId,scopeFingerprint:scopeFingerprint(scope),workItemId:updated.id,status:"ARMED",baseHead:null,candidateBranch:null,candidateHead:null,executionAttempts:0,verificationRuns:0,startedAt:timestamp,updatedAt:timestamp,reason:"Pilot readiness gate passed",recoveryRequestId:null,recoveryConsumedAt:null,recoveryCount:0,previousFailureReason:null};await this.cycles.savePilotCycle(cycle);return{ready:true,reason:cycle.reason,item:updated,cycle};
  }
  async recoveryStatus():Promise<PilotRecoveryStatus>{const scope=this.control.scope,item=scope?await scopedPilotItem(this.work,scope):null,cycle=scope?(await this.cycles.pilotCycles()).find(value=>value.cycleId===scope.cycleId)??null:null,state=await this.executionState();return assessPilotRecovery(this.control,scope,item,cycle,state,this.context,this.now());}
  private async recover(item:WorkItem,cycle:PilotCycle):Promise<{item:WorkItem;cycle:PilotCycle}>{
    if(cycle.recoveryRequestId===this.control.recoveryId&&cycle.recoveryConsumedAt){if(item.workState==="FAILED"){item=await this.work.transitionExecutionState(item.id,current=>transitionWorkItem(current,{type:"RETRY_STARTED"}).workItem);}return{item,cycle};}
    const assessment=assessPilotRecovery(this.control,this.control.scope,item,cycle,await this.executionState(),this.context,this.now());if(!assessment.eligible)return{item,cycle};
    const timestamp=new Date(this.now()).toISOString(),next={...cycle,status:"ARMED" as const,recoveryRequestId:this.control.recoveryId,recoveryConsumedAt:timestamp,recoveryCount:(cycle.recoveryCount??0)+1,previousFailureReason:item.transitionReason.slice(0,500),updatedAt:timestamp,reason:"Explicit Pilot Recovery consumed; retry dispatch armed"};
    await this.cycles.savePilotCycle(next);item=await this.work.transitionExecutionState(item.id,current=>transitionWorkItem(current,{type:"RETRY_STARTED"}).workItem);return{item,cycle:next};
  }
}
export function assessPilotRecovery(control:PilotControl,scope:PilotScope|null,item:WorkItem|null,cycle:PilotCycle|null,execution:ExecutionState,context:PilotReadinessContext,now=Date.now()):PilotRecoveryStatus{const attempts=cycle?.executionAttempts??0,grant=cycle?.recoveryCount??0,limit=(scope?.maxExecutionAttempts??0)+grant,base={requested:!!control.recoveryId,consumed:!!cycle?.recoveryConsumedAt,cycleId:cycle?.cycleId??scope?.cycleId??null,previousFailureReason:cycle?.previousFailureReason??(item?.workState==="FAILED"?item.transitionReason:null),attemptCount:attempts,remainingBudget:Math.max(0,limit-attempts),workState:item?.workState??null,cycleStatus:cycle?.status??null};const reject=(reason:string):PilotRecoveryStatus=>({...base,eligible:false,reason});if(!control.enabled||!scope)return reject(control.reason);if(control.recoveryId&&control.recoveryId!==scope.cycleId)return reject("recovery request does not match cycleId");if(!cycle||cycle.scopeFingerprint!==scopeFingerprint(scope))return reject("scope fingerprint mismatch");if(!item||cycle.workItemId!==item.id||!matchesPilotScope(item,scope))return reject("WorkItem mismatch");if(cycle.recoveryConsumedAt||cycle.recoveryCount)return reject("recovery request already consumed");if(cycle.status!=="FAILED")return reject("PilotCycle is not FAILED");if(item.workState!=="FAILED")return reject("WorkItem is not FAILED");const blocker=readinessReason(item,scope,context,now);if(blocker)return reject(blocker);const records=execution.records.filter(value=>value.workItemId===item.id),latest=records.at(-1);if(!latest||latest.resultStatus!=="FAILED"||latest.baseHead||latest.candidateBranch||latest.candidateHead)return reject("failure is not a pre-Codex execution failure");if(latest.retryable!==true&&!item.transitionReason.startsWith("RETRYABLE_FAILURE accepted"))return reject("failure is terminal or non-recoverable");if(grant>=1)return reject("recovery grant exhausted");return{...base,eligible:true,reason:"pre-Codex retryable infrastructure/setup failure"};}
export function pilotExecutionCandidates(items:readonly WorkItem[],control:PilotControl,cycle:PilotCycle|null):string[]{const scope=control.scope,effectiveLimit=scope?scope.maxExecutionAttempts+(cycle?.recoveryCount??0):0;if(!control.enabled||!scope||!cycle||cycle.status!=="ARMED"||cycle.executionAttempts>=effectiveLimit)return[];return items.filter(item=>item.id===cycle.workItemId&&matchesPilotScope(item,scope)&&hasPilotLabels(item,scope)&&(item.workState==="READY"||item.workState==="RETRYING")).map(item=>item.id).slice(0,1);}
export function pilotVerificationCandidates(items:readonly WorkItem[],control:PilotControl,cycle:PilotCycle|null):string[]{const scope=control.scope;if(!control.enabled||!scope||!cycle||cycle.status!=="VERIFYING"||cycle.verificationRuns>=scope.maxVerificationRuns)return[];return items.filter(item=>item.id===cycle.workItemId&&matchesPilotScope(item,scope)&&item.workState==="VERIFYING").map(item=>item.id).slice(0,1);}
export async function reconcilePilotCycle(repository:PilotCycleRepository,cycle:PilotCycle,item:WorkItem,execution:ExecutionState,verification:VerificationState,now=Date.now()):Promise<PilotCycle>{const records=execution.records.filter(value=>value.workItemId===cycle.workItemId),checks=verification.records.filter(value=>value.workItemId===cycle.workItemId),successful=[...records].reverse().find(value=>value.resultStatus==="SUCCEEDED"),status:PilotCycle["status"]=item.workState==="WAITING_HUMAN"?"WAITING_HUMAN":item.workState==="VERIFYING"?"VERIFYING":item.workState==="RUNNING"?"EXECUTING":item.workState==="FAILED"?"FAILED":cycle.status,next={...cycle,status,executionAttempts:records.length,verificationRuns:checks.length,baseHead:successful?.baseHead??cycle.baseHead,candidateBranch:successful?.candidateBranch??cycle.candidateBranch,candidateHead:successful?.candidateHead??cycle.candidateHead,updatedAt:new Date(now).toISOString(),reason:item.transitionReason.slice(0,500)};await repository.savePilotCycle(next);return next;}
