import { randomUUID } from "node:crypto";
import type { WorkItem } from "../domain/work-item.js";
import { transitionWorkItem } from "../domain/work-state-machine.js";
import { decideVerification,parseAcceptanceCriteria,verificationPlan,type VerificationCriterion,type VerificationRequest,type VerificationResult,type VerificationState } from "../domain/verification.js";
import type { ExecutionState,WorkerDescriptor } from "./execution.js";

export interface RepositoryVerificationTarget{repository:string;workerId:string;workspaceId:string;profileId:string;checkIds:string[]}
export interface VerificationExecutor{execute(request:VerificationRequest):Promise<VerificationResult>}
export interface VerificationWorkerRegistry{get(workerId:string):Promise<WorkerDescriptor|null>}
export interface AcquireVerificationCommand{request:VerificationRequest;workerId:string;requestedAt:string;criteria:VerificationCriterion[]}
export interface VerificationRepository{findWorkItem(id:string):Promise<WorkItem|null>;transitionExecutionState(id:string,update:(item:WorkItem)=>WorkItem):Promise<WorkItem>;executionState():Promise<ExecutionState>;verificationState():Promise<VerificationState>;acquireVerification(command:AcquireVerificationCommand):Promise<boolean>;completeVerification(id:string,result:VerificationResult):Promise<WorkItem|null>}
export interface VerificationGateDecision{status:"ELIGIBLE"|"REJECTED"|"WAITING_WORKER"|"ALREADY_RUNNING";reason:string}

export function evaluateVerificationGate(item:WorkItem,target:RepositoryVerificationTarget|null,worker:WorkerDescriptor|null,execution:ExecutionState,state:VerificationState):VerificationGateDecision{if(item.workState!=="VERIFYING"||item.ballHolder!=="LCC"||item.nextAction.kind!=="VERIFY"||!item.nextAction.aiExecutable)return rejected("WorkItem verification state is not eligible");if(!target||target.repository!==item.source.repository)return rejected("repository verification target is not uniquely configured");const source=[...execution.records].reverse().find(record=>record.workItemId===item.id&&record.resultStatus==="SUCCEEDED");if(!source)return rejected("successful source execution is required");if(state.leases.some(lease=>lease.status==="ACTIVE"&&(lease.workItemId===item.id||lease.repository===item.source.repository)))return{status:"ALREADY_RUNNING",reason:"active verification lease exists"};if(!worker||worker.workerId!==target.workerId||worker.status!=="ONLINE")return{status:"WAITING_WORKER",reason:"verification worker is unavailable"};const profileChecks=worker.verificationProfiles?.[target.profileId];if(!worker.workspaceIds.includes(target.workspaceId)||!worker.executorKinds.includes("VERIFICATION")||!profileChecks||target.checkIds.some(id=>!profileChecks.includes(id)))return{status:"WAITING_WORKER",reason:"worker is not verification capable for the configured profile"};return{status:"ELIGIBLE",reason:"verification gate passed"};}
export class VerificationService{private stopping=false;private inflight=new Set<Promise<unknown>>();constructor(private repository:VerificationRepository,private targets:readonly RepositoryVerificationTarget[],private workers:VerificationWorkerRegistry,private executor:VerificationExecutor,private now:()=>number=Date.now,private id:()=>string=randomUUID){}async verify(workItemId:string):Promise<VerificationGateDecision>{if(this.stopping)return rejected("verification service is shutting down");const item=await this.repository.findWorkItem(workItemId);if(!item)return rejected("WorkItem not found");const targets=this.targets.filter(value=>value.repository===item.source.repository),target=targets.length===1?targets[0]!:null,worker=target?await this.workers.get(target.workerId):null,execution=await this.repository.executionState(),state=await this.repository.verificationState(),gate=evaluateVerificationGate(item,target,worker,execution,state);if(gate.status!=="ELIGIBLE"||!target||!worker)return gate;const parsed=parseAcceptanceCriteria(item.acceptanceCriteria),plan=verificationPlan(parsed,target.checkIds);if(!plan.valid){await this.repository.transitionExecutionState(item.id,current=>transitionWorkItem(current,{type:"HUMAN_REQUIRED",summary:plan.reason}).workItem);return rejected(plan.reason);}const source=[...execution.records].reverse().find(record=>record.workItemId===item.id&&record.resultStatus==="SUCCEEDED")!;const request:VerificationRequest={verificationId:this.id(),workItemId:item.id,sourceExecutionId:source.executionId,repository:item.source.repository,workspaceId:target.workspaceId,profileId:target.profileId,checkIds:plan.checkIds};if(!await this.repository.acquireVerification({request,workerId:worker.workerId,requestedAt:new Date(this.now()).toISOString(),criteria:plan.criteria}))return{status:"ALREADY_RUNNING",reason:"verification lease acquisition rejected"};const operation=this.run(request);this.inflight.add(operation);try{await operation;}finally{this.inflight.delete(operation);}return gate;}async stop():Promise<void>{this.stopping=true;await Promise.allSettled(this.inflight);}private async run(request:VerificationRequest):Promise<void>{let result:VerificationResult;try{if(request.checkIds.length===0){const now=new Date(this.now()).toISOString();result={verificationId:request.verificationId,status:"PASSED",startedAt:now,finishedAt:now,checks:[],summary:"No AUTO checks; HUMAN criteria remain",evidence:[]};}else result=await this.executor.execute(request);}catch(error){const now=new Date(this.now()).toISOString();result={verificationId:request.verificationId,status:"ERROR",startedAt:now,finishedAt:now,checks:[],summary:error instanceof Error?error.message:"verification infrastructure error",evidence:[]};}await this.repository.completeVerification(request.verificationId,sanitizeResult(result));}}
export function verificationDecision(criteria:readonly VerificationCriterion[],result:VerificationResult){if(result.status==="ERROR"||result.status==="CANCELLED")return{status:"ERROR" as const,criterionEvidence:[],reason:"Verification infrastructure unavailable"};const decision=decideVerification(criteria,result.checks);return result.status==="FAILED"&&decision.status!=="FAILED"?{...decision,status:"FAILED" as const,reason:"Worker reported verification failure"}:decision;}
function sanitizeResult(result:VerificationResult):VerificationResult{return{...result,summary:redact(result.summary,500),evidence:result.evidence.slice(0,10).map(v=>redact(v,500)),checks:result.checks.slice(0,20).map(check=>({...check,summary:redact(check.summary,500),evidence:check.evidence.slice(0,10).map(v=>redact(v,500))}))};}
export function redact(value:string,limit:number):string{return value.replace(/(token|secret|api[_-]?key)\s*[:=]\s*\S+/gi,"$1=[REDACTED]").replace(/Bearer\s+\S+/gi,"Bearer [REDACTED]").replace(/[A-Za-z]:\\(?:[^\s\\]+\\)+[^\s]*/g,"[LOCAL_PATH]").replace(/\/(?:home|Users|tmp|var)\/[^\s]*/g,"[LOCAL_PATH]").slice(-limit);}
function rejected(reason:string):VerificationGateDecision{return{status:"REJECTED",reason};}
