import type { ProductsManifest } from "./products.js";
import { IssueSyncService, type IssueSource, type WorkItemRepository } from "./application/issue-sync-service.js";
import { IssuePollingRuntime, pollIntervalFromEnvironment, type Scheduler } from "./application/issue-polling-runtime.js";
import { GitHubIssueAdapter } from "./infrastructure/github-issue-adapter.js";
import { DurableWorkItemRepository, workItemDatabasePath } from "./infrastructure/durable-work-item-repository.js";
import { ExecutionService, type ExecutionRepository, type RepositoryExecutionTarget } from "./application/execution.js";
import { ExecutionScanner, workExecutionEnabled } from "./application/execution-scanner.js";
import { RemoteCodexExecutor, RemoteVerificationExecutor, RemoteWorkerRegistry, type RemoteWorkerConfig } from "./infrastructure/remote-execution.js";
import { ExecutionReconciler } from "./application/execution-reconciler.js";
import { VerificationService, type RepositoryVerificationTarget, type VerificationRepository } from "./application/verification.js";
import { VerificationScanner, workVerificationEnabled } from "./application/verification-scanner.js";
import { VerificationReconciler } from "./application/verification-reconciler.js";
import { parsePilotControl, type PilotControl, type PilotCycle } from "./domain/pilot.js";
import type { WorkItem } from "./domain/work-item.js";
import { DurablePilotCycleRepository } from "./infrastructure/durable-pilot-cycle-repository.js";
import { PilotReadinessService, pilotExecutionCandidates, pilotVerificationCandidates, reconcilePilotCycle, type PilotCycleRepository } from "./application/pilot-control.js";

export function discoverRepositories(manifest: ProductsManifest): string[] { return [...new Set(manifest.products.flatMap(product => product.repository ? [product.repository] : []))]; }
export interface CompositionDependencies { openRepository?: (path:string)=>Promise<WorkItemRepository>;source?:IssueSource;scheduler?:Scheduler }
export interface IssueRuntimeComposition { repository:WorkItemRepository&Partial<ExecutionRepository&VerificationRepository>;adapter:GitHubIssueAdapter|IssueSource;syncService:IssueSyncService;runtime:IssuePollingRuntime }
export async function composeIssueRuntime(manifest:ProductsManifest,environment:NodeJS.ProcessEnv=process.env,dependencies:CompositionDependencies={}):Promise<IssueRuntimeComposition>{const repository=await(dependencies.openRepository??DurableWorkItemRepository.open)(workItemDatabasePath(environment)),adapter=dependencies.source??new GitHubIssueAdapter(fetch,environment.GITHUB_TOKEN),syncService=new IssueSyncService(adapter,repository),runtime=new IssuePollingRuntime(discoverRepositories(manifest),syncService,pollIntervalFromEnvironment(environment),dependencies.scheduler);return{repository:repository as WorkItemRepository&Partial<ExecutionRepository&VerificationRepository>,adapter,syncService,runtime};}

export interface PilotRuntimeComposition{control:PilotControl;cycles:PilotCycleRepository;readiness:PilotReadinessService;targetReady:boolean;refresh(item:WorkItem|null):Promise<PilotCycle|null>}
export async function composePilotRuntime(repository:WorkItemRepository&ExecutionRepository&VerificationRepository,environment:NodeJS.ProcessEnv=process.env):Promise<PilotRuntimeComposition>{const control=parsePilotControl(environment),path=environment.WORK_PILOT_STATE_PATH?.trim()||"/var/lib/luckountry-control-center/pilot-cycles.json",cycles:PilotCycleRepository=control.scope?await DurablePilotCycleRepository.open(path):new InactivePilotCycles(),scope=control.scope,targets=safeJson<RepositoryVerificationTarget[]>(environment.WORK_VERIFICATION_TARGETS_JSON),targetReady=await pilotTargetReady(environment,scope,targets),readiness=new PilotReadinessService(repository,cycles,control,{workerReady:targetReady,workspaceReady:targetReady,profileReady:targetReady},Date.now,()=>repository.executionState());return{control,cycles,readiness,targetReady,async refresh(item){if(!item||!scope)return null;const cycle=(await cycles.pilotCycles()).find(value=>value.cycleId===scope.cycleId);return cycle?reconcilePilotCycle(cycles,cycle,item,await repository.executionState(),await repository.verificationState()):null;}};}

export interface VerificationRuntimeComposition{service:VerificationService;scanner:VerificationScanner;reconciler:VerificationReconciler}
export async function composeVerificationRuntime(repository:WorkItemRepository&ExecutionRepository&VerificationRepository,repositories:readonly string[],environment:NodeJS.ProcessEnv=process.env,pilotRuntime?:PilotRuntimeComposition):Promise<VerificationRuntimeComposition|null>{const pilot=pilotRuntime??await composePilotRuntime(repository,environment);if(!workVerificationEnabled(environment)||!pilot.control.enabled||!pilot.control.scope)return null;const scope=pilot.control.scope,workerId=environment.WORKER_ID?.trim(),baseUrl=environment.WORKER_URL?.trim(),keyId=environment.WORKER_HMAC_KEY_ID?.trim(),secret=environment.WORKER_HMAC_SECRET,targets=safeJson<RepositoryVerificationTarget[]>(environment.WORK_VERIFICATION_TARGETS_JSON);if(!workerId||!baseUrl||!keyId||!secret||!Array.isArray(targets)||targets.length!==1||targets[0]?.repository!==scope.repository||targets[0].workerId!==scope.workerId||targets[0].workspaceId!==scope.workspaceId||targets[0].profileId!==scope.verificationProfileId||!repositories.includes(scope.repository)||!targets[0].checkIds.length)return null;const remotes:RemoteWorkerConfig[]=[{workerId,baseUrl,credentials:{keyId,secret}}],registry=new RemoteWorkerRegistry(remotes),executor=new RemoteVerificationExecutor(remotes,()=>workerId),service=new VerificationService(repository,targets,registry,executor),scanner=new VerificationScanner(repository,service,true,async()=>{const readiness=await pilot.readiness.evaluate(),cycle=await pilot.refresh(readiness.item);return readiness.item?pilotVerificationCandidates([readiness.item],pilot.control,cycle):[];}),reconciler=new VerificationReconciler(repository,executor);await reconciler.reconcile();return{service,scanner,reconciler};}

export interface ExecutionRuntimeComposition{service:ExecutionService;scanner:ExecutionScanner;reconciler:ExecutionReconciler}
export async function composeExecutionRuntime(repository:WorkItemRepository&ExecutionRepository&VerificationRepository,repositories:readonly string[],environment:NodeJS.ProcessEnv=process.env,pilotRuntime?:PilotRuntimeComposition):Promise<ExecutionRuntimeComposition|null>{const pilot=pilotRuntime??await composePilotRuntime(repository,environment);if(!workExecutionEnabled(environment)||!pilot.control.enabled||!pilot.control.scope)return null;const scope=pilot.control.scope,workerId=environment.WORKER_ID?.trim(),baseUrl=environment.WORKER_URL?.trim(),keyId=environment.WORKER_HMAC_KEY_ID?.trim(),secret=environment.WORKER_HMAC_SECRET,targets=safeJson<RepositoryExecutionTarget[]>(environment.WORK_EXECUTION_TARGETS_JSON);if(!workerId||!baseUrl||!keyId||!secret||!Array.isArray(targets)||targets.length!==1||targets[0]?.repository!==scope.repository||targets[0].workerId!==scope.workerId||targets[0].workspaceId!==scope.workspaceId||!repositories.includes(scope.repository)||targets[0].concurrency!=="EXCLUSIVE_REPOSITORY")return null;const remotes:RemoteWorkerConfig[]=[{workerId,baseUrl,credentials:{keyId,secret}}],registry=new RemoteWorkerRegistry(remotes),executor=new RemoteCodexExecutor(remotes,()=>workerId),service=new ExecutionService(repository,targets,registry,executor,Date.now,undefined,scope),scanner=new ExecutionScanner(repository,service,true,async()=>{const readiness=await pilot.readiness.evaluate(),cycle=await pilot.refresh(readiness.item);return readiness.item?pilotExecutionCandidates([readiness.item],pilot.control,cycle):[];}),reconciler=new ExecutionReconciler(repository,executor);await reconciler.reconcile();return{service,scanner,reconciler};}
function safeJson<T>(value:string|undefined):T|null{try{return JSON.parse(value??"") as T;}catch{return null;}}
class InactivePilotCycles implements PilotCycleRepository{async pilotCycles(){return[];}async savePilotCycle(){throw new Error("pilot automation is disabled");}}
async function pilotTargetReady(environment:NodeJS.ProcessEnv,scope:PilotControl["scope"],targets:RepositoryVerificationTarget[]|null):Promise<boolean>{if(!scope||!Array.isArray(targets)||!targets.some(target=>target.repository===scope.repository&&target.workerId===scope.workerId&&target.workspaceId===scope.workspaceId&&target.profileId===scope.verificationProfileId))return false;const baseUrl=environment.WORKER_URL?.trim(),keyId=environment.WORKER_HMAC_KEY_ID?.trim(),secret=environment.WORKER_HMAC_SECRET;if(!baseUrl||!keyId||!secret)return false;const worker=await new RemoteWorkerRegistry([{workerId:scope.workerId,baseUrl,credentials:{keyId,secret}}]).get(scope.workerId),checks=worker?.verificationProfiles?.[scope.verificationProfileId];return!!worker&&worker.status==="ONLINE"&&worker.workspaceIds.includes(scope.workspaceId)&&worker.executorKinds.includes("CODEX")&&worker.executorKinds.includes("VERIFICATION")&&Array.isArray(checks);}
