import { join, resolve } from "node:path";
import type { ExecutionRepository, ExecutionRequest } from "./application/execution.js";
import { AutomaticEvidenceReporter, DurableEvidenceOutbox, GitHubCommentTransport } from "./application/evidence-reporting.js";
import { ProductionSelfCommissioningControl } from "./application/production-self-commissioning.js";
import { DurableSelfCommissioningStore, SelfCommissioningOrchestrator, type CommissioningExecutors } from "./application/self-commissioning.js";
import { TxMaintenanceService, reconcilePilotStore } from "./application/tx-maintenance.js";
import type { VerificationRepository } from "./application/verification.js";
import { DurablePilotCycleRepository } from "./infrastructure/durable-pilot-cycle-repository.js";
import { RemoteCodexExecutor, RemoteWorkerMaintenanceClient, RemoteWorkerRegistry, type RemoteWorkerConfig } from "./infrastructure/remote-execution.js";
import { FixedTxCommandRunner } from "./infrastructure/tx-command-runner.js";
import type { WorkItemRepository } from "./application/issue-sync-service.js";

type DurableRepository=WorkItemRepository&ExecutionRepository&VerificationRepository;
export interface ProductionSelfCommissioningComposition{control:ProductionSelfCommissioningControl;token:string;readiness():Promise<true|string>}
export async function composeProductionSelfCommissioning(repository:DurableRepository,environment:NodeJS.ProcessEnv=process.env):Promise<ProductionSelfCommissioningComposition>{
  const data=resolve(environment.LCC_DATA_DIRECTORY?.trim()||"/var/lib/luckountry-control-center"),runs=await DurableSelfCommissioningStore.open(join(data,"self-commissioning-runs.json")),outbox=await DurableEvidenceOutbox.open(join(data,"self-commissioning-github-outbox.json")),pilotPath=resolve(environment.WORK_PILOT_STATE_PATH?.trim()||join(data,"pilot-cycles.json")),cycles=await DurablePilotCycleRepository.open(pilotPath),repositoryPath=resolve(environment.LCC_REPOSITORY_PATH?.trim()||"/opt/luckountry-control-center"),workerId=environment.WORKER_ID?.trim()||"",baseUrl=environment.WORKER_URL?.trim()||"",keyId=environment.WORKER_HMAC_KEY_ID?.trim()||"",secret=environment.WORKER_HMAC_SECRET||"",remote:RemoteWorkerConfig={workerId,baseUrl,credentials:{keyId,secret}},registry=new RemoteWorkerRegistry([remote]),maintenance=new RemoteWorkerMaintenanceClient(remote),codex=new RemoteCodexExecutor([remote],name=>name==="knys/TOBIE"?workerId:null),tx=new TxMaintenanceService({repositoryPath,allowedRepository:"knys/luckountry-control-center",allowedRefs:(environment.LCC_ALLOWED_UPDATE_REFS??"").split(",").map(v=>v.trim()).filter(v=>/^[0-9a-f]{40}$/i.test(v)),storePath:join(data,"tx-maintenance-results.json"),runner:new FixedTxCommandRunner(),status:async()=>["TX LCC maintenance ready"],migrate:async()=>{await DurablePilotCycleRepository.open(pilotPath);return["Pilot store readable"]},reconcile:async()=>reconcilePilotStore(cycles,await repository.executionState(),await repository.verificationState(),async id=>(await repository.findWorkItem(id))?.workState??null,new Date().toISOString())}),githubToken=environment.GITHUB_TOKEN||"",reporter=new AutomaticEvidenceReporter(outbox,new GitHubCommentTransport(githubToken),{repository:"knys/luckountry-control-center",issueNumber:18,pullNumber:19},3);
  const readiness=async():Promise<true|string>=>{if(environment.WORK_AUTOMATION_MODE!=="disabled"||environment.WORK_EXECUTION_ENABLED!=="false"||environment.WORK_VERIFICATION_ENABLED!=="false")return"Automation must be disabled before Self-Commissioning readiness";if(!workerId||!baseUrl||!keyId||!secret)return"GTX authenticated transport is not configured";if(!githubToken)return"GitHub evidence reporter is not configured";await cycles.pilotCycles();const descriptor=await registry.get(workerId);if(!descriptor||descriptor.status!=="ONLINE")return"GTX Worker descriptor is not ready";if(!descriptor.workspaceIds.includes("tobie-pilot")||!descriptor.executorKinds.includes("CODEX"))return"GTX Worker lacks fixed LCC-008 workspace or CODEX capability";return true};
  const executors:CommissioningExecutors={tx:async request=>map(await tx.execute(request)),gtx:async request=>map(await maintenance.execute(request)),codex:async(job,id)=>{const request:ExecutionRequest={executionId:id,workItemId:"github:knys/TOBIE:215",repository:job.repository,workspaceId:job.workspaceId,actionKind:"EXECUTE",summary:job.objective,requiredCapabilities:["CODEX"],sourceUrl:"https://github.com/knys/TOBIE/issues/215"},result=await codex.execute(request);return{status:result.status==="SUCCEEDED"?"SUCCEEDED":"FAILED",summary:result.summary,evidence:result.evidence,retryable:result.retryable}}},orchestrator=new SelfCommissioningOrchestrator(runs,executors),control=new ProductionSelfCommissioningControl(runs,orchestrator,{report:run=>reporter.collectAndReport(run,[{kind:"CONTROLLER",status:run.status,summary:"Production Self-Commissioning checkpoint"}]).then(()=>undefined)},readiness,environment.SELF_COMMISSIONING_ENABLED==="true");await reporter.flush();await control.resume();return{control,token:environment.SELF_COMMISSIONING_CONTROL_TOKEN||"",readiness};
}
function map(result:{status:string;summary:string;evidence:string[]}){return{status:result.status==="SUCCEEDED"?"SUCCEEDED"as const:"FAILED"as const,summary:result.summary,evidence:result.evidence,retryable:result.status==="TIMED_OUT"}}
